### ISSUE TITLE
reranker模型可以直接当embedding模型(bge v1.5)用吗？还是说必须要先用embedding模型才最好

### ISSUE THREAD

**Issue by aliencaocao** [FlagOpen/FlagEmbedding#100]

**Comment by staoxiao** [comment]
reranker模型无法当作embedding模型使用，两者模型架构不一样，输入输出也不一样。reranker直接输出分数，embedding 模型输出向量。
从另一个角度，reranker模型计算相似度也可以用来做第一阶段召回，但速度比较慢，所以推荐只做小范围内排序。

**Comment by aliencaocao** [comment]
也就是说reranker不能预先计算好一部分文本的向量是吧，明白了，谢谢解答
