### ISSUE TITLE
[Question]使用bge-multilingual-gemma2做RAG时的语言基座模型是否必须要用gemma2？

### ISSUE THREAD

**Issue by hcnhcn012** [FlagOpen/FlagEmbedding#1005]
如题，请教一下

**Comment by forestemperor** [comment]
没有关系，bge这个只是在做rerank

**Comment by hcnhcn012** [comment]
> 没有关系，bge这个只是在做rerank

@forestemperor 我想你可能说的是bge-reranker-v2.5-gemma2-lightweight，而不是embedding模型bge-multilingual-gemma2

**Comment by staoxiao** [comment]
@hcnhcn012 ， 不需要的，用来做embedding和rerank的模型不必与语言模型一样。

**Comment by hcnhcn012** [comment]
> @hcnhcn012 ， 不需要的，用来做embedding和rerank的模型不必与语言模型一样。

好的 感谢
