### ISSUE TITLE
关于余弦相似度Temperature should be smaller than 1.0的疑问

### ISSUE THREAD

**Issue by coasxu** [FlagOpen/FlagEmbedding#1008]
```
[rank0]:   File "bge-base-zh-v1.5/FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/modeling.py", line 80, in __init__
[rank0]:     raise ValueError("Temperature should be smaller than 1.0 when use cosine similarity (i.e., normlized=True). Recommend to set it 0.01-0.1")
[rank0]: ValueError: Temperature should be smaller than 1.0 when use cosine similarity (i.e., normlized=True). Recommend to set it 0.01-0.1
```
请问Temperature为什么要小于1.0呢？

**Comment by staoxiao** [comment]
cosine similarity的范围在[-1, 1]之间，loss选用的是交叉熵，在计算softmax后，概率会很平滑，各个样本的概率基本差不多，除以一个<1的Temperature，可以拉大不同样本的分数差异，让softmax之后的概率更有区分度。

**Comment by coasxu** [comment]
> cosine similarity的范围在[-1, 1]之间，loss选用的是交叉熵，在计算softmax后，概率会很平滑，各个样本的概率基本差不多，除以一个<1的Temperature，可以拉大不同样本的分数差异，让softmax之后的概率更有区分度。 如果使用dot product，相似度本身范围就很多，就不需要设置Temperature

非常感谢您的回复，很有帮助～
