### ISSUE TITLE
V1.5的相似度分布是大概0-1，平均0.5了吗？

### ISSUE THREAD

**Issue by aliencaocao** [FlagOpen/FlagEmbedding#101]
v1.0是0.6-1，平均0.8左右

**Comment by staoxiao** [comment]
没有完整统计过v1.5的相似度，无法保证平均值是0.5，但通过调整temperture参数，相似度分布的范围确实变大了。

**Comment by aliencaocao** [comment]
好的，如果将来有相关的统计，麻烦加到readme里，谢谢

**Comment by Nipi64310** [comment]
> 没有完整统计过v1.5的相似度，无法保证平均值是0.5，但通过调整temperture参数，相似度分布的范围确实变大了。

Hi @staoxiao ,

根据readme提到的
> 建议使用bge v1.5，它缓解了相似度分布的问题。
> 
> 由于我们通过温度为0.01的对比学习来微调模型， 当前BGE模型的相似度分布大约在[0.6, 1]区间内。 因此，相似度大于0.6并不表示这两个句子相似。

> 对于下游任务，如段落检索或语义相似性， 重要的是分数的相对顺序，而不是绝对值。 如果你需要根据相似度阈值过滤相似句子， 请根据数据的相似度分布(如0.8,0.85，甚至0.9)选择合适的相似度阈值。

v1.5明显降低了不相似pair对的相似度分数，是只通过训练的时候调高temperature参数来实现的吗？请问训练的时候还有没有其他的优化策略？
