### ISSUE TITLE
sentence_pooling_method参数问题

### ISSUE THREAD

**Issue by nanyoullm** [FlagOpen/FlagEmbedding#102]
7号提交的版本，微调会报这样的错
```dataclasses.FrozenInstanceError: cannot assign to field sentence_pooling_method```

**Comment by staoxiao** [comment]
建议更新到最新版本。如果不行的话，可以提供微调指令查看是否出错。

**Comment by nanyoullm** [comment]
是最新版本呢，我自行改了些可以跑了。
```torchrun --nproc_per_node 1 -m FlagEmbedding.baai_general_embedding.finetune.run --output_dir bge_finetune_v1.6 --model_name_or_path BAAI/bge-base-zh --train_data dataset/v1_6/HN_bge_fine_tune.jsonl --learning_rate 1e-5 --fp16 --num_train_epochs 5 --per_device_train_batch_size 64 --normlized True --temperature 0.02 --query_max_len 64 --passage_max_len 256 --train_group_size 3 --negatives_cross_device --query_instruction_for_retrieval "为这个句子生成表示以用于检索相关文章：" --ddp_backend gloo --logging_steps 10```
