### ISSUE TITLE
基于minicpm微调后MiniCPMForCausalLM.forward() got an unexpected keyword argument 'cutoff_layers'

### ISSUE THREAD

**Issue by momo4826** [FlagOpen/FlagEmbedding#1025]
1. 微调代码：
CUDA_VISIBLE_DEVICES=1 torchrun --nproc_per_node 1 \
-m FlagEmbedding.llm_reranker.finetune_for_layerwise.run \
--output_dir model/v2_reranker_3 \
--model_name_or_path /data/mnt/ShareFolder/common_models/MiniCPM-2B-dpo-bf16 \
--train_data raw_data/train2_reranker_1.json \
--learning_rate 2e-4 \
--num_train_epochs 1 \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 16 \
--dataloader_drop_last True \
--query_max_len 256 \
--passage_max_len 256 \
--train_group_size 8 \
--logging_steps 1 \
--save_steps 2000 \
--save_total_limit 50 \
--ddp_find_unused_parameters False \
--gradient_checkpointing \
--deepspeed stage1.json \
--warmup_ratio 0.1 \
--bf16 \
--use_lora True \
--lora_rank 32 \
--lora_alpha 64 \
--use_flash_attn True \
--target_modules q_proj k_proj v_proj o_proj \
--start_layer 8 \
--head_multi True \
--head_type simple \
--lora_extra_parameters linear_head \
--finetune_type from_raw_model

2. 合并代码：
merge_layerwise_raw_llm('/data/mnt/ShareFolder/common_models/MiniCPM-2B-dpo-bf16/', '/data/mnt/ShareFolder/code/retrieval_finetune/model/v2_reranker_3/', '/data/mnt/ShareFolder/code/retrieval_finetune/model/v2_reranker_3_mixed')

3. 微调和合并都是按照官方提供的指导来的，但是合并后的微调模型在推理时报错：MiniCPMForCausalLM.forward() got an unexpected keyword argument 'cutoff_layers'

请问是什么原因？

**Comment by 545999961** [comment]
You can replace the `config.json` in `/data/mnt/ShareFolder/code/retrieval_finetune/model/v2_reranker_3_mixed'` with the `config.json` from [BAAI/bge-reranker-v2-minicpm-layerwise](https://huggingface.co/BAAI/bge-reranker-v2-minicpm-layerwise/blob/main/config.json).

**Comment by momo4826** [comment]
> You can replace the `config.json` in `/data/mnt/ShareFolder/code/retrieval_finetune/model/v2_reranker_3_mixed'` with the `config.json` from [BAAI/bge-reranker-v2-minicpm-layerwise](https://huggingface.co/BAAI/bge-reranker-v2-minicpm-layerwise/blob/main/config.json).

感谢感谢！解决了
