### ISSUE TITLE
无法复现TTFT in activation beacon

### ISSUE THREAD

**Issue by Lu-kuan-lpk** [FlagOpen/FlagEmbedding#1033]
在测试beacon windows和stride都为2048的qwen base model的TTFT使发现和论文的结果存在差距（32K context用时3s以上，文中为0.5s），发现https://github.com/FlagOpen/FlagEmbedding/blob/master/Long_LLM/activation_beacon/new/src/qwen2/modeling_qwen2.py#L541
处耗时很大，这是否正常呢

**Comment by namespace-Pt** [comment]
hi, 要复现论文结果, 需要用old代码. 新的代码这里尚未做速度优化, 近期会更新一下

**Comment by Lu-kuan-lpk** [comment]
THX！
