### ISSUE TITLE
hard negative相关问题

### ISSUE THREAD

**Issue by MoYang94** [FlagOpen/FlagEmbedding#106]
你好，请问在你的finetuning阶段使用的hard `negative是经过这个命令挖掘出来的吗`python -m FlagEmbedding.baai_general_embedding.finetune.hn_mine \
--model_name_or_path BAAI/bge-base-en \
--input_file toy_finetune_data.jsonl \
--output_file toy_finetune_data_minedHN.jsonl \
--range_for_sampling 2-200 \
--query_instruction_for_retrieval "Represent this sentence for searching relevant passages: "`

**Comment by mechigonft** [comment]
你好，请问candidate_pool的格式是怎么样的？有给出吗？

**Comment by staoxiao** [comment]
和pre-train数据格式一致，可以参考 https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/pretrain#2-data-format
