### ISSUE TITLE
希望能使用vllm加速llm reranker

### ISSUE THREAD

**Issue by ericxk** [FlagOpen/FlagEmbedding#1060]

**Comment by skycore9** [comment]
+1

**Comment by eureka336** [comment]
+1

**Comment by Cloopen-ReLiNK** [comment]
+1

**Comment by ericxk** [comment]
组内同事帮忙实现了，有一些小改动

**Comment by codewen77** [comment]
> 组内同事帮忙实现了，有一些小改动

相比TensorRT和onnx有多大提升啊。 能否提供一下参考代码

**Comment by EvanSong77** [comment]
> > > 组内同事帮忙实现了，有一些小改动
> > 
> > 
> > 相比TensorRT和onnx有多大提升啊。 能否提供一下参考代码
> 
> avg p90 p99等耗时指标降低一半多，收益挺明显的，比预期高（之前以为只返回一个token，耗时优化应该不太明显)，强力推荐

可否分享一下示例代码

**Comment by zhouyuustc** [comment]
可否分享一下示例代码 +1

**Comment by EvanSong77** [comment]
去用vllm部署吧，现在vllm已经支持bge reranker了

**Comment by gaopeiyang** [comment]
> 去用vllm部署吧，现在vllm已经支持bge reranker了

有示例代码吗
