### ISSUE TITLE
VISTA Train & Evaluation Code

### ISSUE THREAD

**Issue by kimwongyuda** [FlagOpen/FlagEmbedding#1085]
I'm inspired by your nice work, "VISTA: Visualized Text Embedding For Universal Multi-Modal Retrieval" (Visualized BGE).

I would like to reproduce the model but VISTA project (FlagOpen/FlagEmbedding/visual/) doesn't have training and evaluation code unlike other projects.

It has only modelling code. Could you provide those for reproduction and test?

Thank you.

**Comment by JUNJIE99** [comment]
Thank you for your interest in our work!

We've made the relevant code available [here](https://github.com/JUNJIE99/VISTA_Evaluation_FineTuning). If you have any additional questions, please feel free to reach out.
