### ISSUE TITLE
Model shortname is required -- Open WebUI RAG

### ISSUE THREAD

**Issue by qiulang** [FlagOpen/FlagEmbedding#1086]
我想在 Open WebUI RAG的用 "BAAI/bge-base-zh-v1.5"，如下图
![BAAI/bge-base-zh-v1.5](https://github.com/user-attachments/assets/c699d479-407e-4e7e-8aef-cc890de58086)

但是报错 Model filesystem path detected. Model shortname is required for update, cannot continue.

请问 Model shortname  是什么，没查到。谢谢

![Model shortname](https://github.com/user-attachments/assets/841d3258-03ac-484e-ae41-99ee28aca574)

**Comment by staoxiao** [comment]
去掉sentence_transformers，只用BAAI/bge-base-zh-v1.5试试

**Comment by qiulang** [comment]
确实是，谢谢！
<img width="643" alt="BAAI/bge-base-zh-v1.5" src="https://github.com/user-attachments/assets/2e69298c-fe35-4de1-a2f6-24730eb88bc6">
