### ISSUE TITLE
FlagLLMReranker Multiple GPUs doesn't work

### ISSUE THREAD

**Issue by by1e11** [FlagOpen/FlagEmbedding#1091]
Hi, I always get cuda out of memory errors even I have set CUDA_VISIBLE_DEVICES="3,4,5". It seems the model is always using cuda0 to load the model. Could you please help?

Thanks

**Comment by 545999961** [comment]
Where do you set `CUDA_VISIBLE_DEVICES="3,4,5"`, you should set it outside the document or at the very beginning of the code.

**Comment by by1e11** [comment]
Yes, that's what I did.
I executed CUDA_VISIBLE_DEVICES=4,5,6 python3 get_embedding.py

and got the error:

![Screenshot from 2024-08-30 14-25-40](https://github.com/user-attachments/assets/b10801b7-3f0c-4131-b5d9-53005a3b257e)

**Comment by by1e11** [comment]
After inspecting the code, it seems the FlagLLMReranker (shown below) has different implementation with such as BGEM3FlagModel 
```python
if device and isinstance(device, str):
            self.device = torch.device(device)
        else:
            device = 0 if device is None else device
            if torch.cuda.is_available():
                torch.cuda.set_device(device)
                self.device = torch.device("cuda")
            elif torch.backends.mps.is_available():
                self.device = torch.device("mps")
            elif is_torch_npu_available():
                self.device = torch.device("npu")
            else:
                self.device = torch.device("cpu")
                use_fp16 = False

        if use_fp16 and use_bf16 is False:
            self.model.half()

        self.model = self.model.to(self.device)

        self.model.eval()
```
I'm not sure where did you parallelize the model and whether data parallelism is supported for FlagLLMReranker or not.
Please let me know if I made something wrong.

Thanks

**Comment by 545999961** [comment]
Due to the large memory consumption of LLM-based rerankers when using DP multi-card inference, we do not provide multi-card parallelism for LLM-based rerankers; manual parallelism using multiple processes is required.

The OOM error mentioned above is likely not due to CUDA 0 running out of memory, but rather from CUDA 3. You can try reducing the batch size for inference.

**Comment by by1e11** [comment]
> Due to the large memory consumption of LLM-based rerankers when using DP multi-card inference, we do not provide multi-card parallelism for LLM-based rerankers; manual parallelism using multiple processes is required.
> 
> The OOM error mentioned above is likely not due to CUDA 0 running out of memory, but rather from CUDA 3. You can try reducing the batch size for inference.

Great man. You inspired me, I successfully load the model into 1 gpu using bf16. Thanks a lot
