### ISSUE TITLE
线上推理性能咨询

### ISSUE THREAD

**Issue by KekeWa** [FlagOpen/FlagEmbedding#11]
1. 支持转onnx提升推理速度吗？
2. 线上推理，由于无GPU，请问large系列用CPU推理（控制在100ms内）的最低要求是什么呢？比如4核8G

**Comment by staoxiao** [comment]
您好，
1. 理论上是可以的，但暂未尝试
2. 单次推理时间与句子数量和句子长度有关，您可以减少句子长度(参数max_length)来提高速度，但具体时间消耗还未有个一个清楚的统计。建议可以使用base或者small的模型，效果也不错，速度更快。

**Comment by KekeWa** [comment]
推理速度提升较快的一个方法是降维，那您这边是在网络层最后一层加一个比如：128维的全连接这种方法，还是直接线上线下均PCA降维呢?

**Comment by staoxiao** [comment]
您好，使用128维的全连接效果会更好，但需要finetune一下这个全连接层。
降维只能提高检索的速度(即提高相似度计算这一步)， 不会提高向量的推理速度，因为还是需要用模型先得到一个大向量。
如果是候选集很大，需要提高相似度计算并找到最相似文本这一步，可以考虑使用一些向量数据库，如Faiss，同时使用里面的一些近似索引技术，如OPQ。

**Comment by KekeWa** [comment]
<img width="1031" alt="image" src="https://github.com/FlagOpen/FlagEmbedding/assets/37018609/0b577988-ed5b-4c80-b683-f29a8a5db873">
您好，想咨询下微调过程的问题，使用自己训练集进行微调：报线程加速的错误？用的默认参数，不知从哪里开始排查bug

**Comment by staoxiao** [comment]
您好，trianer应该会在初始化的时候设置self.deepspeed。请问您的transformers版本是多少？

**Comment by KekeWa** [comment]
您好，transformers是4.30.2版本

**Comment by staoxiao** [comment]
您可以更新到最新版本的transformers，可以解决这个问题
```
pip install -U transformers
```

**Comment by staoxiao** [comment]
另外，建议在可用范围内使用最大的`--per_device_train_batch_size `, 更新了一些参数的建议：https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune

**Comment by KekeWa** [comment]
感谢您的耐心指导，有两个问题：1. 您提到更大得batchsize能发挥更大的性能，那微调的衡量指标有没有什么建议呢？比如检索排序指标NDCG之类，2. 微调完数据集（共2000条，一个query大概1-10个正样本，1-10个负样本），得出微调后参数如下：问题是，我计算两个不相干的句子相似度竟然也有0.88-0.9左右，有什么办法让不相似的控制在0.5以下吗？我尝试了多组数据卡阈值，卡到0.93，觉得不太合适（有违常理），也尝试了调整增大temperat到0.5，效果也近似，望指教。
![img_v2_aa20c31f-29e0-4c07-8e5b-bba0ddc01f9g](https://github.com/FlagOpen/FlagEmbedding/assets/37018609/50c9f9ea-0d05-45a6-a13c-f1cd1d1e5218)

**Comment by staoxiao** [comment]
1. 可以使用一些常用的检索指标，NDCG，Recall等
2. 关于相似度大小，需要看具体情况，由于训练中使用的是排序学习，绝对大小不具备太大的参考意义，阈值卡到0.93也并不一定有违常理，主要看具体数据。一方面建议使用更多负样本或者更大batch size，另一方面，如果想要这让相似度的绝对大小有关，可以考虑替换损失函数，使用二分类的损失函数进行训练。

**Comment by wanzhixiao** [comment]
> 1. 持转onnx提升推理速度吗？

请问是如何转onnx的，我看该模型在huggingface模型上套了一层，from FlagEmbedding import FlagModel
使用的FlagModel类构建embedding模型；
可以贴下代码吗

**Comment by chuangzhidan** [comment]
> > 1. 持转onnx提升推理速度吗？
> 
> 请问是如何转onnx的，我看该模型在huggingface模型上套了一层，from FlagEmbedding import FlagModel 使用的FlagModel类构建embedding模型； 可以贴下代码吗

同问
