### ISSUE TITLE
您好，https://huggingface.co/BAAI 近期无法访问，模型这块能否提供国内的下载地址，谢谢！

### ISSUE THREAD

**Issue by alei76** [FlagOpen/FlagEmbedding#110]
您好，https://huggingface.co/BAAI 近期无法访问，模型这块能否提供国内的下载地址，谢谢！

**Comment by staoxiao** [comment]
抱歉，暂时还没在其他网站上存储模型。我们近期会将其传上https://model.baai.ac.cn/models，到时即可下载。

**Comment by alei76** [comment]
谢谢

**Comment by staoxiao** [comment]
模型在BAAI data hub网站上发布了： https://model.baai.ac.cn/models， 搜索bge可以找到
