### ISSUE TITLE
使用/FlagEmbedding/baai_general_embedding/finetune/eval_msmarco.py。报错

### ISSUE THREAD

**Issue by yzx220** [FlagOpen/FlagEmbedding#1100]
使用文档中给出格式的数据进行测试，报这个错误要怎么解决
![12222](https://github.com/user-attachments/assets/73b32ed2-3498-4beb-bbcf-c7cba2dc8905)

**Comment by ZiyiXia** [comment]
这个报错应该是roc_auc_score()里参数y_true中的值只有1种（只有0没有1，或者只有1没有0），如果你是用自己的数据集做的测试的话可能是数据集有偏差

**Comment by yzx220** [comment]
那请问要如何避免这个错误的出现，或者有一些可参考的数据集吗





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Joey Xia ***@***.***&gt;
发送时间: 2024年9月12日 18:35
收件人: FlagOpen/FlagEmbedding ***@***.***&gt;
抄送: yzx ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [FlagOpen/FlagEmbedding] 使用/FlagEmbedding/baai_general_embedding/finetune/eval_msmarco.py。报错 (Issue #1100)

**Comment by ZiyiXia** [comment]
如果是只有0没有1，应该是所有queries检索出的答案都不在ground truth里，有可能是模型没有你的数据集所覆盖的知识所以embedding很不准确
如果是只有1没有0，可能是ground truth里每个query对应的positive passages太多了，可以试着把k调得大一些
代码里默认的数据集MS MARCO是没问题的，但太大耗时太长的话可以用这个[迷你数据集](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune/toy_evaluation_data)试一下，这里k应该要大于1小于等于5

**Comment by yzx220** [comment]
> 如果是只有0没有1，应该是所有查询检索出的答案都不在groundtruth里，有可能是模型没有你的数据集所覆盖的知识所以嵌入很不准确如果 是只有1没有0，可能是groundtruth里每个查询对应的正向段落太多了，可以试着把k调得大一些 代码里默认的数据集MS MARCO是没问题的，但精致加工太长的话可以用这个[迷你数据集](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune/toy_evaluation_data)试一下，这里k应该大于1小于等于5
好的谢谢回复
