### ISSUE TITLE
BGE-M3模型的使用协议是什么，可否商用？

### ISSUE THREAD

**Issue by charliedream1** [FlagOpen/FlagEmbedding#1101]

**Comment by ZiyiXia** [comment]
MIT License，可以商用

**Comment by charliedream1** [comment]
谢谢



---原始邮件---
发件人: "Joey ***@***.***&gt;
发送时间: 2024年9月12日(周四) 晚上6:42
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [FlagOpen/FlagEmbedding] BGE-M3模型的使用协议是什么，可否商用？ (Issue #1101)




 
MIT License，可以商用
