### ISSUE TITLE
langchain的正确导入方法

### ISSUE THREAD

**Issue by YAETHeryk** [FlagOpen/FlagEmbedding#1105]
搜索了一些issue反而让我有些疑惑。如果我要用langchain导入bge-small-zh-v1.5，HuggingFaceBgeEmbeddings和HuggingFaceEmbeddings这两个方法有什么差别？
然后，更具体一点，如果我的任务不是从一篇文章中找出与query对应的内容，而是比较两个短语的相似度例如：
['北京到上海的动车票','上海到北京的动车票']
那usage中这样的导入方法是合适的吗？
```
from langchain.embeddings import HuggingFaceBgeEmbeddings
model_name = "BAAI/bge-large-en-v1.5"
model_kwargs = {'device': 'cuda'}
encode_kwargs = {'normalize_embeddings': True} # set True to compute cosine similarity
model = HuggingFaceBgeEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
    query_instruction="为这个句子生成表示以用于检索相关文章："
)
model.query_instruction = "为这个句子生成表示以用于检索相关文章："
```

**Comment by ZiyiXia** [comment]
HuggingFaceEmbeddings是为HuggingFace里开源的embedding models设计的一个通用类，对于embed document和query没有区别；而HuggingFaceBgeEmbeddings是专门为调取BGE模型设计的，里面包含了BGE中英文模型的query instruction。
如果你只是比较短语相似度，那query instruction不是必须的，用哪个都行；如果需要做retrieval相关的任务，那建议用HuggingFaceBgeEmbeddings。
导入方法基本没问题，没必要加query_instruction这个参数，因为类里面已经设计了自动检测是zh还是en的模型，来给对应的embed_query时加上对应的instruction。只是比较短语相似度的话在初始化模型后可以参考下面的代码
```python
embeddings = model.embed_documents(['北京到上海的动车票','上海到北京的动车票'])
embeddings = np.asarray(embeddings)
print(embeddings @ embeddings.T)
```
细节和具体区别见Langchain的[源码](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/embeddings/huggingface.py)
