### ISSUE TITLE
reranker模型微调数据集问题

### ISSUE THREAD

**Issue by StephenZKCurry** [FlagOpen/FlagEmbedding#1110]
reranker模型微调数据集格式为：`{"query": "", "pos": [], "neg": []}`，其中pos可以是多个，在微调训练时能否反映出多个正向样本之间相关度的高低不同。例如posA的相关度最高，posB其次，posC最低，这三个样本都是属于正向样本。
我看到`TrainDatasetForCE.__getitem__()`中是随机从pos中抽取一个样本数据，是否意味着pos中多个样本与query之间相关度的高低对训练结果没有影响呢。

**Comment by staoxiao** [comment]
是的，目前训练是每次从列表里随机挑选一个pos

**Comment by StephenZKCurry** [comment]
> 是的，目前训练是每次从列表里随机挑选一个pos

谢谢，明白了
