### ISSUE TITLE
MTEB评测结果问题

### ISSUE THREAD

**Issue by micrazy** [FlagOpen/FlagEmbedding#1111]
作者您好，我在mteb官方提供的评测脚本上测试bge-m3在EN retriever任务MSMARCO数据集的指标，结果出奇的好：ndcg@10：67.044，远超mteb榜单上其他模型，甚至超过了一些7B的模型，我看bge-m3的微调数据集里有MSMARCO的数据，请问是否是因为存在数据泄露？

**Comment by staoxiao** [comment]
@micrazy ， 你看的应该是另一个集合上的指标，那个集合比容易，MTEB上MSMARCO放的是dev集合的指标
