### ISSUE TITLE
微调数据内容规模问题以及指令问题

### ISSUE THREAD

**Issue by EliverQ** [FlagOpen/FlagEmbedding#113]
您好！非常优秀的工作！我还有几个问题不太清楚，想请教一下:

1. 我看到你们放了微调数据的链接，似乎并没有直接放实际微调时训练的数据，所以你们微调数据的总量是2亿吗？如果按微调的默认epoch是5，batch_size是19k的话，总步数就是5w步对吗？
2. 数据构成问题： 你们在这里表明了数据的构成，例如 wikipedia使用的文本对是(title + section title, passage)，但是链接指向的huggingface数据集的wikipedia好像并没有section title？别的数据集也有类似的问题，所以想请问一下这部分数据是怎么构造的。
![image](https://github.com/FlagOpen/FlagEmbedding/assets/37859378/b0c3c667-c80d-4871-8fd4-160f0c763a84)
![image](https://github.com/FlagOpen/FlagEmbedding/assets/37859378/bceb84f9-0db2-4511-8e13-ed9b7f207a37)
3. 请问微调使用的指令是否是所有不同任务数据都使用同一个指令："Represent this sentence for searching relevant passages" ，如果是的话这怎样体现你们论文中的`Task specific instruction`呢？如果不是，请问各个任务对应的指令都是什么呢？

感谢！

**Comment by staoxiao** [comment]
1. 公开数据为v1.5数据经过安全过滤的前2亿条，我们会在20k steps左右停止训练。
2. 使用与链接指向相同的数据源，但我们修改了它的数据处理脚本。
3. 检索任务使用“Represent this sentence for searching relevant passages: "，相似度任务使用空字符串作为指令。
