### ISSUE TITLE
使用FlagEmbedding/baai_general_embedding/finetune/eval_msmarco.py

### ISSUE THREAD

**Issue by yzx220** [FlagOpen/FlagEmbedding#1131]
使用FlagEmbedding/baai_general_embedding/finetune/eval_msmarco.py
按照文件格式构建了自己的语料库和查询但是
{'MRR@1': 0.0, 'MRR@10': 0.0, 'MRR@100': 0.0, 'Recall@1': 0.0, 'Recall@10': 0.0, 'Recall@100': 0.0}
另外部分微调的数据为
{"query": "补骨脂 对人体的哪些脏腑有作用，具体作用是什么？", "pos": ["入脾命门心包三经。为壮火益土之品。（补相火以通君火）"], "neg": ["主温中。心腹痛。呕吐。去口臭气。（别录） 下气。止霍乱。一切冷气。消  酒  毒。  吐酸。", "入肝肾二经。为冲和之品。（兼补剂 能引肺金之气入肾）", "回春曰。河水与井水合用。亦名阴阳水。  以上宣剂水部", "主心痛。小肠气痛。以一枚煨存性。研末。新酒调服。（寇氏）治 疝气痛。  妇  人血", "〔长流水〕一名东流水。主手足四末之病。通利二便。（虞抟）〔逆流水〕主中  风  猝  之  肾虚", "主伤寒头痛寒热。瘴气恶毒。烦躁满闷。两脚疼冷。（别录）疟疾。骨蒸。犬  咬。  中  盗汗", "主诸风头眩肿痛。目欲脱。泪出。皮肤死肌。恶风湿痹。利血气。久服轻身耐  老延  权）", "经疏曰。病涉虚弱者。忌。", "时珍曰。钩藤久煎则无力。纯用钩。取其力锐也。", "味甘。性温。无毒。出北地。寒号虫粪。降也。阴中阴也。恶人参。损人。"]}
{"query": "使用补骨脂 这味中药时有哪些禁忌？", "pos": ["经疏曰。凡病阴虚火动。阳道妄举。梦遗尿血。小便短涩。目赤口苦舌干。大  便燥"], "neg": ["入胃经。为大解热毒之品。（通行五脏）", "主诸风。宣通五脏。去腹内冷滞。心膈痰水。久积症瘕。 癖气块。膀胱宿脓  恶水  肠风邪", "入肺经。兼入心脾二经。为散火通窍之品。（能透骨髓）", "入胃大肠二经。为固下之品。（兼重剂 二经血分药）", "经疏曰。头目痛不因风邪而由血虚有火者。忌之。元素云。胃虚人不可服。恐  生痰", "入命门三焦二经。兼入脾肾膀胱三经。为回阳退阴之品。（兼补剂 专补命门  相火", "味甘咸。性平。有毒。蜂得火气之甚而生。故房亦有毒。取悬树受风露者良。", "经疏曰。本非肺经药。亦有咳逆用之者。通指寒邪郁肺致咳之症。若肺热咳逆。  及", "主风热死肌。痈伤口干舌焦。痈肿不消。喉舌肿不通。水浆不下。（本经）大  惊  入腹", "主五内邪气。胃中热气。面赤。酒 。疮疡。（本经） 疗目赤热痛。胸心大  小  肠大  渴。（  热厥心  疝气。"]}
请问这是什么原因导致的

**Comment by staoxiao** [comment]
我感觉pos和query看不出来有什么明显的关系，确认一下pos是否是query的回答？
