### ISSUE TITLE
关于推理的时候是否需要对问题进行截取

### ISSUE THREAD

**Issue by qianzhang2018** [FlagOpen/FlagEmbedding#114]
您好，想请教一个问题
我发现训练的时候，是会对问题进行一个截断（64）
但是推理代码的时候好像都是统一默认512
我们推理的时候需要对问题进行截断么

**Comment by staoxiao** [comment]
不需要的。
通常问题都比较短，所以为提高效率，训练的时候设置了不太大的query_max_len， 但具体下游任务微调时应该根据实际数据的长度设置query_max_len和passage_max_len， 如果都很长的话，应该增大这些参数。
