### ISSUE TITLE
在训练的时候，能否不指定 neg， 即 只用in-batch 的形式 

### ISSUE THREAD

**Issue by yejiahaoye** [FlagOpen/FlagEmbedding#116]

**Comment by staoxiao** [comment]
您好，目前还不支持使用in-batch形式。
如果数据中没有neg，可以通过从其他pos中随机抽取neg，生成新的训练文件用于训练。
使用neg的好处在于，可以使用难负样本进行训练。难负样本可以通过https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune#hard-negatives 挖掘。

**Comment by stanpcf** [comment]
<img width="932" alt="image" src="https://github.com/FlagOpen/FlagEmbedding/assets/13925796/5395b992-6377-4090-9977-53102a466f31">
