### ISSUE TITLE
下游任务微调

### ISSUE THREAD

**Issue by jiangix-paper** [FlagOpen/FlagEmbedding#117]
您好，非常棒的工作。目前我们想基于bge-zh-large_v1.5对下游任务进行微调，请问：
（1）由于下游微调的数据只有几百条，请问只加这几百条数据微调几个epoch是否可以呢？或者需要将c-mtp中labeled的数据混合一部分进来。
（2）如果需要混合c-mtp中labeled的数据，我们可能需要根据以下数据源自行构建query, pos, neg三元组：
![image](https://github.com/FlagOpen/FlagEmbedding/assets/62198809/09a58699-ed1f-4d24-9f99-8c71a4efff54)
在构建三元组的时候，每个数据集有以下问题：
 I. mmarco数据集自行带了pos和neg，是否只有它自带的就行，还是说也需要利用脚本挖掘hard neg呢？
 II. Dureader数据集包含五类：Dureader_retrieval，Dureader_checklist，Dureader_yesno，Dureader_robust，Duread_QG。请问您那边是用的这里面哪几类构建的query，post，neg呢？
III. NLI_zh数据集中，包含label等于0或1的数据，是否只用到label等于1的数据作为pos呢？

**Comment by staoxiao** [comment]
您好，
1. 只用这几百条确实有些少，可以尝试加上一些其他的相关数据。另外，我们最近也在做一些关于微调的探究，构造更简单的微调方法，后面会陆续发布。
2. 不需要使用这么多数据集的，选择一些跟您任务相关的就好，比如是文档检索的话，加上T2ranking, duretriever等，相似度的话，加上NLI_zh。对于mmarco，自带的neg效果不好，需要利用脚本挖掘。对于dureader，使用了Dureader_retrieval，Dureader_checklist，Dureader_robust三类。对于NLI_zh，只有label为1的作为pos， label为0的作为hard neg。

**Comment by jiangix-paper** [comment]
好的，非常感谢
