### ISSUE TITLE
文档问题：链接错 huggingface.co/BAAI/bge-reranker-large 

### ISSUE THREAD

**Issue by qiulang** [FlagOpen/FlagEmbedding#1180]
你好有两个简单问题，

1. https://huggingface.co/BAAI/bge-reranker-large "We have updated the [new reranker](https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/llm_reranker), supporting larger lengths, more languages, and achieving better performance." 说的 new reranker 是指 v2-m3 吗？因为这里链接显示 404

<img width="836" alt="链接错" src="https://github.com/user-attachments/assets/ef10ab9d-9c51-45b9-af6d-a8a46789a754">

2. 我自己简单比较一下中文两个rerank  /bge-reranker-v2-m3/bge-reranker-large 在中文上差别，感觉好像不明显，想知道差别到底在哪？

**Comment by 545999961** [comment]
感谢提出的问题，这里的new reranker是值v2及以上系列的reranker，包括BAAI/bge-reranker-v2-m3, BAAI/bge-reranker-v2-gemma, BAAI/bge-reranker-v2-minicpm-layerwise, BAAI/bge-reranker-v2.5-gemma2-lightweight
bge-reranker-v2-m3用了更多的训练数据、支持更长的文本、支持更多的语言，效果会更好一点
