### ISSUE TITLE
Typo: Trutorials -> Tutorials

### ISSUE THREAD

**Issue by asdfo123** [FlagOpen/FlagEmbedding#1184]
Find a typo in the overview image in README.md in [imgpath](https://github.com/FlagOpen/FlagEmbedding/blob/master/imgs/projects.png)

Trutorails -> Tutorials

![image](https://github.com/user-attachments/assets/a7326aea-99f0-4936-9a86-09bb3e1f7056)

**Comment by 545999961** [comment]
Thanks!
