### ISSUE TITLE
qwen2.5 1.5B作为按照decoder_only训练reranker出错

### ISSUE THREAD

**Issue by Kang9779** [FlagOpen/FlagEmbedding#1185]
模型在执行时，outputs输出全是Nan导致loss计算失败：
`def encode(self, features):
        outputs = self.model(input_ids=features['input_ids'],
                             attention_mask=features['attention_mask'],
                             position_ids=features['position_ids'] if 'position_ids' in features.keys() else None,
                             output_hidden_states=True)
`
<img width="474" alt="image" src="https://github.com/user-attachments/assets/cbf66b95-ebb1-4843-bb88-b473cc87cc12">

**Comment by AndyVerne** [comment]
@Kang9779  你好，我也遇到了这个问题，请问你怎么解决这个问题呀？
