### ISSUE TITLE
使用FlagEmbedding推理M3一段时间后，显存占用持续增长

### ISSUE THREAD

**Issue by fly-haoli** [FlagOpen/FlagEmbedding#1191]
您好，非常感谢能够开源这一系列模型。
我这边使用FlagEmbedding(v1.3.2)加载bge-m3, 并使用FastAPI简单做了API服务，部分代码如下：
```python
from contextlib import asynccontextmanager
from typing import List, Optional, Union

import torch
import uvicorn
from fastapi import FastAPI, Response
from fastapi.middleware.cors import CORSMiddleware
from FlagEmbedding import BGEM3FlagModel, FlagReranker
from pydantic import BaseModel, Field, field_validator


@asynccontextmanager
async def lifespan(app: FastAPI):
    yield
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()


app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=['*'], allow_credentials=True, allow_methods=["*"], allow_headers=["*"],
)


def check_str_list(v) -> list:
    """ Union[str, list] 统一处理为 list """
    if not v:
        v = []
    elif not isinstance(v, list):
        v = [v]
    return v


class EncodeKwargs(BaseModel):
    return_dense: bool = True
    return_sparse: bool = False


class EmbeddingRequest(BaseModel):
    input: Union[List[str], str]
    model: Optional[str] = Field(default='bge-m3')
    encode_kwargs: Optional[EncodeKwargs] = {}

    _validator_list = field_validator('input', check_fields=False)(check_str_list)


class CompletionUsage(BaseModel):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class EmbeddingResponse(BaseModel):
    data: list
    model: str
    object: str
    usage: Optional[CompletionUsage] = Field(None)


@app.post("/api/v1/hybrid_embeddings", response_model=EmbeddingResponse)
async def get_hybrid_embeddings(request: EmbeddingRequest):
    encode_kwargs = request.encode_kwargs if isinstance(request.encode_kwargs, dict) else request.encode_kwargs.dict()
    encode_kwargs = {**encode_kwargs, 'return_dense': True, 'return_sparse': True}
    embeddings = embedding_model.encode(request.input, **encode_kwargs)
    dense_embeddings = [i.tolist() for i in embeddings['dense_vecs']]
    sparse_embeddings = [
        {k: v.tolist() for k, v in sorted(i.items(), key=lambda x: int(x[0]))}
        for i in embeddings['lexical_weights']
    ]
    dense_embeddings_length = len(dense_embeddings)
    sparse_embeddings_length = len(sparse_embeddings)
    hybrid_embeddings = []
    for i in range(max(dense_embeddings_length, sparse_embeddings_length)):
        dense_vecs = dense_embeddings[i] if dense_embeddings_length > i else []
        sparse_vecs = sparse_embeddings[i] if sparse_embeddings_length > i else []
        hybrid_embeddings.append({'dense': dense_vecs, 'sparse': sparse_vecs})
    response = {
        "data": [{"index": index, **embedding} for index, embedding in enumerate(hybrid_embeddings)],
        "model": request.model,
        "object": "list",
    }
    return response


if __name__ == "__main__":
    DEVICE = ['cuda:0', 'cuda:1'] if torch.cuda.is_available() else 'cpu'
    # load Embedding
    EMBEDDING_PATH = ''
    MAX_MODEL_LENGTH = 8192
    embedding_model = BGEM3FlagModel(
        EMBEDDING_PATH, device=DEVICE, use_fp16=True, query_max_length=MAX_MODEL_LENGTH,
        passage_max_length=MAX_MODEL_LENGTH, batch_size=64
    )
    uvicorn.run(app, host='0.0.0.0', port=8012)
```

然后我另写了一段代码，调用上述API服务，部分代码如下：
```python
import json
from datetime import datetime

import requests
from tqdm import tqdm


def hybrid_embed(data):
    url = 'http://IP:8012/api/v1/hybrid_embeddings'
    payload = {"input": data, "model": 'bge-m3'}
    res = requests.post(url, json=payload).json()
    batched_embeddings = [{'dense': r.get('dense'), 'sparse': r.get('sparse')} for r in res['data']]
    return batched_embeddings


def embedding_request():
    # 1.读取数据
    with open('data.txt', 'r', encoding='utf-8') as f:
        data_list = [json.loads(i) for i in f.readlines() if i.strip()]

    # 3.embedding
    start = 0
    step = 50
    print(f'chunk_total:{len(data_list)}')
    pbar = tqdm(total=len(data_list[start:]), initial=start)
    for idx in range(start, len(data_list), step):
        # sparse and dense
        vecs = hybrid_embed([i['text'] for i in data_list[idx:idx + step]])
        pbar.set_description(f'idx: {idx}')
        pbar.set_postfix(mongo_id=data_list[idx]['id'], datetime=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        pbar.update(step)
    print('------- 已完成 -------')


if __name__ == '__main__':
    embedding_request()
```

== 测试结果 ==
总共18451条数据（文本最大长度为22479），每轮请求发送50条数据，发现显存占用不停上涨且没有释放，见下方截图。
试验过FlagEmbedding加载m3时调下 batch_size，效果也不理想
（第1张是API服务刚启动时显存占用情况，第2张是开始推理时的显存占用，后续图片能看到显存占用持续上涨）
![image](https://github.com/user-attachments/assets/57a17954-014c-4cc5-8983-5c5e9933012d)

![04d1728f05c517c4736ae9c4973dd46](https://github.com/user-attachments/assets/c7769210-29ad-453e-a97e-0876222fc51a)

![2bc3d02ee98bf4c977a901230ff397d](https://github.com/user-attachments/assets/9e05347b-85d0-41ed-95fb-0d83a23e08cb)

![3330d7c942d2fece6e5742301e808e2](https://github.com/user-attachments/assets/4c79b171-04c5-4977-8c2a-570ddd1012ae)

![6589bcb87983fda0cdeb75e13773626](https://github.com/user-attachments/assets/cddf4306-33fe-4f62-b28b-0aa0ee202fff)

![b69bd2b3bbb4af341ea03e39ed58b2c](https://github.com/user-attachments/assets/e9a55b0e-78db-4c18-8166-7d28884292eb)

![4c4c9d781e8053ab348957fd58eb9af](https://github.com/user-attachments/assets/b874aaf1-bf96-418e-8015-c0be870df33f)

**Comment by fly-haoli** [comment]
> @fly-haoli 您好，首先更正下初始化时的一个参数名的错误 (device -> devices)，另外新版本支持在初始化的时候把推理参数传进去：
> 
> ```python
> if __name__ == "__main__":
>     DEVICE = ['cuda:0', 'cuda:1'] if torch.cuda.is_available() else 'cpu'
>     # load Embedding
>     EMBEDDING_PATH = ''
>     MAX_MODEL_LENGTH = 8192
>     embedding_model = BGEM3FlagModel(
>         EMBEDDING_PATH, devices=DEVICE, use_fp16=True, query_max_length=MAX_MODEL_LENGTH,
>         passage_max_length=MAX_MODEL_LENGTH, batch_size=64,
>         return_dense=True, return_sparse=True
>     )
>     uvicorn.run(app, host='0.0.0.0', port=8012)
> ```
> 
> 目前我们这边猜测是如下原因导致显存不断上升：由于最大长度开到 8192，而每次请求的50条数据的长短差距可能很大，当某次请求中有很长的数据时，显存利用率会拉到很高，并且后续这部分被利用的显存直到整个调用结束才会释放，所以显存利用率可能会不断拉高，这是正常现象。由于我们做了动态 batch size 调整策略，所以不用担心会报 OOM 错误。 如果您想让整个调用的过程中显存利用率相对稳定，建议您对需要 encode 的数据预先处理下，让第一次请求的数据长度是所有请求中最长的，那么后续的显存利用率就会保持一个稳定的状态，而不是像目前一样持续上升。

谢谢，我先请求了一次数据长度之后，然后再批量请求，显存的确会保持在一个稳定状态。

但是，这种情况下显存一直占用比较大，没有释放，直到重启服务才行。
另外，我无意间发现只用单卡加载模型，即DEVICE = 'cuda:0'，在批量请求时，显存会不断释放，不会一直占用比较高的水平。

**Comment by 545999961** [comment]
> > @fly-haoli 您好，首先更正下初始化时的一个参数名的错误 (device -> devices)，另外新版本支持在初始化的时候把推理参数传进去：
> > ```python
> > if __name__ == "__main__":
> >     DEVICE = ['cuda:0', 'cuda:1'] if torch.cuda.is_available() else 'cpu'
> >     # load Embedding
> >     EMBEDDING_PATH = ''
> >     MAX_MODEL_LENGTH = 8192
> >     embedding_model = BGEM3FlagModel(
> >         EMBEDDING_PATH, devices=DEVICE, use_fp16=True, query_max_length=MAX_MODEL_LENGTH,
> >         passage_max_length=MAX_MODEL_LENGTH, batch_size=64,
> >         return_dense=True, return_sparse=True
> >     )
> >     uvicorn.run(app, host='0.0.0.0', port=8012)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 目前我们这边猜测是如下原因导致显存不断上升：由于最大长度开到 8192，而每次请求的50条数据的长短差距可能很大，当某次请求中有很长的数据时，显存利用率会拉到很高，并且后续这部分被利用的显存直到整个调用结束才会释放，所以显存利用率可能会不断拉高，这是正常现象。由于我们做了动态 batch size 调整策略，所以不用担心会报 OOM 错误。 如果您想让整个调用的过程中显存利用率相对稳定，建议您对需要 encode 的数据预先处理下，让第一次请求的数据长度是所有请求中最长的，那么后续的显存利用率就会保持一个稳定的状态，而不是像目前一样持续上升。
> 
> 谢谢，我先请求了一次数据长度之后，然后再批量请求，显存的确会保持在一个稳定状态。
> 
> 但是，这种情况下显存一直占用比较大，没有释放，直到重启服务才行。 另外，我无意间发现只用单卡加载模型，即DEVICE = 'cuda:0'，并且在API代码中增加每次请求调用后清理缓存，如：
> 
> ```python
> @app.middleware("http")
> async def add_process_time_header(request: Request, call_next):
>     response = await call_next(request)
>     # 每次请求后清理 GPU 内存（只在单卡情况下有效）
>     if torch.cuda.is_available():
>         torch.cuda.empty_cache()
>         torch.cuda.ipc_collect()
>     return response
> ```
> 
> 然后，在批量请求时，显存会不断释放，不会一直占用比较高的水平。

每次编码后可以在代码中添加清除操作，但在面对较长的输入时，那一刻的显存仍然会达到很高的值。如果想避免显存峰值，减少 batch size 是更有效的策略。
