### ISSUE TITLE
Error in AbsDataset.py - KeyError: ('neg_scores', <class 'list'>)

### ISSUE THREAD

**Issue by jhyeom1545** [FlagOpen/FlagEmbedding#1203]
When I train using paramter knowledge_distillation True, 
I got some issue below
KeyError: ('neg_scores', <class 'list'>)

FlagEmbedding/FlagEmbedding/abc/finetune/embedder/AbsDataset.py
I think AbsDataset.py need some change

<img width="895" alt="image" src="https://github.com/user-attachments/assets/9c766a16-c106-4987-8c9c-3ebfd65faf77">

I think this code need update like this:
<img width="923" alt="image" src="https://github.com/user-attachments/assets/01c05fcd-2962-41e9-8dfe-986ceb83e12d">

**Comment by 545999961** [comment]
Thank you for your correction.
