### ISSUE TITLE
请问微调数据集的问题

### ISSUE THREAD

**Issue by czhcc** [FlagOpen/FlagEmbedding#1209]
微调数据集中prompt，category和type属性的作用是什么？

**Comment by hanhainebula** [comment]
你好，@czhcc！prompt 字段是用于指定在 query 前添加的指令，category 字段是在使用 embedder.decoder_only.icl 训练时才会生效，type 字段是在使用 `same_dataset_within_batch` 选项时才会生效 (也就是说要求同一个 batch 的数据均来自一个数据集文件)。具体来说，它们的作用分别如下：
- prompt: 指定时会在对应的 query 前加上该特定的 prompt，参考[这里](https://github.com/FlagOpen/FlagEmbedding/blob/3f071736d41e76f0620b1063dc34e4f04e34b5be/FlagEmbedding/abc/finetune/embedder/AbsDataset.py#L111) 和[这里](https://github.com/FlagOpen/FlagEmbedding/blob/3f071736d41e76f0620b1063dc34e4f04e34b5be/FlagEmbedding/abc/finetune/embedder/AbsDataset.py#L452)
- category: 在聚类任务的数据集中会增加这个字段用于 ICL 模型的训练以作为 example，参考[这里](https://github.com/FlagOpen/FlagEmbedding/blob/3f071736d41e76f0620b1063dc34e4f04e34b5be/FlagEmbedding/finetune/embedder/decoder_only/icl/dataset.py#L145)
- type: 目前是提供了 `symmetric_sts` (STS 任务的数据), `symmetric_class` (Classification 任务的数据), `symmetric_clustering` (Clustering 任务的数据), `only_1neg` (只使用1个难负样本的数据) 这些选项，带 `symmetric_` 前缀的数据的 batch_size 会缩减为默认的1/2以扩大对应数据训练的 steps (参考[这里](https://github.com/FlagOpen/FlagEmbedding/blob/3f071736d41e76f0620b1063dc34e4f04e34b5be/FlagEmbedding/abc/finetune/embedder/AbsDataset.py#L374))，`only_1neg`会使得该数据所在的 batch 的 group_size 为 2 (参考[这里](https://github.com/FlagOpen/FlagEmbedding/blob/3f071736d41e76f0620b1063dc34e4f04e34b5be/FlagEmbedding/abc/finetune/embedder/AbsDataset.py#L426))，`symmetric_class` 会使得该数据所在的 batch 的 group_size 为所有的种类数和指定的 group_size 的最小值 (参考[这里](https://github.com/FlagOpen/FlagEmbedding/blob/3f071736d41e76f0620b1063dc34e4f04e34b5be/FlagEmbedding/abc/finetune/embedder/AbsDataset.py#L428))，`symmetric_clustering` 和 `symmetric_sts` 两种类型会使得该 batch 的训练数据的 passage 侧也会加上 prompt
