### ISSUE TITLE
FlagEmbedding/abc/inference/AbsReranker.py第99行存在bug

### ISSUE THREAD

**Issue by Swgj** [FlagOpen/FlagEmbedding#1215]
<img width="825" alt="image" src="https://github.com/user-attachments/assets/a1c3dfb9-9cd6-4dd1-bace-f6c48de67a39">

PyTorch 不支持torch.mps.device_count()方法，这里应该和cpu一样修改成
return ["mps"]
因为M芯片好像只支持单设备

<img width="657" alt="image" src="https://github.com/user-attachments/assets/31a2353e-57ea-48ed-8020-a276d674fbda">

**Comment by 545999961** [comment]
Thank you for fixing the bug!
