### ISSUE TITLE
请给个Embedder和Reranker微调后模型合并的例子

### ISSUE THREAD

**Issue by czhcc** [FlagOpen/FlagEmbedding#1217]
按照
https://github.com/FlagOpen/FlagEmbedding/tree/master/examples
的例子运行了Embedder和Reranker微调，但一定不能合并，能否给个合并的方式？

**Comment by hanhainebula** [comment]
你好，@czhcc！embedder 和 reranker 是两种不同的模型，embedder 一般是双塔架构，常用于检索，reranker 一般是单塔架构，常用于排序，二者常搭配使用即”检索+排序“，一般不能合并。

**Comment by czhcc** [comment]
好的，感谢
