### ISSUE TITLE
请问bge的Sequence Length最大是512吗？

### ISSUE THREAD

**Issue by adol001** [FlagOpen/FlagEmbedding#122]
当我调大encode的max len参数后，会报错，异常与这个问题基本相似 https://github.com/huggingface/transformers/issues/18506

> 发生异常: RuntimeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
> The size of tensor a (2222) must match the size of tensor b (512) at non-singleton dimension 1
>   File "/home/adol/anaconda3/envs/flagEmbed/lib/python3.10/site-packages/transformers-4.31.0-py3.10.egg/transformers/models/bert/modeling_bert.py", line 238, in forward
>     embeddings += position_embeddings
>   File "/home/adol/anaconda3/envs/flagEmbed/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/adol/anaconda3/envs/flagEmbed/lib/python3.10/site-packages/transformers-4.31.0-py3.10.egg/transformers/models/bert/modeling_bert.py", line 1015, in forward
>     embedding_output = self.embeddings(
>   File "/home/adol/anaconda3/envs/flagEmbed/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/adol/anaconda3/envs/flagEmbed/lib/python3.10/site-packages/FlagEmbedding/flag_models.py", line 84, in encode
>     last_hidden_state = self.model(**inputs, return_dict=True).last_hidden_state
>   File "/home/adol/anaconda3/envs/flagEmbed/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/mnt/ok/works30/w3/cool35.py", line 46, in <module>
>     line_embeddings = model.encode(lines, max_length=3000)
>   File "/home/adol/anaconda3/envs/flagEmbed/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/adol/anaconda3/envs/flagEmbed/lib/python3.10/runpy.py", line 196, in _run_module_as_main (Current frame)
>     return _run_code(code, main_globals, None,
> RuntimeError: The size of tensor a (2222) must match the size of tensor b (512) at non-singleton dimension 1

没有办法突破512的限制吗？

**Comment by adol001** [comment]
> 是的，当前bge的最大长度为512。很长的文本建议分chunk，处理成多个向量

@staoxiao 通常bge建议的chunk长度是多少？我发现有些信息如果放在末尾，虽然没被truncate，但是不容易被向量数据库搜索召回

**Comment by staoxiao** [comment]
建议128，bge的大部分训练数据长度都在128以内
