### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by Vincent2Liu** [FlagOpen/FlagEmbedding#123]
https://github.com/FlagOpen/FlagEmbedding/blob/f585fcfd6669533b9cd0a516c5699a4f5989f340/FlagEmbedding/baai_general_embedding/finetune/hn_mine.py#L72C19-L72C22

这一行代码是不是有问题

**Comment by staoxiao** [comment]
感谢指正！确实有问题，修改了一下。
