### ISSUE TITLE
No sentence-transformers model found with name /home/FlagEmbedding/QA_finetune_bge-large-zh-v1.5. Creating a new one with mean pooling

### ISSUE THREAD

**Issue by sanilyli** [FlagOpen/FlagEmbedding#1238]
我在使用微调后的模型，遇到了这个告警，查看之前的issue有看到一些建议，但是那个页面已经过期了，请问现在有最新的处理方法吗？非常感谢。No sentence-transformers model found with name /home/FlagEmbedding/QA_finetune_bge-large-zh-v1.5. Creating a new one with mean pooling

**Comment by sanilyli** [comment]
把部分原配置文件（modules，config_sentence_transformers，1_Pooling）复制过去暂时没有告警了，但不能确定是不是有效方法。

**Comment by hanhainebula** [comment]
你好，@sanilyli。因为目前的代码在保存模型文件时没有针对 sentence-transformers 进行相应 config 文件的保存，你可以参考[这里的代码](https://github.com/FlagOpen/FlagEmbedding/blob/master/research/baai_general_embedding/finetune/trainer.py#L5) 进行手动保存。

**Comment by chansonzhang** [comment]
> 把部分原配置文件（modules，config_sentence_transformers，1_Pooling）复制过去暂时没有告警了，但不能确定是不是有效方法。

多谢，我在微调 m3 后这些配置文件都不见了 ([issues#1326](https://github.com/FlagOpen/FlagEmbedding/issues/1326))，把他们从原始模型中拷贝过来就好了。
