### ISSUE TITLE
Evaluation Pipeline for BGE-EN-ICL

### ISSUE THREAD

**Issue by ShirleyTY** [FlagOpen/FlagEmbedding#1244]
Hello authors, thank you for your great work!  And I wonder when the Evaluation Pipeline for BGE-EN-ICL will be released?

**Comment by 545999961** [comment]
You can follow [eval mteb](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/evaluation#1-mteb) to evaluate bge-en-icl.
The examples can be found at [examples](https://github.com/FlagOpen/FlagEmbedding/tree/master/research/llm_dense_retriever/examples/bge-en-icl/MTEB)

**Comment by ShirleyTY** [comment]
> You can follow [eval mteb](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/evaluation#1-mteb) to evaluate bge-en-icl. The examples can be found at [examples](https://github.com/FlagOpen/FlagEmbedding/tree/master/research/llm_dense_retriever/examples/bge-en-icl/MTEB)

Thanks for your reply! 
I read the files in the examples folder, and I'm curious why the content of the query and response in the dictionary is the same? For example, {"query": "I wish I could have used this head set but the day I received it it wouldn't even turn on and I really wanted this product to work I'm very disappointed.", "response": "I wish I could have used this head set but the day I received it it wouldn't even turn on and I really wanted this product to work I'm very disappointed."}.

**Comment by 545999961** [comment]
> > You can follow [eval mteb](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/evaluation#1-mteb) to evaluate bge-en-icl. The examples can be found at [examples](https://github.com/FlagOpen/FlagEmbedding/tree/master/research/llm_dense_retriever/examples/bge-en-icl/MTEB)
> 
> Thanks for your reply! I read the files in the examples folder, and I'm curious why the content of the query and response in the dictionary is the same? For example, {"query": "I wish I could have used this head set but the day I received it it wouldn't even turn on and I really wanted this product to work I'm very disappointed.", "response": "I wish I could have used this head set but the day I received it it wouldn't even turn on and I really wanted this product to work I'm very disappointed."}.

We are very sorry that there was an error with the examples. We have corrected the examples, so you can use them again.
