### ISSUE TITLE
How to use finetune result?

### ISSUE THREAD

**Issue by dviettu134** [FlagOpen/FlagEmbedding#1247]
Hi, which model should I use for inference from the finetuned result?
This is the structure from finetuned result folder:

```
\---checkpoint-15478
    |   config.json
    |   latest
    |   model.safetensors
    |   rng_state_0.pth
    |   rng_state_1.pth
    |   sentencepiece.bpe.model
    |   special_tokens_map.json
    |   tokenizer.json
    |   tokenizer_config.json
    |   trainer_state.json
    |   training_args.bin
    |   zero_to_fp32.py
    |
    \---global_step15478
            mp_rank_00_model_states.pt
            zero_pp_rank_0_mp_rank_00_optim_states.pt
            zero_pp_rank_1_mp_rank_00_optim_states.pt
```

**Comment by 545999961** [comment]
If the model has been fine-tuned with LoRA, it needs to be merged and then used. Refer to: [merge](https://github.com/FlagOpen/FlagEmbedding/blob/master/research/llm_reranker/merge/merge_base_model.py)

If it has been directly fine-tuned, you can replace the previous model name or path with this path and use it directly.

**Comment by dviettu134** [comment]
@545999961 thank you for your reply. I followed the instruction in https://github.com/FlagOpen/FlagEmbedding/blob/master/examples/finetune/embedder/README.md, so I guess that is directly fine-tuned. I could run inference like this:
```
model_finetuned = BGEM3FlagModel(
        {path_to_folder_checkpoint-15478},
        devices="cuda:0",   # if you don't have a GPU, you can use "cpu"
        pooling_method='cls',
        cache_dir=os.getenv('HF_HUB_CACHE', None),
    )
```

I'm not sure this is the correct way to run inference or not. 
And there are multi model files (*.pt, *.pth) in the `checkpoint-15478` foder, what is the meaning of these models?

**Comment by 545999961** [comment]
> @545999961 thank you for your reply. I followed the instruction in https://github.com/FlagOpen/FlagEmbedding/blob/master/examples/finetune/embedder/README.md, so I guess that is directly fine-tuned. I could run inference like this:
> 
> ```
> model_finetuned = BGEM3FlagModel(
>         {path_to_folder_checkpoint-15478},
>         devices="cuda:0",   # if you don't have a GPU, you can use "cpu"
>         pooling_method='cls',
>         cache_dir=os.getenv('HF_HUB_CACHE', None),
>     )
> ```
> 
> I'm not sure this is the correct way to run inference or not. And there are multi model files (*.pt, *.pth) in the `checkpoint-15478` foder, what is the meaning of these models?

These files store the weights of the model.
