### ISSUE TITLE
关于使用带难负数据的样本进行微调

### ISSUE THREAD

**Issue by Vincent2Liu** [FlagOpen/FlagEmbedding#126]
你好，想咨询一下几个关于微调的问题
1、微调时的训练数据中的query是指问句吗？还是说任意句子都可以？
2、pos和query之间的关系是一种语义上的相似关系吗,可不可以认为pos是对query的重写？
3、对于微调使用训练集的大小有什么指导性的建议吗，是根据预训练使用数据集的大小来定吗？

**Comment by staoxiao** [comment]
1. 不一定是问句，任意句子都可以
2. query和pos之间需要有相关性，改写后的query可以看为原query的pos。但微调数据应该跟下游任务相似，下游任务是做什么，微调数据就应该是这样的文本对。如果下游任务是查找重写的query，那么就可以使用重写query作为pos，即正样本。
3. 没有具体数量限制，高质量数据越多越好

**Comment by Vincent2Liu** [comment]
谢谢解答！
对于上面第二个问题：我使用bge-large-zh是用在langchain里面和向量数据库一起搭配使用的，然后使用langchain进行问答及text2sql等任务。我理解这里的bge-large-zh的下游任务主要应该是检索，检索出与query相关的文档送到LLM当中，不知道这样理解对不对？

**Comment by staoxiao** [comment]
对的，所以训练数据中的pos就是与query相关的文档

**Comment by Vincent2Liu** [comment]
好的，了解了，多谢
