### ISSUE TITLE
Add Activation Beacon as a standalone Huggingface model

### ISSUE THREAD

**Issue by maxjeblick** [FlagOpen/FlagEmbedding#1263]
Thanks a lot for your interesting work on Activation Beacon!

As a user, it would be really helpful to have the finetuned Activation Beacon models hosted on Huggingface (including custom code) such that they could be loaded as `model = AutoModelForCausalLM.from_pretrained(".../llama3.1-beacon", trust_remote_code=True)`

This would allow to integrate the models in any currently existing workflow that uses `AutoModelForCausalLM`.

**Comment by namespace-Pt** [comment]
Yes I do. Actually I'm working on improving the model to make it generate more fluent and long output. After that, I'll release Llama models as well as Qwen models.
