### ISSUE TITLE
关于开源的数据集问题

### ISSUE THREAD

**Issue by Xls1994** [FlagOpen/FlagEmbedding#127]
您好，想问一下，这个开源的中文训练数据集除了wudao还包括了一些其他的数据集，这些数据是都参与了我们BGE模型的微调吗，还是说只用了wudao的数据进行微调呢

**Comment by staoxiao** [comment]
您好，都使用了，可以参考 https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/baai_general_embedding

**Comment by Xls1994** [comment]
感谢您的回复！
