### ISSUE TITLE
ModuleNotFoundError: No module named 'FlagEmbedding.visual'

### ISSUE THREAD

**Issue by AmineM24** [FlagOpen/FlagEmbedding#1270]
I encountered a ModuleNotFoundError while using the FlagEmbedding library. After running pip install -U FlagEmbedding, i executed the following code :

import torch
from FlagEmbedding.visual.modeling import Visualized_BGE

and i got the following error : 

ModuleNotFoundError: No module named 'FlagEmbedding.visual'

**Comment by JUNJIE99** [comment]
Our repository has recently been restructured, and the paths for some projects have changed. Please refer to the latest example code. https://github.com/FlagOpen/FlagEmbedding/tree/master/research/visual_bge
