### ISSUE TITLE
MPT数据集相关问题

### ISSUE THREAD

**Issue by Wenze7** [FlagOpen/FlagEmbedding#130]
您好，想问下 数据中的pos和neg选取的规则是什么呢？ pos是标注好的吗，neg是随机取的还是未经强负例采样的可能的负例？在做hard neg采样的时候可以在全部的文本里面进行采样吗？

另外，我看数据并没有区分 title和para，有没有title和para分开的数据版本呢？

最后，有没有微信交流群呀？

**Comment by staoxiao** [comment]
您好，pos是标注好的，也有从文档中挖取的，比如说选取标题做query, 文章做pos。neg是随机取的。在做hard neg采样的时候可以在全部的文本里面进行采样。title和para是区分开开的，title做query, para做pos。
抱歉，目前还没有开通微信群。

**Comment by Wenze7** [comment]
谢谢您的回答，还想问一下，General purpose fine-tuning 对于这个训练，公开的MPT数据集式已经通过Text2VecChinese等工具过滤好的了吗，还是是公开的数据集没有经过过滤，其他人在用的时候还需要自己过滤？

**Comment by staoxiao** [comment]
已经过滤过了的
