### ISSUE TITLE
MTP数据集是否有随机shuffle？

### ISSUE THREAD

**Issue by memray** [FlagOpen/FlagEmbedding#133]
你好，我在使用MTP进行训练，发现到特定step的时候loss会剧烈变动（变好或者变坏，并持续一段时间）。请问开放下载的数据集([https://data.baai.ac.cn/details/BAAI-MTP](https://data.baai.ac.cn/details/BAAI-MTP))是否只是单纯拼接，训练前最好额外进行shuffle？此外想问release的BGE模型是否都是用这个数据集训练的？

谢谢！

**Comment by staoxiao** [comment]
您好，数据集没有做shuffle，训练的时候最好随机采样。是的

**Comment by hitwangshuai** [comment]
能分享下数据吗
