### ISSUE TITLE
Finetune阶段对比学习数据集构造问题求教

### ISSUE THREAD

**Issue by KevinNuNu** [FlagOpen/FlagEmbedding#137]
我现在在做一个领域数据文本相似度匹配任务
已经在领域数据上完成了pretrain过程
接下来准备进行finetune，但由于没有有监督的标注，想请问下该如何生成无监督对比学习的样本呢？
现在我相当于只有200w条query，负样本neg可以从非此条query中去随机抽取，但是pos样本该如何给定呢（pos hnm过程也不会生成）？
比如SimCSE通过自身dropout两次得到正样本对，bge是否有自己的方法构造正样本对呢？想请教一下这方面的经验
盼回复，感谢！

**Comment by staoxiao** [comment]
BGE本身不具备构造正样本对的功能，我只能提供一些潜在的方法：
1. 通过大模型LLM或者一些生成模型去生成正样本。
2. 如果您的数据内存在互相相似的文本，可以使用BGE进行检索，找到最相似的样本，然后使用bge-reranker模型进行判断，留下那些相似度比较高的文本作为样本对。 
3. 通过对query进行文字替换，删除，增加或者simcse两次dropout等方式生成正样本。

**Comment by KevinNuNu** [comment]
> BGE本身不具备构造正样本对的功能，我只能提供一些潜在的方法：
> 
> 1. 通过大模型LLM或者一些生成模型去生成正样本。
> 2. 如果您的数据内存在互相相似的文本，可以使用BGE进行检索，找到最相似的样本，然后使用bge-reranker模型进行判断，留下那些相似度比较高的文本作为样本对。
> 3. 通过对query进行文字替换，删除，增加或者simcse两次dropout等方式生成正样本。

非常感谢您的回复~

**Comment by pcx-pcx** [comment]
这么多数据，可以先聚个类了来，把相似文本先聚到一起，再从中构造正样本
