### ISSUE TITLE
进行pretrain时，显卡的使用率大部分时间是0%，只有极短的时间使用率是100%

### ISSUE THREAD

**Issue by xiaoyang-cn** [FlagOpen/FlagEmbedding#141]
进行pretrain时，显卡的使用率大部分时间是0%，只有极短的时间使用率是100%

运行行出现下面warning：
[W reducer.cpp:1300] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

**Comment by xiaoyang-cn** [comment]
显卡使用率如下：几乎只有一瞬间的利用率较高。大部分时间都是0%

<img width="917" alt="image" src="https://github.com/FlagOpen/FlagEmbedding/assets/53287191/da1dc2be-4a94-4e5c-8511-fa4ae80b8bf9">
<img width="930" alt="image" src="https://github.com/FlagOpen/FlagEmbedding/assets/53287191/21081325-fde2-4ed7-8e20-7d5917e1c20e">

**Comment by staoxiao** [comment]
增加参数以多线程处理数据：` --dataloader_num_workers 12`

**Comment by xiaoyang-cn** [comment]
感谢~    已解决！！
