### ISSUE TITLE
FlagModel 没办法使用cpu吗

### ISSUE THREAD

**Issue by ReverseSystem001** [FlagOpen/FlagEmbedding#15]
FlagModel will use all available GPUs when encoding, please set os.environ["CUDA_VISIBLE_DEVICES"] to choose GPU.

**Comment by staoxiao** [comment]
If you wan to use CPU, you can set `os.environ["CUDA_VISIBLE_DEVICES"]=""`.

**Comment by ReverseSystem001** [comment]
哦哦，谢谢
