### ISSUE TITLE
`bge-base-en-v1.5` displayed better retrieval results than `bge-large-en-v1.5`

### ISSUE THREAD

**Issue by winstxnhdw** [FlagOpen/FlagEmbedding#150]
Used the same instruction, query and dataset. 

Only difference is that I am using 1024 dimensions for `bge-large-en-v1.5` and 764 for the base model.

**Comment by staoxiao** [comment]
The embedding size of the base model is 768. You can select the model based on the performance on your data.
This problem may be due to incorrect usage or too little test data. In most cases, large is better than the base model.

**Comment by winstxnhdw** [comment]
Hmm.. I have about 6 MBs worth of data though. It could be my chunking strategy. Do you have any recommendations? I am currently using LlamaIndex’s sentence splitter.

**Comment by staoxiao** [comment]
Sorry, I don't have enough experience with text allocators to make useful suggestions.
