### ISSUE TITLE
hybrid search using both BGE and BM25

### ISSUE THREAD

**Issue by bugface** [FlagOpen/FlagEmbedding#17]
Dear Team,

Thank you for this great work.

Our team has been actively engaged in testing hybrid search strategies by integrating BM25 search with semantic search (we leverage search engines like Elasticsearch / opensearch / azure cognitive search). In our recent experimentation, we have consistently observed that the hybrid search approach outperforms the individual model performance for both the instructor (https://instructor-embedding.github.io/) and sentence-transformer (multi-qa-mpnet-base-dot-v1) models. This encouraging outcome underscores the efficacy of the hybrid strategy.

However, an interesting pattern emerged when we incorporated BGE into our hybrid search framework. In this specific scenario, the hybrid search results fell between the performance of the BM25-only search and the BGE-only search strategies and worse than hybrid search results from BM25 + instructor.

Given these intriguing findings, we are reaching out to inquire if any of you have hands-on experience or insights related to hybrid search strategies involving BGE. Your valuable input could significantly contribute to our ongoing research and experimentation.

Thank you for your time and assistance.

**Comment by staoxiao** [comment]
Hi, thanks for your interest! 
Our team did some research on hybrid search before, also finding hybrid method is better than a single retriever.  But for BGE model, we have not done some experiments about the hybrid method. 
Maybe you can provide some detailed information, so that we can analyze your results more deeply.  You also can email [me](mailto:stxiao@baai.ac.cn).

**Comment by habaneraa** [comment]
I am also interested in the performance of hybrid search. How do you combine BGE with sparse retrieval (like BM25)?

**Comment by habaneraa** [comment]
[This paper](https://arxiv.org/abs/2210.11934) has studied the performance of hybrid search on the popular retrieval datasets. Their results show that the hybrid search algorithm outperforms both BM25 / semantic similarity on all datasets, when using appropriate fusing method. Here is their main result (LEX for BM25 only; SEM for embedding vector similarity only; TM2C2 & RRF for fusing methods):

<img width="1023" alt="image" src="https://github.com/FlagOpen/FlagEmbedding/assets/95517280/14e5bac4-94a7-4445-a1d6-f4887bbd371b">

However, they only use [this model](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2) for the embedding vector. In particular, I am curious about whether these results are representative across all kinds of embedding models.

**Comment by bugface** [comment]
@staoxiao please found some details below, We have a few foundings here:

1. we only have the results on scifact but will update if I have more
2. we test both bge and gte.  The gte results are somehow consistent with the paper reported. But bge seems significantly lower than we expect.
3.  you can see for instructor embedding, hybrid is better than just use instructor or BM25, but for bge and gte, it is reversed.
4. We use elasticsearch, it could be because of the elasticsearch vector search implementation or embedding normalization.
- TODO: I will test other datasets as well as on azure cognitive search. But really hope your team can try something on your end as well.   


## dataset/evaluation
- we use beir package

## search engine
- elasticsearch (as example here)
- we can also use other search tools (azure cognitive or weaviate)

## elasticsearch mapping
```
{
    "mappings": {
        "properties": {
            self.title_key: {"type": "text", "analyzer": "english"},
            self.text_key: {"type": "text", "analyzer": "english"},
            "ins_emb": {
                "type": "dense_vector",
                "dims": 768,
                "index": True,
                "similarity": "cosine",
                "index_options": {"type": "hnsw", "m": 16, "ef_construction": 512},
            },
            "bge_emb": {
                "type": "dense_vector",
                "dims": 768,
                "index": True,
                "similarity": "cosine",
                "index_options": {"type": "hnsw", "m": 16, "ef_construction": 512},
            },
        }
    }
}
```

## elasticsearch create index
```
# generate embeddings
# context is the paragraph for retrieval

INSTRUCT_CONTEXT = "Represent the paragraph for retrieval: "
model1 = INSTRUCTOR("hkunlp/instructor-large")
model_inputs = [[INSTRUCT_CONTEXT, context, 0]]
instruct_embedding = model1.encode(model_inputs, device=DEVICE).tolist()[0]


model2 = SentenceTransformer("BAAI/bge-base-en")
bge_embedding = model2.encode(context, device=DEVICE).tolist()

# the index data for each sample:
doc = {
    "_id": str(_id),
    "_op_type": "index",
    "refresh": "wait_for",
    "text": context, 
    "title": context_title,
    "ins_emb": inse,
    "bpe_emb": bpe_emb,
}
```

## elasticsearch query

- given same query for retrieval
- bm25 + instructor
- top_k is 10 and 20
```
# bm25 + instructor

INSTRUCT_QUERY = "Represent the question for retrieving supporting paragraphs: "
ins_emb = model1.encode([[INSTRUCT_QUERY, query, 0]], device=DEVICE).tolist()[0]

# query schema
req_body = {
    "bool": {
        "should": [
            {"match": {self.text_key: query}},
            {"match": {self.title_key: query}},
        ]
    },
    "knn": {
        "field": "ins_emb",
        "query_vector": ins_emb,
        "k": 20,
        "num_candidates": 100,
    },
}

es.search(
    index=index_name, body=req_body, size=top_k, request_timeout=360
)
```
- bm25 + bge
```
# bm25 + bge
PROMPT = "Represent this sentence for searching relevant passages:"
bge_emb = model2.encode(" ".join([self.PROMPT, text4emb]), normalize_embeddings=True).tolist() # why we need `normalize_embeddings` here

req_body = {
    "query": {
        "bool": {
            "should": [
                {"match": {self.text_key: text}},
                {"match": {self.title_key: text}},
            ]
        },
    },
    "knn": {
        "field": "bge_emb",
        "query_vector": bge_emb,
        "k": 20,
        "num_candidates": 100,
    },
}

es.search(
    index=index_name, body=req_body, size=top_k, request_timeout=360
)
```

## results:

### scifacts
| experiment | NDCG@10 | NDCG@20 | recall@10 | recall@20 |
| ------------- |:-------------:|:-------------:|:-------------:|:-------------:|
| BM25 | 0.67| 0.68 | 0.81 | 0.85 |
| instructor | 0.61 | 0.63 | 0.78 | 0.80 |
| BM25 + instructor | 0.68 | 0.69 | 0.81 | 0.86 |
| bge | 0.73| 0.74| 0.85| 0.89|
| BM25 + bge |0.68 | 0.69 |0.82 |0.87 |
| gte |0.75 | 0.76 | 0.88 | 0.92 |
| BM25 + gte | 0.71 | 0.72 | 0.83 | 0.88 |

**Comment by staoxiao** [comment]
I don't know the implementation method of hybrid search in Elasticsearch, which will have a significant influence on the hybrid performance. Here are some possible reasons:
- The range of scores from bge and bm23 are very different. Using cosine similarity (so it needs to normalize embedding), the scores from bge models are always smaller than 1, but the score from bm25 is always higher (no need to be smaller than 1). Adding bm25 score to cosine similarity score directly is not a good way to integrate them.
- Maybe Elasticsearch first retrieve items by bm25, then re-rank by dense vector. In this way, the upper bound of evaluation metrics is limited by bm25.
