### ISSUE TITLE
I did pip install -U FlagEmbedding and I still got "cannot import name 'LLMEmbedder' from 'FlagEmbedding'" error

### ISSUE THREAD

**Issue by sungkim11** [FlagOpen/FlagEmbedding#170]
Exception has occurred: ImportError
cannot import name 'LLMEmbedder' from 'FlagEmbedding' (/usr/local/lib/python3.8/dist-packages/FlagEmbedding/__init__.py)
  File "/home/project/src/llmembedder.py", line 1, in <module>
    from FlagEmbedding import LLMEmbedder
ImportError: cannot import name 'LLMEmbedder' from 'FlagEmbedding' (/usr/local/lib/python3.8/dist-packages/FlagEmbedding/__init__.py)

**Comment by staoxiao** [comment]
Sorry, the package in pypi has not been updated.

**Comment by staoxiao** [comment]
We just uploaded the latest FlagEmbedding 1.1.3 to pypi, and you can install the latest version by `pip install -U FlagEmbedding`.

**Comment by sungkim11** [comment]
I do not get error anymore, but I cannot get FlagEmbedding to work in general. Do you know why I get "----------using 3*GPUs----------" then nothing happens?

**Comment by staoxiao** [comment]
Can you share some codes to provide more information?

**Comment by sungkim11** [comment]
This is general for any usage of FlagEmbedding. My environment is a workstation with 3 3090s on ubuntu, using huggingface/transformers-pytorch-gpu docker image.

from FlagEmbedding import LLMEmbedder

# Define queries and keys
queries = ["test query 1", "test query 2"]
keys = ["test key 1", "test key 2"]

# Load model (automatically use GPUs)
model = LLMEmbedder('BAAI/llm-embedder', use_fp16=False)

# Encode for a specific task (qa, icl, chat, lrlm, tool, convsearch)
task = "qa"
query_embeddings = model.encode_queries(queries, task=task)
key_embeddings = model.encode_keys(keys, task=task)

similarity = query_embeddings @ key_embeddings.T
print(similarity)

**Comment by sungkim11** [comment]
sentence_transformers works fine in same environment.

**Comment by namespace-Pt** [comment]
Sorry, I cannot reproduce this error. I got the expected output using the above code:
```
[[0.89705956 0.853418  ]
 [0.84624743 0.90914035]]
```

Could you please print key_embeddings and query_embeddings to see if they have meaningful values? For example:
```python
print(key_embeddings[0, :5])

# The output should be similar to
[-0.01383494  0.01495152  0.00169425  0.01854622  0.06940375]
```

**Comment by sungkim11** [comment]
Yeah... It works on CPU, so I will use CPU instead. Thank for trying to replicate.

**Comment by sungkim11** [comment]
pip install -U FlagEmbedding works as expected.
