### ISSUE TITLE
微调效果问题

### ISSUE THREAD

**Issue by Xls1994** [FlagOpen/FlagEmbedding#178]
您好，我在 baike_2018qa 这个数据集上（https://github.com/brightmart/nlp_chinese_corpus ）微调了一下bge-large的模型，发现在自己数据集上测试的召回率下降了不少。 我看了一下这个数据集应该没有加到原始模型微调的数据里。下面是我配置的一些微调参数，是参数配置不合理还是数据集上重复度偏高导致的呢。看损失，都有在下降的。麻烦帮忙看看哪些地方可能存在问题，感谢。

--learning_rate 1e-5 \
--num_train_epochs 1 \
--per_device_train_batch_size 2 \
--dataloader_drop_last True \
--normlized True \
--temperature 0.02 \
--query_max_len 64 \
--passage_max_len 258 \
--train_group_size 8 \
--gradient_accumulation_steps 128 \
--save_steps 1000 \
--save_total_limit 20 \
--negatives_cross_device

**Comment by staoxiao** [comment]
您好，目前的per_device_train_batch_size太小了，尽可能增大batch size，可以通过开启`--fp16`, `--deepspeed df_config.json`, `--gradient_checkpointing`等方式来拓展batch size。如果文本不长的话，可以适当减小query_max_len，使得可以开启更大的batch size。

**Comment by Xls1994** [comment]
您好，我在尝试修改参数之后，发现程序在执行的时候出现了异常退出了。
`WARNING:torch.distributed.elastic.agent.server.api:Received 1 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 28820 closing signal SIGHUP
Traceback (most recent call last):
  File "/home/deploy/anaconda3/envs/yyl_env/bin/torchrun", line 8, in <module>
    sys.exit(main())`
但是没有其他相关的报错信息了，这个错误您有遇到过吗。
另外，这种情况下能继续从原来读取的数据地方继续训练吗，还是只能从头开始训练了呢

**Comment by staoxiao** [comment]
没有遇到，可以再运行看看是否出现更详细的报错信息。
之前的checkpoint表现不好，建议从头训练。

**Comment by Xls1994** [comment]
好的，感谢您的回复。我再试下看看
