### ISSUE TITLE
从checkpoint回复后训练，代码出错

### ISSUE THREAD

**Issue by Xls1994** [FlagOpen/FlagEmbedding#183]
在 trainer.train() 时，增加了 resume_from_checkpoint=True 的参数，但是代码没有正常执行。想问一下，是目前不支持这种操作吗

`AttributeError: 'BiEncoderModel' object has no attribute
'_keys_to_ignore_on_save'`

**Comment by staoxiao** [comment]
目前没有实现resume的操作，可以将model_name_or_path替换为之前的checkpoint进行训练

**Comment by Xls1994** [comment]
好的，感谢。 请问后续有提供这方面的操作的计划吗

**Comment by staoxiao** [comment]
您好，暂时没有考虑这方面。如果您实现了此类支持，也欢迎提PR👏。
