### ISSUE TITLE
llm-embedder在MTEB这种传统的向量表征任务上表现咋样哈

### ISSUE THREAD

**Issue by lierer007** [FlagOpen/FlagEmbedding#186]
llm-embedder太棒了。
不过想请问下llm-embedder还能保留bge在sts、retrieval这种传统任务上效果吗？
它在MTEB榜单的分数大概是多少哈

**Comment by namespace-Pt** [comment]
谢谢你~ 我们测试llm-embedder在mteb retrieval上结果是51.14

**Comment by lierer007** [comment]
有点强啊，通用的retrieval上还能有51.14的表现
请教下其它任务如sts这样的QQ相似度计算，有办法加一个优化目标到llm-embedder里吗
或者说如果想把bge和llm-embedder融合到一个模型，然后在mteb和popqa这些检索增强任务上同时表现得好，您有什么建议吗

**Comment by namespace-Pt** [comment]
我觉得理论是可行的。如果只关注检索增强的qa效果的话，可以用bge自身的instruction，然后把msmarco、nq的数据混在bge的task-specific finetune数据里一起训练。

**Comment by lierer007** [comment]
不好意思哈上面没表达清楚，如果是想在mteb以及llm-embedder相关的所有验证集(popqa,mmlu,icl,msc,lrlm,tool,qrecc)上都表现好呢

**Comment by namespace-Pt** [comment]
那同样可以试试把所有数据混起来训练，但是可能面临不同任务之间的冲突，因此效果可能难以保证。

**Comment by lierer007** [comment]
是的是的，多谢多谢哈
方便问下，mteb的通用retrieval验证集  和  llm-embedder的所有retrieval-augmentation验证集，主要的区别是啥哈
看起来bge和llm-embedder的数据和优化目标都不太一样

**Comment by namespace-Pt** [comment]
区别主要在于mteb直接衡量检索效果，而llm-embedder中检索只是大模型生成的中间过程，检索效果由大模型的生成结果反过来决定，因此优化目标不一样。
