### ISSUE TITLE
请问fine-tuning的训练数据是如何收集的

### ISSUE THREAD

**Issue by BiggyBing** [FlagOpen/FlagEmbedding#19]
你好，我在readme中看到
“
Training data:

For English, we collect 230M text pairs from [wikipedia](https://huggingface.co/datasets/wikipedia), [cc-net](https://github.com/facebookresearch/cc_net), and so on.

For chinese, we collect 120M text pairs from [wudao](https://github.com/BAAI-WuDao/Data), [simclue](https://github.com/CLUEbenchmark/SimCLUE) and so on.
”
想请教一下collect text pairs的细节。

**Comment by staoxiao** [comment]
使用网页文档的title-body pairs (wikipedia, cc-net)，以及问答对(stackexchange)，同时包括了sentence-transformers的开源训练数据集：https://huggingface.co/datasets/sentence-transformers/embedding-training-data。

**Comment by BiggyBing** [comment]
@staoxiao 谢谢，还想请问一下，RetroMAE当时pre-train要用多久呢？还有就是fine-tune的时候 一定要很大的batch size么？我只有8张A10，不知道能不能跑的起来

**Comment by staoxiao** [comment]
您好，Pre-train的时间跟数据量有关，BGE的版本用了大概两周。
如果您是将BGE用于下游任务微调，8张A100足够了；如果是尝试训一个通用向量模型，8*A100也可以训得动large-scale的模型，但是batch size更大效果会更好（负样本会更多），可以尝试使用gradient_checkpointing或deepspeed等一些节省显存的方式。

**Comment by BiggyBing** [comment]
@staoxiao 谢谢！
