### ISSUE TITLE
正样本的数量

### ISSUE THREAD

**Issue by chiosChen** [FlagOpen/FlagEmbedding#197]
您好，想请教您一些对比学习在retrieval任务中的问题。

区别于STS这类任务，retrieval任务中一条query可对应的正样本是非常多样的，也就是说给定一条query，其对应的多个document之间也有可能存在比较大的差异。

而对比学习的核心思想是把每个个体看作一个类，通过对比大量的负样本来学习出区别个体的关键特征。这类任务往往正样本和原始样本之间差异较小，例如cv中通过简单的数据增强形成正样本，simcse等工作中通过简单的dropout形成正样本。

明显retrieval任务中的正样本和原始样本的关系，和以上的任务中不同。假设，我们仍然可以通过对比学习，学习出一条query相关的document之间的关键特征，那应该要保证训练时对每个query要有足够多的正样本，否则很难学习到多种正样本之间的共性？

在bge中似乎只保证了负样本的多样性？请问是否有做实验去验证正样本数量对模型效果的影响？

**Comment by staoxiao** [comment]
您好，bge的训练代码中时确实一次只能训练一个正样本，多个正样本只能通过多训练几个epoch让模型见到。

如果在一次训练中塞入多个正样本可能会带来更好的效果，但是这块我们并没有深入分析过，目前我们能够获取到的数据集中也很少有一个query带有多个正样本的情况。

**Comment by chiosChen** [comment]
十分感谢回复，另外有看到bge在第二阶段用到text2vec，这个模型是用Cosent的损失函数来训练的，想请问bge是否有尝试过使用Cosent来训练比较效果？
如果没有，是因为Cosent对有标签数据的格式要求多，所以不太好收集高质量数据集吗？

我看到text2vec的作者也在bge基础上，用Cosent做了进一步训练，在匹配问题上有所提高。

**Comment by staoxiao** [comment]
没有试过使用cosent，Cosent需要所有样本对的排序关系，这个比较难以获取，同时在样本数量很多的情况下，计算所有样本对的排序关系也比较复杂。目前主流的text embedding 训练方案还是infonce。

**Comment by chiosChen** [comment]
了解，感谢您的回复。
