### ISSUE TITLE
MTEB榜单没看懂，为什么说BGE是最佳？

### ISSUE THREAD

**Issue by yucc-leon** [FlagOpen/FlagEmbedding#2]
![image](https://github.com/FlagOpen/FlagEmbedding/assets/17897916/58459b35-229c-4477-af64-a2e00843bdcc)
是串列了吗？指标方面不应该是分数越高越好吗？

**Comment by staoxiao** [comment]
抱歉，中文readme确实串列了，已更正。谢谢指出！
