### ISSUE TITLE
开心和石头的相似度得分都0.8，这也太高了吧

### ISSUE THREAD

**Issue by NaviQuant** [FlagOpen/FlagEmbedding#21]
![image](https://github.com/FlagOpen/FlagEmbedding/assets/11497574/1ebae90b-33ee-4480-99db-adf2b2c4045f)

**Comment by staoxiao** [comment]
您好，BGE训练采用的对比学习，相似度的绝对值不具备太大参考意义，请参考相对值的大小，比如"难过"的相似度要大于”石头“。另外，对于短句来说，如果需要选择相对值大小进行判断，需要选择一个较大的值，例如0.85,0.9之类的（请尽量根据您的实际情况选择阈值）

**Comment by NaviQuant** [comment]
现在想设定阈值来控制检索的答案

**Comment by NaviQuant** [comment]
比如：要获取与这个检索相关的问题，那么就需要一个阈值来过滤

**Comment by staoxiao** [comment]
最好是根据您的实际数据判断一个阈值。
如果都是如上文显示的一个词语这样的短句，建议设置一个较大的阈值(模型对很短句子的相似度数值会偏高)。

**Comment by NaviQuant** [comment]
测试了比较长的问题，大概20个字符左右，无论问题如何不相关，没有遇到过0.6以下的

**Comment by staoxiao** [comment]
抱歉，当前模型相似度数值的大小不是0-1范围内的平均分布，并不是大于0.6就相关。您可以选择一个更大的阈值，例如前面提到的0.85或0.9。

**Comment by NaviQuant** [comment]
嗯嗯，通过和其他向量模型对比测试，发现bge得分普遍偏高，而且分布区间0.6-1.0之间

**Comment by NaviQuant** [comment]
所以想测试证明bge模型是最优的，就不知道该如何测试了

**Comment by staoxiao** [comment]
感谢您的反馈，我们后面会尝试优化相似度分布的区间。
对于如何测试向量模型，您可以参考一些常见的检索任务指标，如NDCG, Recall等，判断模型是否能检索回来相关的样本。

**Comment by NaviQuant** [comment]
好的，谢谢

**Comment by NaviQuant** [comment]
bge模型是不是适用于很长的文档搜索，而不是短问题？

**Comment by staoxiao** [comment]
我们目前的实验结果是BGE模型长文档检索和短句子匹配上效果都不错(但确实长文档上效果更明显)。
您这边是如何进行的测试？如果方便的话，可以提供一些测试细节，也可以发邮件给我，我们这边研究一下。

**Comment by NaviQuant** [comment]
我这边都是短文本与短文本之间的匹配，平均大概20-30个字符；你那边的测试方法和数据时什么，我和其他的向量模型对比测试下

**Comment by staoxiao** [comment]
> 我的理解是用户输入的短句子向量，然后与所有长文档的向量计算相似度，最后找到相似度值最高的那个返回给用户？

是的，这是常见的检索任务场景。对于短句子BGE也可以这样使用。

**Comment by staoxiao** [comment]
> 我这边都是短文本与短文本之间的匹配，平均大概20-30个字符；你那边的测试方法和数据时什么，我和其他的向量模型对比测试下

有两种常用的测试方式：一种是检索任务，判断召回的前10个文本中是否存在匹配的文本，计算NDCG@10；另一种是方式是句子相似度任务，计算两个文本之间相似度，计算spearman值。
您可以参考：https://github.com/FlagOpen/FlagEmbedding/tree/master/C_MTEB 进行测试。

**Comment by staoxiao** [comment]
如果只跑检索和生成任务，可以
```
python eval_C-MTEB.py --model_name_or_path BAAI/bge-large-zh --task_type Retrieval
python eval_C-MTEB.py --model_name_or_path BAAI/bge-large-zh --task_type STS
```

**Comment by staoxiao** [comment]
是的

**Comment by NaviQuant** [comment]
> 

嗯嗯，明天测试下不同模型的之间的效果；感谢

**Comment by NaviQuant** [comment]
好的，感谢

**Comment by Daniel-1997** [comment]
> ![image](https://user-images.githubusercontent.com/11497574/259699273-1ebae90b-33ee-4480-99db-adf2b2c4045f.png)

请问这个gradio在哪里可以使用？

**Comment by staoxiao** [comment]
> 预训练的数据可以给一份不，想融合垂直领域的数据进行二次训练

可以在此下载wudao数据集：https://data.baai.ac.cn/details/WuDaoCorporaText

**Comment by NaviQuant** [comment]
好的，谢谢

**Comment by yiyayybj** [comment]
您好，请问eval_C-MTEB.py这部分代码是在哪个目录下，现在好像找不到了
python eval_C-MTEB.py --model_name_or_path BAAI/bge-large-zh --task_type Retrieval
python eval_C-MTEB.py --model_name_or_path BAAI/bge-large-zh --task_type STS
