### ISSUE TITLE
关于微调的passage_max_len取值

### ISSUE THREAD

**Issue by Alemax067** [FlagOpen/FlagEmbedding#213]
passage_max_len: max length for passage. Please set it according the average length of passages in your data.

请问这里是应该把pos和neg作为一个整体来计算token长度取平均值，还是对里面的元素（取neg是长度为7的列表）计算token长度取平均值

**Comment by Alemax067** [comment]
d_collated = self.tokenizer(
            passage,
            padding=True,
            truncation=True,
            max_length=self.passage_max_len,
            return_tensors="pt",
        )
看这里代码似乎是后者

**Comment by staoxiao** [comment]
最方便的是直接开到最大值512，但是训练速度会变慢，同时batch size开不大。
最好的选择是根据实际文章的长度来设置，文章比较短，就可以设小一些，提高训练速度；pos和neg都属于passage，计算所有passage的token数量范围，选一个能覆盖大部分passage的数字即可。

**Comment by Alemax067** [comment]
你好，你可能没理解我的意思，比如一个数据集，n条数据，每条数据pos是一个列表，里面有一句话，neg是一个列表，里面有7句话，我要算passage_max_len的话是用 (数据集中所有的pos和neg的token数求和)/n 还是 (数据集中所有的pos和neg的token数求和)/8n

**Comment by staoxiao** [comment]
你好，是所有passage的值，即(数据集中所有的pos和neg的token数求和)/8n

**Comment by Alemax067** [comment]
好的，万分感谢！

**Comment by ChengsongLu** [comment]
你好，请问max_length取平均长度的话，不足的我理解是用paddding，那超出的句子是怎么处理的？是截断吗？
