### ISSUE TITLE
Add contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [FlagOpen/FlagEmbedding#218]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
 The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.

![contributors](https://github.com/FlagOpen/FlagEmbedding/assets/147402107/cd1dca98-fd94-4a57-ad5f-2fcfb4b1e7ac)

**Comment by Kalyanimhala** [comment]
@staoxiao  kindly assign me this #218 this issue, i want to work on it. Thank You!!

**Comment by staoxiao** [comment]
Good advice! Feel free to pull a request.
