### ISSUE TITLE
请问一下，bge模型怎么在中文NSP任务上微调呢？

### ISSUE THREAD

**Issue by rangehow** [FlagOpen/FlagEmbedding#224]
我把bge模型加载到transformers的BertForNextSentencePrediction，提示分类头缺失，需要在下游任务上微调。想请教一下您，中文有什么数据集合适用于NSP任务吗，大概流程应该怎么走呢？万分感激%%

**Comment by staoxiao** [comment]
您好，NSP任务不需要标签数据，用相关下游数据进行训练即可。
这个任务不是很流行，我们也没有跑过。
