### ISSUE TITLE
raise ValueError('Distributed training has not been initialized for representation all gather.')

### ISSUE THREAD

**Issue by hjq133** [FlagOpen/FlagEmbedding#23]
在我运行finetune代码时报了这个错误
似乎finetune代码中也没有看到分布式的初始化? 也没有看到将model放到ddp wrapper里面

**Comment by staoxiao** [comment]
您好，可以提供一下您的运行代码吗？
分布式的初始化和ddp wrapper会在tranier里面完成

**Comment by hjq133** [comment]
我的运行脚本是这样的，只是换了种启动方式:
`python -m torch.distributed.launch --nnodes 1 --nproc_per_node $GPUS_PER_NODE --rdzv_endpoint localhost:$MASTER_PORT --use-env \
    -m FlagEmbedding.baai_general_embedding.finetune.run \
    --output_dir './output_ft' \
    --model_name_or_path $MODEL_NAME_OR_PATH \
    --train_data $DATA_FILE \
    --learning_rate 1e-5 \
    --num_train_epochs 5 \
    --normlized True \
    --temperature 0.01 \
    --query_max_len 32 \
    --passage_max_len 128 \
    --negatives_cross_device \
    --per_device_train_batch_size 1 `

您的代码在初始化trainer之前会初始化BiEncoderModel
如果negative cross device为true的话，会涉及到dist调用，应该是这里出了些问题

**Comment by staoxiao** [comment]
可以提供一下torch和transformers的版本吗？这边未能复现这个bug
如果只有一张GPU的话，可以不开negatives_cross_device。
另外，per_device_train_batch_size设为1太小了，建议尽可能设大点。

**Comment by hjq133** [comment]
感谢回复，暂时已经解决了！

**Comment by zll0000** [comment]
@hjq133 怎么解决的
