### ISSUE TITLE
reranker-finetune中设置batch_size

### ISSUE THREAD

**Issue by Harmon-l** [FlagOpen/FlagEmbedding#230]
请问微调reranker是否可以设置per_device_train_batch_size大于1，当我设置batch_size=4的时候，出现RuntimeError，Target sizes: [16, 597], Tensore sizes: [1, 514]。如果设置batch_size不等于1时，需要同步更改那些参数吗？

**Comment by staoxiao** [comment]
batch size说可以大于1的。
这个问题说由于句子token数量大于512导致的，可以参考https://github.com/FlagOpen/FlagEmbedding/issues/202
代码中刚修改了truncation=True，您可以git clone最新的代码进行训练。

**Comment by Harmon-l** [comment]
拉取了最新代码现在问题解决了，感谢您的回复~
