### ISSUE TITLE
报错：_save() got an unexpected keyword argument 'state_dict'，请问这个是怎么修改？这个_save()函数在哪呢？

### ISSUE THREAD

**Issue by mechigonft** [FlagOpen/FlagEmbedding#233]
In my environment (transformers==4.31.0, deepspeed==0.10.3)
Following your advice, I got the following error when saving the model after training in the [line](https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/baai_general_embedding/retromae_pretrain/trainer.py#L30).

`_save() got an unexpected keyword argument 'state_dict'`

I succeeded in reducing the memory by making the following modifications.

`def _save(self, output_dir: Optional[str] = None, state_dict=None):`

_Originally posted by @one-award in https://github.com/FlagOpen/FlagEmbedding/issues/132#issuecomment-1730909085_

**Comment by mechigonft** [comment]
报错：_save() got an unexpected keyword argument 'state_dict'，请问这个是怎么修改？这个_save()函数在哪呢？

**Comment by staoxiao** [comment]
在这里：https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/baai_general_embedding/retromae_pretrain/trainer.py#L30

或者把transformers降版本，4.28是可以跑的。

**Comment by mechigonft** [comment]
感谢，已经成功解决

**Comment by Youfenghao** [comment]
@staoxiao ，能不能发一个requirement.txt, 运行多次微调代码都卡在 trainer上了，是不是跟安装包环境有关，setup.py默认下载最新版的库包时，总是报错
