### ISSUE TITLE
添加gradient_checkpointing参数出现了问题

### ISSUE THREAD

**Issue by yolandalyl** [FlagOpen/FlagEmbedding#236]
TypeError: BiEncoderModel.gradient_checkpointing_enable() got an unexpected keyword argument 'gradient_checkpointing_kwargs'
这该怎么解决呢

**Comment by staoxiao** [comment]
这个问题我们没有遇到过，猜测可能是transformers版本更新导致的，可以使用transformers 4.28.1试试

**Comment by yolandalyl** [comment]
感谢回复，通过降低transformers版本解决了问题~
