### ISSUE TITLE
parameter: batch size per gpu

### ISSUE THREAD

**Issue by hjq133** [FlagOpen/FlagEmbedding#25]
您好，非常棒的工作！
有一点疑惑，您在readme中提到

> We trained our model on 48 A100(40G) GPUs with a large batch size of 32,768 (so there are 65,535 negatives for each query in a batch)

根据我的理解，negative num = (group size * batch size per gpu * gpu_num)  - 1
您提到在finetune时 negative num = 65535, 那么可以推算出 group size * batch size per gpu = (65535+1) / 48 ，但显然这不是一个整数。所以是不是哪里弄错了呢？

请问能提供一下BGE-base-zh在finetune时的具体参数吗，想了解下，感谢！

**Comment by staoxiao** [comment]
您好，抱歉这里计算出错了。batch size per gpu=683， 总batch size应等于33467， 负样本数量为65567。
base与large参数一致，出了lr（base 为2e-5, large 为1e-5)

**Comment by staoxiao** [comment]
感谢指出，已更正

**Comment by hjq133** [comment]
@staoxiao 您好
您在finetune时的batch size per gpu=683, 如果您的group size为2的话。
这意味着一个batch内encode了683个triplet(query, pos_passage, neg_passage)是吗
而以上根据您的readme，似乎是40G A100在max length128 下就可以开到这么大的batch size？

不知道您默认是否会开negative cross device呢？根据我的实验来看，dist gather后显存会有大幅度增加。
比如我在不进行dist gather的情况下，能用到256的batch size per device。但是在dist gather的实验中，这个数字大概会降到 60-80左右，您是否也会遇到这样的现象呢？

**Comment by staoxiao** [comment]
您好，我们开启了deepspeed-stage 1和gradient_checkpointing， 能显著降低显存的使用
