### ISSUE TITLE
bge reranker score < 0, can we suppose that the relation is low?

### ISSUE THREAD

**Issue by LCorleone** [FlagOpen/FlagEmbedding#250]
hi all, suppose my query retriever get [d1, d2, d3, d4], and reranker input [[query, d1], [query, d2], [query, d3], [query, d4]], and output [3, 0.3, -2, -5]
if top3 is selected, when the 3rd < 0, should i use it or just drop it? thanks

**Comment by LCorleone** [comment]
or can we set a threshold based on the reranker score to filter low relation doc?

**Comment by staoxiao** [comment]
> or can we set a threshold based on the reranker score to filter low relation doc?

Yes, you can try to set a threshold to filter the docs. And noted that the threshold may be different for different tasks, so we suggest selecting a threshold based on your data.

**Comment by LCorleone** [comment]
> > or can we set a threshold based on the reranker score to filter low relation doc?
> 
> Yes, you can try to set a threshold to filter the docs. And noted that the threshold may be different for different tasks, so we suggest selecting a threshold based on your data.

many thanks, I will try it
