### ISSUE TITLE
C_MTEB评测时如何从本地加载数据

### ISSUE THREAD

**Issue by lierer007** [FlagOpen/FlagEmbedding#251]
C_MTEB评测时想从本地加载数据如T2Retrieval任务，应该怎么做呢
我修改了description中的hf_hub_name值
```'hf_hub_name': '/home/notebook/XXX/data/C-MTEB/T2Retrieval',```
但是在加载T2Retrieval-qrels数据时显示  KeyError: 'dev'； （运行时的key为validation）

这是我的脚本
```
from mteb import MTEB
from C_MTEB import *
from sentence_transformers import SentenceTransformer

model_name = "/home/notebook/code/personal/all-MiniLM-L6-v2"

model = SentenceTransformer(model_name)
evaluation = MTEB(tasks=['T2Retrieval'])
results = evaluation.run(model, output_folder=f"zh_results/{model_name}")
```

**Comment by staoxiao** [comment]
请问你的本地数据是什么格式的？

**Comment by rumsyx** [comment]
![image](https://github.com/FlagOpen/FlagEmbedding/assets/30486101/3fa7f1bf-7183-457d-a69c-02d36f686bfe)
我也出现一样的问题

**Comment by lierer007** [comment]
好像找到原因了  
要把readme也下载下来  HF的datasets通过readme来定位加载

**Comment by rumsyx** [comment]
下载了readme，并按照hf的dataset格式调整了一下，
![image](https://github.com/FlagOpen/FlagEmbedding/assets/30486101/917b5145-a4ab-4efe-a4a2-14a1063f8b74)
报了新的错
![image](https://github.com/FlagOpen/FlagEmbedding/assets/30486101/5eb4b5aa-0227-48bc-b4f4-e1b7ea45653c)

**Comment by rumsyx** [comment]
> 下载了readme，并按照hf的dataset格式调整了一下： ![image](https://user-images.githubusercontent.com/30486101/281596135-917b5145-a4ab-4efe-a4a2-14a1063f8b74.png) 又报了新的错，还有哪里出了问题呢。。 ![image](https://user-images.githubusercontent.com/30486101/281595799-5eb4b5aa-0227-48bc-b4f4-e1b7ea45653c.png)

这是一个已经被fix的bug：huggingface/datasets#5739，升级datasets包即可( huggingface/datasets#5748 )

**Comment by chaoStart** [comment]
meta版本Version: 1.19.7版本里面，加载本地数据集的方式如下:    metadata = TaskMetadata(
        name="T2Retrieval",
        description="T2Ranking: A large-scale Chinese Benchmark for Passage Ranking",
        reference="https://arxiv.org/abs/2304.03679",
        dataset={
            # "path": "C-MTEB/T2Retrieval",#修改之前的数据路径
            "path": "/home/bqc/.cache/evalscope/dataset/T2Retrieval",
            "revision": "8731a845f1bf500a4f111cf1070785c793d10e64",
            "qrel_revision": "1c83b8d1544e529875e3f6930f3a1fcf749a8e97",
        },修改path为本地的路径，同时要保证数据集完整，不能缺失。如果想要测试C-MTEB/T2Retrieval，除了下载C-MTEB/T2Retrieval的数据集，还要下载C-MTEB/T2Retrieval-qrels的数据集，建立2个文件夹分别起名为T2Retrieval和T2Retrieval-qrels

**Comment by viviansmlie** [comment]
> meta版本Version: 1.19.7版本里面，加载本地数据集的方式如下: metadata = TaskMetadata( name="T2Retrieval", description="T2Ranking: A large-scale Chinese Benchmark for Passage Ranking", reference="https://arxiv.org/abs/2304.03679", dataset={ # "path": "C-MTEB/T2Retrieval",#修改之前的数据路径 "path": "/home/bqc/.cache/evalscope/dataset/T2Retrieval", "revision": "8731a845f1bf500a4f111cf1070785c793d10e64", "qrel_revision": "1c83b8d1544e529875e3f6930f3a1fcf749a8e97", },修改path为本地的路径，同时要保证数据集完整，不能缺失。例如：想要测试T2Retrieval数据集，除了下载C-MTEB/T2Retrieval的数据集，还要下载C-MTEB/T2Retrieval-qrels的数据集，建立2个文件夹分别起名为T2Retrieval和T2Retrieval-qrels

你好 想问一下T2Retrieval和T2Retrieval-qrels的区别，我看T2Retrieval中有id和query和text，id相同的代表是一对query和text；而T2Retrieval-qrels中只有pid，这里的pid是什么含义呢？
