### ISSUE TITLE
Guidance of fine tuning data prep step

### ISSUE THREAD

**Issue by sroy-forr** [FlagOpen/FlagEmbedding#255]
Hi,
Thank you for the amazing repo. A general question on the fine-tuning step.

Do you have any guidance on generating pos, neg questions? I have a general idea from sbert webpage using t5 model and then random sampling negatives, but I want to explore your suggestions.

Will random sampling of negatives work? I am seeing pinecone using transformer embeddings to mine negatives.

**Comment by staoxiao** [comment]
Using t5 or LLMs to generate the positive for a sentence is a good approach. As for negatives, you can use embedding to mine hard negatives. Here is a simple script to mine negative: https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune#hard-negatives
