### ISSUE TITLE
ReRanker效果不及预期

### ISSUE THREAD

**Issue by Xls1994** [FlagOpen/FlagEmbedding#256]
您好，我在T2Ranking的数据集上，用bge-large 召回了100个文档，计算相关的recall值。然后，再使用reranker去对这100个文档进行重排序，重新计算recall。发现重排序之后的recall比之前的降低了 0.03 左右。

这个和您公布的在T2Ranking数据集上的效果有所差异，是因为评价指标不一样吗，还是其他原因

**Comment by staoxiao** [comment]
readme中T2Ranking计算的是NDCG。
另外，是在top多少计算的recall值，reranker方法对头部的排序更准确。recall只能反应是否存在列表中，无法反映在列表中的位置。

**Comment by Xls1994** [comment]
您好，我计算的是top5、top20和top50。发现reranker之后的指标对比large模型本身的这几个召回率都有下降，

**Comment by staoxiao** [comment]
那建议使用bge-large模型挖掘负样本，微调一下reranker模型

**Comment by Xls1994** [comment]
好的，感谢建议
