### ISSUE TITLE
Pre-train 示例疑问

### ISSUE THREAD

**Issue by CuteMing** [FlagOpen/FlagEmbedding#26]
请问一下，所给出 Pre-train 示例是 继续预训练 还是 从零预训练 呢？FlagEmbedding.baai_general_embedding.retromae_pretrain.run

**Comment by staoxiao** [comment]
您好，从零预训练收敛速度慢，建议您选择一个基座模型继续预训练

**Comment by CuteMing** [comment]
torchrun --nproc_per_node {number of gpus} \
-m FlagEmbedding.baai_general_embedding.retromae_pretrain.run \
--output_dir {path to save model} \
--model_name_or_path BAAI/bge-large-en \
--train_data toy_pretrain_data.jsonl \
--learning_rate 2e-5 \
--num_train_epochs 5 \
--per_device_train_batch_size 1 \
--dataloader_drop_last True \
--max_seq_length 512 \
--logging_steps 1

请问按照您给的示例，就是在bge-large-en 上继续预训练么？

**Comment by staoxiao** [comment]
可以直接在bge上进行微调，也可以选择在bge上继续预训练，再微调，这样在下游任务上效果一般会更好些

**Comment by zouzoutingting** [comment]
预训练的数量级大概需要多少呢

**Comment by zouzoutingting** [comment]
继续预训练的数量级大概是需要多少呢

**Comment by staoxiao** [comment]
没有明确的要求，预训练的数据集与下游任务相关的话效果更好，您可以使用您下游任务的数据进行预训练。
