### ISSUE TITLE
微调数据集的预处理问题

### ISSUE THREAD

**Issue by Xls1994** [FlagOpen/FlagEmbedding#261]
您好，我下载了你们公开的wudao的数据集 MTP， 发现里面有一些正样本的实际长度已经超过了512的大小，这种情况下，是直接对正样本截断了吗。

**Comment by staoxiao** [comment]
是的

**Comment by Xls1994** [comment]
这种方式如果有一些正样本中和query相近的语义片段，比较靠后的情况，不会导致微调出现偏差吗。还是说微调数据量足够多的时候，能避免这种问题呢

**Comment by staoxiao** [comment]
会存在一些不可避免的问题，所有后期也在训练更长文本的模型。

**Comment by Xls1994** [comment]
好的，感谢您的回答。更长文本的模型是有计划会放出吗

**Comment by staoxiao** [comment]
训练完后会放出的
