### ISSUE TITLE
微调后的模型调用

### ISSUE THREAD

**Issue by aaashinshin** [FlagOpen/FlagEmbedding#263]
作者您好，请问我要使用微调后的模型，比如我微调时的output_dir是output-pt，
我想调用是应该写成--model_name_or_path output-pt \ 还是 --model_name_or_path output-pt/encoder_model \呢

**Comment by staoxiao** [comment]
微调后的模型使用output-pt，
如果是预训练后的模型，其存储位置为encoder_model，使用output-pt/encoder_model

**Comment by aaashinshin** [comment]
好的明白了，感谢您的回复。
