### ISSUE TITLE
执行run_dense.py所需的数据能提供toy data吗

### ISSUE THREAD

**Issue by hgwu4869** [FlagOpen/FlagEmbedding#267]
在fine-tune.md中，提供了下载数据链接，但是数据太大了，有15G+，请问能直接提供一些toy data用于快速跑通代码吗？

![bge-run-dense数据示例](https://github.com/FlagOpen/FlagEmbedding/assets/41505486/4f999f21-d966-4d92-92c8-ec74d5a41cd9)

**Comment by namespace-Pt** [comment]
Hi, 见 https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/llm_embedder/docs/fine-tune.md#llm-embedder-toy-example

**Comment by hgwu4869** [comment]
thx~
