### ISSUE TITLE
依据任务特性修改网络的两个问题

### ISSUE THREAD

**Issue by KekeWa** [FlagOpen/FlagEmbedding#27]
1. 期望cpu推理加速（从768降到128），故想在您训练代码的最后一层网络结构中加一个768*128的pooling
2. 期望相似句子相似度高，不相似句子，相似度低，故将损失函数改为交叉熵
您对比学习的网络结构请问有代码公示吗？可否标记位置呢？如果尝试后有效果我向您汇报一下

**Comment by staoxiao** [comment]
您好，模型代码在：https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/baai_general_embedding/finetune/modeling.py
具体可参考里面的forward函数
