### ISSUE TITLE
请问这报错什么原因，mac跟linux都一样不行

### ISSUE THREAD

**Issue by msute** [FlagOpen/FlagEmbedding#29]
OSError: Unable to load weights from pytorch checkpoint file for '/FlagEmbedding/BAAI/bge-large-zh/pytorch_model.bin' at '/FlagEmbedding/BAAI/bge-large-zh/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by staoxiao** [comment]
您好，可以查看一下是否完整下载了bge-large-zh文件，pytorch_model.bin大概在1.3G 左右。

**Comment by msute** [comment]
> 

是完整的。我从HuggingFace下载，执行时候已经使用了绝对路径

**Comment by staoxiao** [comment]
方便提供一下您的加载代码吗？

**Comment by msute** [comment]
> 方便提供一下您的加载代码吗？

代码就是你们github的示例代码，我只将路径改了一下

**Comment by BrownTen** [comment]
> OSError: Unable to load weights from pytorch checkpoint file for '/FlagEmbedding/BAAI/bge-large-zh/pytorch_model.bin' at '/FlagEmbedding/BAAI/bge-large-zh/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

#### [这个问题网上有解决方案](https://blog.csdn.net/A_zhangpengjie/article/details/113978101)
#### 出现这个问题的原因
- 发生这个问题的原因是你没能完整下载模型数据
- 例如 在下载 最大的 pytorch_model.bin （可能有1.3G左右）这个文件的时候 中断了，文件不完整，就会出现这个错误。
#### 解决这个问题的方法
- 我自己在使用的时候，是通过代码获取模型
- 例如 SentenceTransformers `SentenceTransformers('model name')`这一句加载模型的时候，程序就会从HuggingFace进行下载。其他的模型读取方式详细可以看[ReadMe](https://github.com/FlagOpen/FlagEmbedding/blob/master/README_zh.md#usage)
- 由于我的网络问题，大文件多次发生下载失败的问题，只需要到 `C:\Users\Admin\.cache\torch\sentence_transformers`(如果是windows的话)删除对应的模型重新下载，直至所有的下载进度条是完成的即可。
- 如果你是从HuggingFace `https://huggingface.co/BAAI/bge-large-en/tree/main?clone=true` 克隆 / 下载的模型文件，务必确保大文件内容没有缺失。

**Comment by TangJiakai** [comment]
我都按照说明走了，一样也是报错这个
