### ISSUE TITLE
Re-ranker fine tuning CUDA out of memory error

### ISSUE THREAD

**Issue by sroy-forr** [FlagOpen/FlagEmbedding#293]
I am trying to finetune re-ranker using a relatively small corpus (10k) but I receive CUDA out of memory error. I tried reducing batch size but it didn't work. Before I had no issues tuning any bge embedding models. Below is my instance type

<img width="949" alt="image" src="https://github.com/FlagOpen/FlagEmbedding/assets/98828692/7a5538a0-9ad4-496b-85e3-c677e8108d0e">

Using torch==1.13.1 for nvcc build cuda_11.8.r11.8/compiler.31833905_0

This is the error that I am getting.
<img width="1107" alt="image" src="https://github.com/FlagOpen/FlagEmbedding/assets/98828692/df5bdc7a-7872-4a58-a2c3-ae923fd4ffd7">

Run command:
`!torchrun --nproc_per_node 4 \
-m FlagEmbedding.reranker.run \
--output_dir ./custom-cross-encoder/ \
--model_name_or_path BAAI/bge-reranker-base \
--train_data ./corpus_minedHN_reranker.jsonl \
--learning_rate 1e-4 \
--fp16 \
--num_train_epochs 10 \
--per_device_train_batch_size 8 \
--gradient_accumulation_steps 4 \
--dataloader_drop_last True \
--train_group_size 8 \
--max_len 512 \
--weight_decay 0.01 \
--logging_steps 10 `

Appreciate any help! TIA

**Comment by staoxiao** [comment]
You can use deepspeed and grandient_checkpointing to further reduce the memory cost. The usage is the smae as embedding: https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune#3-train
```
--deepspeed ./df_config.json (df_config.json can refer to [ds_config.json](https://github.com/FlagOpen/FlagEmbedding/blob/master/examples/finetune/ds_config.json))
--gradient_checkpointing
```

**Comment by sroy-forr** [comment]
Thanks for the quick response. I now get a new error. Can you suggest on this?

![image](https://github.com/FlagOpen/FlagEmbedding/assets/98828692/f4c4009a-87f2-4047-9301-5fe395e6fa84)

**Comment by staoxiao** [comment]
The error seems to be related to DeepSpeed. Maybe there are some useful information in deepspeed repo: https://github.com/microsoft/DeepSpeed
