### ISSUE TITLE
ReRanker训练时label为什么全为0

### ISSUE THREAD

**Issue by LaoWangGB** [FlagOpen/FlagEmbedding#297]
https://github.com/FlagOpen/FlagEmbedding/blob/1c682c38b55c811aead2118d158b68c416970c67/FlagEmbedding/reranker/modeling.py#L26C19-L26C24
Dataset的第一个样本是正样本，为什么label还是0

**Comment by wjx-git** [comment]
> https://github.com/FlagOpen/FlagEmbedding/blob/1c682c38b55c811aead2118d158b68c416970c67/FlagEmbedding/reranker/modeling.py#L26C19-L26C24 Dataset的第一个样本是正样本，为什么label还是0

你好，这个问题阁下似乎已经懂了，但我还没明白，能请教下吗。

**Comment by LaoWangGB** [comment]
https://github.com/FlagOpen/FlagEmbedding/blob/0c8ea888c5d8a09354ea47a30f78b5b8a0d318db/FlagEmbedding/reranker/data.py#L51
在构建dataset时，batch中每个样本包含了一个匹配句子对和groupsize-1个不匹配的句子对，计算损失时相当于把每个样本进行一个多分类，每个样本匹配的句子对都在第0位，所以每个样本的label都是0.

**Comment by staoxiao** [comment]
> > https://github.com/FlagOpen/FlagEmbedding/blob/0c8ea888c5d8a09354ea47a30f78b5b8a0d318db/FlagEmbedding/reranker/data.py#L51
> > 
> > 在构建dataset时，batch中每个样本包含了一个匹配句子对和groupsize-1个不匹配的句子对，计算损失时相当于把每个样本进行一个多分类，每个样本匹配的句子对都在第0位，所以每个样本的label都是0.
> 
> 您好，想请教下，如果是把一个group的sample看作多分类来计算loss的话，负样本在计算的时候都为0了，那有没有负样本还有什么意义呢，希望您有空了回复一下，感谢～

交叉熵分类损失会对所有分数计算softmax，负样本的分数会在分母上，计算loss时只取出softmax后正样本的概率，提升他的分数（相当于要减小分母上的负样本）。

**Comment by MowanHu** [comment]
感谢您的回复！

從我的iPhone傳送

staoxiao ***@***.***> 於 2024年2月7日 23:24 寫道：

﻿

https://github.com/FlagOpen/FlagEmbedding/blob/0c8ea888c5d8a09354ea47a30f78b5b8a0d318db/FlagEmbedding/reranker/data.py#L51

在构建dataset时，batch中每个样本包含了一个匹配句子对和groupsize-1个不匹配的句子对，计算损失时相当于把每个样本进行一个多分类，每个样本匹配的句子对都在第0位，所以每个样本的label都是0.

您好，想请教下，如果是把一个group的sample看作多分类来计算loss的话，负样本在计算的时候都为0了，那有没有负样本还有什么意义呢，希望您有空了回复一下，感谢～

交叉熵分类损失会对所有分数计算softmax，负样本的分数会在分母上，计算loss时只取出softmax后正样本的概率，提升他的分数（相当于要减小分母上的负样本）。
