### ISSUE TITLE
C-MTEB部分数据集评测分数为0

### ISSUE THREAD

**Issue by izhx** [FlagOpen/FlagEmbedding#3]
刚开始跑评测，发现 TNews 和 IFlyTek 的分数是 0，hf hub上看 test label 全是 -1，这个是数据上传的问题吗？

```
INFO - mteb.evaluation.MTEB : Evaluation for TNews on test took 41.18 seconds
INFO - mteb.evaluation.MTEB : Scores: {'accuracy': 0.0, 'f1': 0.0, 'accuracy_stderr': 0.0, 'f1_stderr': 0.0, 'main_score': 0.0, 'evaluation_time': 41.18}
```

waimai 等其他数据 test label 都是正常的，我自己评测也正常有分数。

https://huggingface.co/datasets/C-MTEB/TNews-classification
https://huggingface.co/datasets/C-MTEB/IFlyTek-classification

**Comment by staoxiao** [comment]
您好，TNews 和IFlyTek 数据集使用的是validation split， text split上目前没有label

**Comment by izhx** [comment]
> 了

奥我知道了，我手动指定的，我代码是仿着mteb 判断 msmaco 然后指定，我改一下。

这样的数据还有吗？除了这两个

**Comment by staoxiao** [comment]
eval_splits参数可以不用传递，执行默认的测试逻辑
可以参考：https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py

**Comment by izhx** [comment]
好的。我改一下我的脚本，cmteb不传。
mteb那面 eval_splits 会有多个，指定一下好一些。
