### ISSUE TITLE
关于预训练和微调数据量的问题

### ISSUE THREAD

**Issue by EliverQ** [FlagOpen/FlagEmbedding#30]
您好！非常棒的工作！我很好奇你们在预训练和微调阶段使用数据量的情况，我看你们说英文微调语料大致在230M，请问这些语料是全都训完了或者甚至训了多个epoch，还是说训的时候只使用了部分呢？以及预训练阶段模型见过的数据量大概是多少呢？

**Comment by staoxiao** [comment]
您好，中英文都大致训练了3个epoch左右。预训练阶段跑了18w steps。
