### ISSUE TITLE
C-MTP (unlabeled) 的组成

### ISSUE THREAD

**Issue by liuqi6777** [FlagOpen/FlagEmbedding#301]
请问C-MTP的数据中，MISC项大致包括哪些数据呢，例如MLQA，MQA这些公开的多语言问答数据集中的中文部分，以及其他公开中文问答数据集等，有没有包含在内呢？

**Comment by staoxiao** [comment]
不包括。主要是来自中文问答网站，中文文献的数据。

**Comment by staoxiao** [comment]
是的
