### ISSUE TITLE
Reranker训练问题

### ISSUE THREAD

**Issue by chiosChen** [FlagOpen/FlagEmbedding#304]
您好，想请教有关reranker训练的问题。

下游任务：历史相似对话检索
模型结构：cross-encoder
数据：清洗后的gpt生成的数据，2000条

1. 如果在bge reranker的基础上微调，需不需要加入bge reranker的预训练数据，像t2reranking之类，很担心数据分布不同导致效果差
2. bge reranker的基座模型是xlm roberta，似乎并不是中文任务的最优选。如果拿中文bert重新训，2000条数据是不是不太够？可不可以模仿bge-reranker先用公开数据集（和最终下游任务分布不同）训练，然后再用任务数据微调。
3. 哪里可以找到bge-reranker训练阶段的参数信息

感谢！

**Comment by staoxiao** [comment]
1. 不需要加入预训练数据，训练数据中没有和您任务相似的数据。如果想保留reranker在其他领域的效果，融合reranker和微调后模型的权重即可，参考：https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/reranker#3-model-merging-via-lm-cocktail
2. 2k数据基本够训练，但先使用其他数据预训练可能效果会更好。
3. train_group_size=16, max_epoch=2, lr=5e-5, batch_size=6*16GPU=96

**Comment by chiosChen** [comment]
感谢您的回复
