### ISSUE TITLE
LM_Cocktail 融合后丢失sentence_transformers的配置

### ISSUE THREAD

**Issue by YanshekWoo** [FlagOpen/FlagEmbedding#311]
LM_Cocktail做参数融合融合的确是一个提升泛化性简单有效的方法，在我们自己的测试下也很有效。
我们在使用中发现mix_models是通过huggingface的save_pretrained存储的，这样会导致sentence_transformers的配置在新模型下是没有的（例如：modules.json、1_Pooling）
对于这一点有什么好的处理方式吗？你们未来会考虑修复吗？

另外也是提醒一下融合后用sentence_transformers做推理的朋友们，因为bge是cls的pooling，用sentence_transformers会默认加mean pooling，会导致效果显著下降。并且这过程是不会报错的只有一个warning，使用sentence_transformers需注意

**Comment by staoxiao** [comment]
您好，代码已更新，默认会存储成sentence_transformers格式
参考：https://github.com/FlagOpen/FlagEmbedding/issues/299

**Comment by YanshekWoo** [comment]
> 您好，代码已更新，默认会存储成sentence_transformers格式 参考：#299

OK，感谢您的回复和帮助，期待你们项目更多优秀的改进

**Comment by YanshekWoo** [comment]
> 您好，代码已更新，默认会存储成sentence_transformers格式 参考：#299

提醒下你们mix_models_with_data这个方法好像没有加？
