### ISSUE TITLE
为什么  bge-reranker  示例代码 compute 的分数范围跟  huggingface  中的 API  接口不一样？

### ISSUE THREAD

**Issue by dimsky** [FlagOpen/FlagEmbedding#312]
请问为什么 huggingface 上的API  接口 compute  后的分数范围在  0-1  之间？而调用 示例代码的 分数范围 却在负数与正数之间？

![demo1](https://github.com/FlagOpen/FlagEmbedding/assets/3078485/9ef2264a-6533-4d68-afa2-4cd584252567)

``` python
from FlagEmbedding import FlagReranker
reranker = FlagReranker('BAAI/bge-reranker-large', use_fp16=False) # Setting use_fp16 to True speeds up computation with a slight performance degradation

score = reranker.compute_score(['我喜欢你', '我爱你'])
print(score)


```
6.107391834259033

如何使用才能跟 huggingface  中 api返回的分数范围一样？

**Comment by CreationLee** [comment]
> huggingface应该是在分数后面加了个sigmoid，如果想要映射到0-1，可以加上sigmoid函数。

加上了，normalize=True也试了，但是有的情况下，还是会出现大于1的情况
