### ISSUE TITLE
cannot reproduce the results of TRECCOVID

### ISSUE THREAD

**Issue by SeanLee97** [FlagOpen/FlagEmbedding#313]
We utilized the official pretrained weight (BAAI/bge-large-en-v1.5) and employed the official MTEB evaluation script to assess the retrieval performance. However, we observed that our TRECCOVID result was comparatively lower than the reported result.

The reported result is `74.82` (ndcg_at_10). While our reproduction result is `64.40`. Our detailed results are as follows:

```
Scores: {'ndcg_at_1': 0.64, 'ndcg_at_3': 0.66788, 'ndcg_at_5': 0.66584, 'ndcg_at_10': 0.64403, 'ndcg_at_100': 0.47785, 'ndcg_at_1000': 0.42963, 'map_at_1': 0.00186, 'map_at_3': 0.00538, 'map_at_5': 0.00877, 'map_at_10': 0.01544, 'map_at_100': 0.07993, 'map_at_1000': 0.19076, 'recall_at_1': 0.00186, 'recall_at_3': 0.0058, 'recall_at_5': 0.00986, 'recall_at_10': 0.01814, 'recall_at_100': 0.11678, 'recall_at_1000': 0.40031, 'precision_at_1': 0.68, 'precision_at_3': 0.70667, 'precision_at_5': 0.712, 'precision_at_10': 0.688, 'precision_at_100': 0.4908, 'precision_at_1000': 0.1891, 'mrr_at_1': 0.68, 'mrr_at_3': 0.79333, 'mrr_at_5': 0.80233, 'mrr_at_10': 0.80817, 'mrr_at_100': 0.80817, 'mrr_at_1000': 0.80817, 'evaluation_time': 2582.9}
```

Could you give us any advice to help us reproduce the results?

**Comment by staoxiao** [comment]
The official MTEB evaluation script cannot add instruction for query, so the performance will be lower than reported. 
You can use our script to reproduce the results: https://github.com/FlagOpen/FlagEmbedding/tree/master/C_MTEB#evaluate-embedding-model

**Comment by SeanLee97** [comment]
@staoxiao, thanks. It works fine following your instructions.
