### ISSUE TITLE
请问有没有提高bge-reranker推理速度的方法呢？

### ISSUE THREAD

**Issue by CanIbeyourdog** [FlagOpen/FlagEmbedding#324]
您好，我在一个8卡服务器上用bge-ranker模型对20条数据做重排时，大概要花9秒，请问是正常的吗？已经设置use_fp16为True了，另外问一下有没有其余的提升重排速度的方法呢？谢谢！

**Comment by staoxiao** [comment]
20条数据不需要使用多卡，单卡即可一次推理完。多卡反而会因为通信开销变得更慢。
可以使用更小版本的reranker模型；如果您的输入不长，可以减小max_length；可将模型转为onnx等形式提高速度；如果有大量数据，可以使用dataloader加载数据，减少tokenizer的时间。

**Comment by CanIbeyourdog** [comment]
> 20条数据不需要使用多卡，单卡即可一次推理完。多卡反而会因为通信开销变得更慢。 可以使用更小版本的reranker模型；如果您的输入不长，可以减小max_length；可将模型转为onnx等形式提高速度；如果有大量数据，可以使用dataloader加载数据，减少tokenizer的时间。

感谢您的回复！您的办法很有用，我试了一下单卡推理，延迟降低到0.15s左右了，我想问一下大概什么规模的数据才用得到多卡呢？

**Comment by staoxiao** [comment]
当你的数据大到一张卡一次性推理不了的时候，可以用多卡。如果一张卡能吃下，就不建议用多卡。

**Comment by CanIbeyourdog** [comment]
好的，非常感谢！

> 当你的数据大到一张卡一次性推理不了的时候，需要分很多次分别推理的时候，可以用多卡并行推理。如果一张卡能吃下，就不建议用多卡。

**Comment by flyme2023** [comment]
可以通过onnx或者trt来提速，相关代码参考：https://github.com/flyme2023/bge

**Comment by chuangzhidan** [comment]
> 可以通过onnx或者trt来提速，相关代码参考：https://github.com/flyme2023/bge

哪个脚本可以加速比如bge-m3，没有readme，不是很易读
