### ISSUE TITLE
encode函数，是否可以提供一个to_device的parameter呢？

### ISSUE THREAD

**Issue by blablahaha** [FlagOpen/FlagEmbedding#327]
Hey 非常感谢提供了一个很棒的Embedding Model

在使用的过程中，发现encode函数，会强制`.cpu().numpy()`

针对比较大的推理矩阵，这样即使后续使用  `torch.from_numpy(embeddings_1).to('cuda')`，也会导致比较大的I/O开销，因此希望提供一个`to`的parameter，来决定向量的存储位置。

**Comment by staoxiao** [comment]
感谢建议！
使用sentence transformers的话，可以设置convert_to_numpy=False。
目前也为FlagModel新增了convert_to_numpy参数，设置为False的话，不会调用cpu().numpy。

**Comment by blablahaha** [comment]
非常感谢您的及时回复，想请问下，新的Code 什么时候会更新至PyPI上呢？

**Comment by staoxiao** [comment]
可以通过git clone的方式安装，这样是最新的代码：https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune#1-installation

Pypi上的安装包我们近期会进行更新。
