### ISSUE TITLE
能否开放api服务,给其他应用调用.

### ISSUE THREAD

**Issue by guyuexue** [FlagOpen/FlagEmbedding#33]
例如: https://github.com/shibing624/text2vec/blob/master/examples/fastapi_server_demo.py

**Comment by staoxiao** [comment]
感谢您的建议，后续会考虑增加此功能。
如果想要所给示例的代码那样运行，您只需要将
```
from text2vec import SentenceModel
```
换成
```
from FlagEmbedding import FlagModel as SentenceModel
```
应该就能运行
