### ISSUE TITLE
关于微调reranker的问题

### ISSUE THREAD

**Issue by Zhangtiande** [FlagOpen/FlagEmbedding#330]
如果我要对于多个近似实体的全称和缩写进行匹配，假设有一个集团下多个子公司的名称全称和缩写，但多个子公司的名称十分接近，我在构建某个子公司负样本的时候，是否要把其他子公司的句子放入。
负样本代表不相关，这里的不相关有什么依据吗，还是说随意找几个句子？
十分感谢。

**Comment by staoxiao** [comment]
您好，视需求而定。如果需要让模型区分不同的子公司的名称，可以把他们作为负样本。
