### ISSUE TITLE
问答检索相关

### ISSUE THREAD

**Issue by gggdroa** [FlagOpen/FlagEmbedding#331]
想使用bge模型将文章段落文本转为embedding，**目的是想做到：如果用户输入一个问题，他能返回相关的文章段落。**
使用下面方法，返回的结果不是答案，是该问题相似句子。是哪里用错了吗？还是这个做不了相关功能呀？
![image](https://github.com/FlagOpen/FlagEmbedding/assets/106646583/a406bd89-de56-4bb2-8455-3426c243de84)
![image](https://github.com/FlagOpen/FlagEmbedding/assets/106646583/db01c044-2818-4e25-9149-d9e9ff4236e7)
![image](https://github.com/FlagOpen/FlagEmbedding/assets/106646583/7fea73a4-8e78-4b70-a06b-a7fb75173fa7)

**Comment by gggdroa** [comment]
检索代码部分：
![image](https://github.com/FlagOpen/FlagEmbedding/assets/106646583/e3560131-726b-4fd5-913c-255039afd691)

**Comment by staoxiao** [comment]
您好，我觉得这个结果么有问题，这个句子完全包含了query，相似度本就应该很大。
问题在于这个相关的句子里只有query，没包含其他信息，如果截断时截的更长一些让其包含了相关信息就没问题了。
所以如果要检索有答案的锻炼，建议做法是将这种无意义的标题、短句这类的从候选集里删除。

**Comment by gggdroa** [comment]
> 您好，我觉得这个结果么有问题，这个句子完全包含了query，相似度本就应该很大。 问题在于这个相关的句子里只有query，没包含其他信息，如果截断时截的更长一些让其包含了相关信息就没问题了。 所以如果要检索有答案的段落，建议做法是将这种无意义的标题、短句从候选集里删除。

好的感谢回复   那其实我这样做问答检索是正确的哈？只不过因为本身数据集未做处理，导致这样的结果

**Comment by staoxiao** [comment]
是的。

**Comment by gggdroa** [comment]
> 是的。

好的 谢谢你
