### ISSUE TITLE
对于高并发场景如何部署embedding模型

### ISSUE THREAD

**Issue by LCorleone** [FlagOpen/FlagEmbedding#335]
bge embedding部署的时候，对于高并发场景，有什么部署的方案可以参考吗

**Comment by LeeJodie** [comment]
同问

**Comment by staoxiao** [comment]
这块我们没有太多建议。可以参考一些社区的部署：https://github.com/huggingface/text-embeddings-inference, https://github.com/qdrant/fastembed
