### ISSUE TITLE
怎么改变模型加载的gpu呢

### ISSUE THREAD

**Issue by vmn171** [FlagOpen/FlagEmbedding#341]
我有两个显卡，使用的是FlagModel，默认是加载到了第一个显卡上，但第一个显卡不够用了。怎么让他加载到第二个卡上呢？强制去改了FlagModel类中init的self.device。好像也不起作用。

**Comment by staoxiao** [comment]
可以在程序前设置
`os.environ["CUDA_VISIBLE_DEVICES"]="1"`, 这样只会使用第二张卡

**Comment by vmn171** [comment]
谢谢，这样也行
