### ISSUE TITLE
[Instructions] Any other query instructions for other tasks?

### ISSUE THREAD

**Issue by jlia0** [FlagOpen/FlagEmbedding#35]
Are there other instructions for tasks like clustering/classification demonstrated in the [Instructor Embedding](https://instructor-embedding.github.io/)?

![image](https://github.com/FlagOpen/FlagEmbedding/assets/24471281/9cd77ec2-3a03-4428-bd55-25dfbd24db2f)

**Comment by jlia0** [comment]
Thank! How can we use BGE models for other tasks then?

**Comment by staoxiao** [comment]
Just input the original text and use the generated embedding for other tasks.
