### ISSUE TITLE
Some questions about fine-tuning CrossEncoder

### ISSUE THREAD

**Issue by XChen-Zero** [FlagOpen/FlagEmbedding#355]
It's an amazing job!
Any experience fine-tuning CrossEncoder on domain data, such as which layers of parameters to tune? 
Or is there any paper on it? 
Looking forward to your reply!

**Comment by staoxiao** [comment]
Since the model is not very large, we suggest to fine-tune all parameters. You can refer to https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/reranker for an example.

**Comment by XChen-Zero** [comment]
Thanks
