### ISSUE TITLE
请问一下BAAI/bge-large-zh-v1.5的问题

### ISSUE THREAD

**Issue by zysNLP** [FlagOpen/FlagEmbedding#359]
请问你们BAAI/bge-large-zh-v1.5训练的数据的规模有多少，感谢

**Comment by staoxiao** [comment]
无监督数据：https://data.baai.ac.cn/details/BAAI-MTP
微调数据：参考https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/baai_general_embedding#frequently-asked-questions     和https://arxiv.org/pdf/2309.07597.pdf
总共1亿多条。

**Comment by zysNLP** [comment]
好的，谢谢
