### ISSUE TITLE
[finetune]对文档检索任务应该怎么调优

### ISSUE THREAD

**Issue by kouhigh55** [FlagOpen/FlagEmbedding#36]
想要提高模型文档检索能力。请问是要在finetune时，给三元组数据集的query添加instruction吗？

**Comment by staoxiao** [comment]
是的，建议加上。

**Comment by staoxiao** [comment]
> @staoxiao, If it is recommended to add instruction to the queries when fine-tuning bge for document retrieval task, then it would be great if we can update it [data format mentioned in the README.md](https://github.com/FlagOpen/FlagEmbedding/blob/master/examples/finetune/README.md#data-format).

Hi, if you want to add instruction, you can add it to the text in training data json file, 
and note that use your instruction as the value of argument `query_instruction_for_retrieval`, otherwise set `query_instruction_for_retrieval=""`.

**Comment by Yyy11181** [comment]
那如何添加query_instruction_for_retrieval=""这个参数呢？

**Comment by nanyoullm** [comment]
应该是，query数据不加instruction，微调时加上参数 ```--query_instruction_for_retrieva “xxx”```
或者
数据加instruction，微调不加参数 ```--query_instruction_for_retrieva```
@staoxiao 是这样吗

**Comment by staoxiao** [comment]
> 

是的，目前给训练脚本加上了query_instruction_for_retrieval参数，可以直接通过这个参数设置，不必在数据中手动增加了
