### ISSUE TITLE
关于negatives_cross_device的疑问

### ISSUE THREAD

**Issue by zhaobinNF** [FlagOpen/FlagEmbedding#37]
请问设置了negatives_cross_device之后，会出现其他device上的example的negatives恰好是当前device上的pos这种情况吗，这会对模型的学习造成一定影响吗

**Comment by staoxiao** [comment]
negatives_cross_device只是对In-batch negatives的扩充。In-batch negatives是有可能会出现您说的伪负例的情况的，其他query的负样例是该query的正样本，但在数据量大的情况下出现的概率较小，影响可以忽略。

**Comment by KeepGoingCSU** [comment]
> 充。In-batch negatives是有可能会出现您说的伪负例的情况的，其他query的负样例是该query的正样本，但在数据量大的情况下出现的概率较小，影响可以忽略。

请问我做bge-m3的finetune，训练数据是领域内的分类任务，样本示例：
