### ISSUE TITLE
了解到Bge当前最大输入tokens数量是512，请问有没有什么方法可以判断传给bge模型的文本token是否超出512

### ISSUE THREAD

**Issue by TChengZ** [FlagOpen/FlagEmbedding#370]
如题。
在给bge喂数据的时候希望能够有个前置的检测tokens数量，是否有方法（比如api，sdk之类）的方式来判断输入文本的token量

**Comment by staoxiao** [comment]
可以通过一下方式判断输入的token数量，注意目前超过512的会被截断。
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-large-zh-v1.5')
input_l = len(tokenizer.encode("hello"))
```

**Comment by TChengZ** [comment]
AutoTokenizer

> 可以通过一下方式判断输入的token数量，注意目前超过512的会被截断。
> 
> ```
> from transformers import AutoTokenizer
> tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-large-zh-v1.5')
> input_l = len(tokenizer.encode("hello"))
> ```

AutoTokenizer 这个要如何安装呢？

**Comment by staoxiao** [comment]
> AutoTokenizer
> 
> > 可以通过一下方式判断输入的token数量，注意目前超过512的会被截断。
> > ```
> > from transformers import AutoTokenizer
> > tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-large-zh-v1.5')
> > input_l = len(tokenizer.encode("hello"))
> > ```
> 
> AutoTokenizer 这个要如何安装呢？

pip install transformers
