### ISSUE TITLE
关于FineTune

### ISSUE THREAD

**Issue by BrownTen** [FlagOpen/FlagEmbedding#38]
您好，由于我是该相关领域中的新手，我想请教一些可能比较基础简单的问题

当我想在您BGE-small的模型基础上fine-tune自己的模型的时候
1. 如果在我的conda环境中已经配置好了sentence-transformers及相关环境（pytorch等），按照Readme中的介绍，Installation步骤中，我是否还需要安装FlagEmbedding，以及执行pip install . 或 pip install -e . 安装setup.py中的内容。
2. 在fine-tune数据上，我使用了您提供的example里的json文件，我是否只需要在pycharm，Run中配置Train中提示的相关参数。或者在linux系统中，直接执行Train中提示的运行脚本。在这些参数配置中，如果我没有GPU，是否只需要去除第一行和negatives_cross_device 的参数，即可？
3. 我按照第2点的想法，在pycharm上Run了run.py，在当前目录下得到了一个temp的文件夹，里面包含若干checkpoint文件夹，及模型相关文件(config.json、pytorch_model.bin等)，请问我需要如何获取自己的model，我尝试了SentenceTransformers(./temp)。但是他提示了找不到模型。

非常感谢您能够拨冗回复解答我的疑惑。

**Comment by BrownTen** [comment]
感谢您的回复，我已经在本地简单尝试了finetune的使用方法。感觉非常的Nice。
另外关于第3点，并不是路径写错了，经过网上的搜索，说[是一个Warning警告，可以忽略](https://blog.csdn.net/qq_49874815/article/details/124412048)

此外还有2个问题，想要请教一下：

1. 如果我的远程服务器上，是无网络环境 或者 网络环境较差，在fine-tune的时候，我看到是要去Download指定的bge模型（例如bge-small-en），这时候下载非常缓慢，甚至会中断。我是否可以从其他地方获取该模型，然后上传到服务器。在服务器上fine-tune的时候 或 直接使用bge模型的时候 使用本地的文件呢？

2. 我看到了您在readme中提供了pretrain和finetune两种方法 以及 您在#26中的回复，我不太清楚在bge的基础上进行pretrian和finetune的区别

> 我的理解是：对于我想定制化自己相关任务的模型的时候，

- 一般来说是只需要在bge的基础上加上我的相关任务的一些数据进行finetune就可以了吧（高效，简单，便捷）。
- 但如果我想在我自己的任务上，取得更好的成绩，让模型有更好的表示能力，就是需要我的任务中的大量数据，在bge上进行pretrain，然后针对hard sample进行finetune（效率较低，结果较好），是这样吗。
- 然后在pretrian中的data ：{‘text’:str} 是指的 {‘query’: passages} 吗？

**Comment by staoxiao** [comment]
关于路径的问题，如果是这个警告的话，说明文件里没有sentence-transformer的文件，您可以从bge模型里复制一份过去。
或者加载的时候指明使用CLS pooling，不然sentence-transformer会默认使用mean pooling，可参考如下方式：
```
from sentence_transformers import SentenceTransformer, models

word_embedding_model = models.Transformer(your_ckpt_path, max_seq_length=512, do_lower_case=True)
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(), pooling_mode='cls')
model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
```

1. 下载文件：
hugginface会自动下载到本地，下次加载时会自动加载本地的。
如果想要手动下载，可以从：https://huggingface.co/BAAI/bge-base-en/tree/main  选择文件点击下载图标进行下载
或者使用git lfs: https://huggingface.co/BAAI/bge-base-en/tree/main?clone=true

2. 是的。pretrain中不需要文本对，数据中的text单纯指一段文本，这段文本可以来自于您的passage和query。
```
{"text": passage_1}
{"text": passage_2}
```
