### ISSUE TITLE
文本长度和相似度的关系

### ISSUE THREAD

**Issue by xuyungit** [FlagOpen/FlagEmbedding#41]
使用Embedding模型实现一个文档检索应用，文档按照语义段落结构进行切割，因此有一些切片大一些，有一些切片的文字少。使用bge模型编码时，发现字数少的切片经常相似度更高，哪怕文字多的切片从语义上更加相关。而使用OpenAI的embedding似乎没有这个问题。请问有什么优化的方法吗？

**Comment by staoxiao** [comment]
OpenAI的最大长度限制和embedding维度都更大，对长文本会更友好。
对于该任务，建议对查询加上指令，以更好的匹配长文本。使用时，尽量避免长文本超过当前模型的最大长度限制：512。候选集文档长度差距不要太大，可以对极端文本进行进一步处理。

**Comment by xuyungit** [comment]
好的，我尝试减少长文本的长度，同时拼接太短的文本，谢谢！

**Comment by wuhenbai** [comment]
> 
针对长文本，那是不是用1024维度的会比768维度的效果更好？

**Comment by staoxiao** [comment]
> > 
> 
> 针对长文本，那是不是用1024维度的会比768维度的效果更好？

是的

**Comment by staoxiao** [comment]
> > 
> 
> 训练的时候，数据是不是绝大部分都是短文本？因为我看batchsize非常大

训练的时候开启了gradient_checkpointing和deepspeed，并且截断至了200个token，所以batch size开的比较大。

**Comment by runvyang** [comment]
如果截断到200个token, 那么超过200个token是不是就被模型忽略了？（我记得有个地方说是absolute positioning，这个应该缺乏外插能力）
