### ISSUE TITLE
请问在微调的过程中，数据会打乱吗？

### ISSUE THREAD

**Issue by NLPJCL** [FlagOpen/FlagEmbedding#43]
您好，咨询一下几个问题。感谢您的回答！
1.看代码好像每个epoch并没有打乱数据。请问下是否代码支持打乱呢，如何实现。
2.不打乱数据，是不是batch内负采样见到的负例就会少一点？

**Comment by staoxiao** [comment]
您好，
1. 支持打乱的，代码使用的是huggingface 的trainer模块，会自动使用randomsampler或者distributedsampler，其会随机选取数据组成batch。
2. 不打乱的话，每次的batch内负样本都会是固定的，不会变化。
