### ISSUE TITLE
bge-m3 调用README有误

### ISSUE THREAD

**Issue by Gladiator566** [FlagOpen/FlagEmbedding#433]
max_length这个参数在初始化BGEM3FlagModel时是没有的，应该是在encode方法里面，否则执行样例代码的时候会报错 `TypeError: __init__() got an unexpected keyword argument 'max_length'`

![image](https://github.com/FlagOpen/FlagEmbedding/assets/22348637/e6d00a94-4f31-4722-b0d0-7b47be465a68)
![image](https://github.com/FlagOpen/FlagEmbedding/assets/22348637/02484b3c-9696-4368-bb10-ed08bc0eda86)

**Comment by staoxiao** [comment]
感谢反馈！已更新readme。
