### ISSUE TITLE
Comparision of bge-m3 with bge-small and bge-large 

### ISSUE THREAD

**Issue by mlkorra** [FlagOpen/FlagEmbedding#436]
Thanks for sharing your latest work  (bge-models), i took a look at the paper shared, I haven't found any results comparing bge-m3 to the past bge models, can you point me to the right resource ,if I ain't looking in the right direction.

**Comment by staoxiao** [comment]
Thanks for your interest in our work!
bge-m3 is a multilingual model, while past bge models only support one language (English or Chinese) that cannot be tested in a multilingual evaluation dataset, so we haven't evaluated the performance of past bge models in our paper.

**Comment by mlkorra** [comment]
Thanks for the reply, Yes, that makes sense, btw your work on bge-models has shown significant results in one of the retrieval components I was working on, keep doing the awesome work.
