### ISSUE TITLE
why requirement of "transformers" is specified to transformers==4.33.0

### ISSUE THREAD

**Issue by wxywb** [FlagOpen/FlagEmbedding#441]
it could easily get conflict with other library's prerequisite, could it get a looser dependency like transformers >=4.33.0?

https://github.com/FlagOpen/FlagEmbedding/blob/a591096893927eb0c34fc5baf6534b1878d571ae/setup.py#L17

**Comment by staoxiao** [comment]
Thanks for your interest in our work!
The trainer code for different versions of transformers is always changing, and new transformers may cause issues with the fine-tuning code for BGE. Taking this into consideration, we set a fixed version for transformers. However, in practice, there are no restrictions on the transformers version for the inference code.

We will set a looser dependency in setup.py and instead provide a reminder in the fine-tuning code.
