### ISSUE TITLE
关于复现BGE-M3论文中nDCG@10的结果

### ISSUE THREAD

**Issue by ddddddreamcastle** [FlagOpen/FlagEmbedding#445]
我的实验流程如下（以miracl-zh数据和dense方式为例）：
1. 读取huggingface miracl-v1.0-zh的topics和qrels，将里面所有的query读取成python的list，将里面所有query对应的positive_passages和negative_passages读取进python的list。
2. 再使用
  `querys_vec = model.encode(querys)['dense_vecs']
    docs_vec = model.encode(docs)['dense_vecs']`
将二者转换成向量。
3. 计算相似度：`querys_vec @ docs_vec.T`
4. 第3步就得到了query和docs的两两相似矩阵，对每一个query，用scikit-learn提供的ndcg@10计算结果。
5. 最后对所有query的值取一个平均。

想请问作者，我的流程是否有问题？还是使用的数据不对？(我用 train/dev 分别都试了一下)。  但我无法复现论文里面的结果。 例如：文中Table2，zh列，M3-Embedding Dense，论文中的结果是61.7，我得到的结果是80.2 。

**Comment by hanhainebula** [comment]
您好，您的实验流程中的第一步有些问题，应该从相应语言的 [corpus](https://huggingface.co/datasets/miracl/miracl-corpus) 中进行搜索，而不是直接使用 query 对应的 positive_passages 和 negative_passages 作为搜索结果。
我们测试时参考的是 [MIRACL 官方](https://github.com/project-miracl/miracl)给出的评测方法，使用 Pyserini 在 MIRACL 的 dev 集上进行评测。以在 zh 上评测 dense 为例，评测流程如下：
1. 使用 dense 为相应的 zh corpus 生成 embeddings，利用 faiss 建立 index 并保存；
2. 为每条 query 检索出 Top-1000  的结果并保存，具体方法：使用 Pyserini 的 `FaissSearcher` (`from pyserini.search.faiss import FaissSearcher`) 加载第一步建立好的 index，对 zh queries 进行搜索；
3. 利用 qrels 以及第二步检索出的结果进行评测，具体方法为：使用 Pyserini 的 `trec_eval` (`pyserini.eval.trec_eval`) 进行测试。

请注意第 1, 2 步的保存格式有一定要求，具体请参见 [Pyserini 的官方仓库](https://github.com/castorini/pyserini)。

**Comment by ddddddreamcastle** [comment]
@hanhainebula  感谢
