### ISSUE TITLE
微调数据咨询

### ISSUE THREAD

**Issue by Yyy11181** [FlagOpen/FlagEmbedding#45]
您好，可以通过问答的数据集来构建微调数据集吗？期待您的回答

**Comment by staoxiao** [comment]
您好，使用问答对训练模型是可以的

**Comment by Yyy11181** [comment]
好的 微调的数据类型中
{"query": str, "pos": List[str], "neg":List[str]}
，感谢您，可以多个negative 和多个positive吗？

**Comment by staoxiao** [comment]
可以的。
json文件中，`"pos": List[str]`， 是一个列表，里面可以包含多个positive文本
`"neg": List[str]`， 也是一个列表，里面可以包含多个negative文本。
可以参考给出的数据样例：https://github.com/FlagOpen/FlagEmbedding/blob/master/examples/finetune/toy_finetune_data.jsonl

**Comment by Yyy11181** [comment]
好嘞 谢谢您的解答
