### ISSUE TITLE
bge-m3 同样的text，lexical_weights返回不一致

### ISSUE THREAD

**Issue by realqnn** [FlagOpen/FlagEmbedding#453]
text_list 为['肯德基', '麦当劳']
print(model.convert_id_to_token(emb_query['lexical_weights']))
每次跑返回结果不一致，比如，
[{'': 0.3225, '肯': 0.2328, '德': 0.2847, '基': 0.0794}, {'': 0.4055, '麦': 0.7056, '当': 0.731, '劳': 0.841}]
[{'': 0.0365, '基': 0.0555}, {'': 0.05347, '当': 0.05267}]

想问下，这个地方是有什么随机丢词策略吗还是我的包版本或者模型不对
模型是在hf下载的，https://huggingface.co/BAAI/bge-m3/tree/main

**Comment by hanhainebula** [comment]
您好，方便贴一下运行代码吗？

**Comment by realqnn** [comment]
model = BGEM3FlagModel("../model/bge-m3", use_fp16=True)
 query = ['肯德基', '麦当劳']
emb_query = model.encode(query, batch_size=12, max_length=64, return_dense=True, return_sparse=True,
                             return_colbert_vecs=True)
print(model.convert_id_to_token(emb_query['lexical_weights']))

**Comment by hanhainebula** [comment]
您好，我这边测试每次跑出来的结果都是一样的，无论是在程序内使用循环运行多次，还是多次运行测试程序，出来的结果都是一样的，似乎没有遇到您遇到的问题。

**Comment by realqnn** [comment]
应该是我下载的bpe model文件损坏了，

**Comment by henryhu55** [comment]
![image](https://github.com/FlagOpen/FlagEmbedding/assets/128961310/cf837eb3-95d4-4732-b2f2-aa0b496cb8b7)
不会是忘记上传了吧，这个文件这么小吗

**Comment by ANYMS-A** [comment]
我这边用bge-large-zh-v1.5会出现lexical weights为空 是为什么呀？

**Comment by staoxiao** [comment]
@ANYMS-A , bge-large-zh-v1.5不支持lexical weights， 只有bge-m3支持
