### ISSUE TITLE
感觉准确度在60-70%左右，拿来排序，确实大多数都是准确的，但是头疼的是，时不时会冒出一堆毫不相干的内容。

### ISSUE THREAD

**Issue by zengzikang** [FlagOpen/FlagEmbedding#46]
用于搜索的话，还有待完善。最主要的是，这不相干的内容很可能排很前面，搞不懂原因。但是如果你单独生成两个向量去比对，他又每问题。

**Comment by staoxiao** [comment]
感谢反馈。
请问您是如何做的搜索，方便的话可以提供一下代码，如果和单独生成向量对比结果有区别的话，可能是检索的使用方式存在问题。

**Comment by zengzikang** [comment]
可提供源码及部分示例数据提供你们研究。有需要的话，可以发我联系方式，或者邮箱之类的。
具体细节详情：
1、首先将所有需要用于检索的字符串进行向量化，大约6个线程同时跑。
2、将字符串和向量存放到es中。
3、用es进行余弦相似度检索。

检索结果：
如之前所说，使用余弦相似度检索并按照分值排序，大部分可能都是没问题的，但是在这其中，会掺杂一些不相干的数据。
于是我去做了试验，我把检索和被检索的字符串向量化，然后对比用es检索出来的，从肉眼看上去明显不相干的数据对比，发现临时向量化计算的余弦相似度是准确的，而之前批量生成的向量计算的余弦相似度是不准的。
于是我就比对了两个向量，发现同样的字符串，他们的向量差的有点大，而哪些准确的检索结果的向量，差别就很小。这说明在批量向量化的过程中，部分字符串的向量化可能有问题。

环境：
1、批量向量化使用的是4090显卡。
2、执行检索使用的是2080ti。

对比了用两个环境生成的向量，生成的向量区别不大，会稍微有那么点区别。

**Comment by zengzikang** [comment]
另外补充点，就是那些很明显不相干的数据，他们的向量重新生成的话，大概率会变化很大。而那些准确的数据生成的向量，重新再生成一次，他们的变化通常很小。
基于这种情况，有必要的话，我打算对字符串进行2-3轮的向量化，然后几次的去对比，如果余弦相似度很接近，就说明生成大概率是准确的，如果发现余弦相似度差距大，则可能是不准确的，就继续把这批数据重新向量化。

**Comment by staoxiao** [comment]
> 可提供源码及部分示例数据提供你们研究。有需要的话，可以发我联系方式，或者邮箱之类的。 具体细节详情： 1、首先将所有需要用于检索的字符串进行向量化，大约6个线程同时跑。 2、将字符串和向量存放到es中。 3、用es进行余弦相似度检索。
> 
> 检索结果： 如之前所说，使用余弦相似度检索并按照分值排序，大部分可能都是没问题的，但是在这其中，会掺杂一些不相干的数据。 于是我去做了试验，我把检索和被检索的字符串向量化，然后对比用es检索出来的，从肉眼看上去明显不相干的数据对比，发现临时向量化计算的余弦相似度是准确的，而之前批量生成的向量计算的余弦相似度是不准的。 于是我就比对了两个向量，发现同样的字符串，他们的向量差的有点大，而哪些准确的检索结果的向量，差别就很小。这说明在批量向量化的过程中，部分字符串的向量化可能有问题。
> 
> 环境： 1、批量向量化使用的是4090显卡。 2、执行检索使用的是2080ti。
> 
> 对比了用两个环境生成的向量，生成的向量区别不大，会稍微有那么点区别。

了解了，您可以发送邮件至stxiao@baai.ac.cn

**Comment by zengzikang** [comment]
已发邮箱

**Comment by staoxiao** [comment]
> 另外补充点，就是那些很明显不相干的数据，他们的向量重新生成的话，大概率会变化很大。而那些准确的数据生成的向量，重新再生成一次，他们的变化通常很小。 

您可以将这块的示例发过来，理论上使用sentence-transformers库encode多条和一条文本不会有太大差别。
对于会检索出毫不相关的内容，大概率是检索设置或者向量生成设置的问题，本人对es不太了解，您需要自行检查一下。如果是检索精度不够高，可以尝试使用数据微调向量模型。

**Comment by yph0925** [comment]
> 另外补充点，就是那些很明显不相干的数据，他们的向量重新生成的话，大概率会变化很大。而那些准确的数据生成的向量，重新再生成一次，他们的变化通常很小。 基于这种情况，有必要的话，我打算对字符串进行2-3轮的向量化，然后几次的去对比，如果余弦相似度很接近，就说明生成大概率是准确的，如果发现余弦相似度差距大，则可能是不准确的，就继续把这批数据重新向量化。

这个问题解决了吗？是什么原因呢

**Comment by zengzikang** [comment]
> > 另外补充一点，就是那些很明显不相干的数据，他们的支持重新生成，大的概率会变化很多。而那些准确的数据生成的支持，重新再生成一次，他们的变化通常是靠谱的。种情况，有必要的话，我打算对字符串进行2-3轮的辅助化，然后几次去对比，如果余弦相似度很接近，就说明生成大概率是准确的，如果发现余弦相似度差距大，则可能是不准确的，就继续把这批数据重新进行化处理。
> 
> 这个问题解决了吗？是什么原因呢

代码问题，确实还是准的，不过感觉和分词对比差不多
