### ISSUE TITLE
想问一下困难负样本挖掘代码的细节问题

### ISSUE THREAD

**Issue by shtdbb** [FlagOpen/FlagEmbedding#464]
https://github.com/FlagOpen/FlagEmbedding/blob/db672e177083f25cbf44fe2d5d0ac91f02380726/FlagEmbedding/baai_general_embedding/finetune/hn_mine.py#L102-L103
这两行代码是当从向量数据库中召回的随机负例样本数量不足时，从`corpus`中随机选取句子补足成负例。
但是`corpus`中的句子既包含所有的正例、也包含所有负例，那随机选取会不会有可能把当前样本的`pos`中的句子选到当做负样本呢？或者把之前召回到的`neg`中已经有的句子又重复选取到呢？

**Comment by staoxiao** [comment]
会的。corpus比较大的话，选到pos的概率会很小。

**Comment by shtdbb** [comment]
> 会的。corpus比较大的话，选到pos的概率会很小。

若负例会选取到正例的句子，对微调效果会有影响吧？是不是避免选取到`pos`，然后尽量避免重复选取数据库之前召回的`neg`要好一些呢？

**Comment by staoxiao** [comment]
是的，避免选取pos和重复的neg会更好。

**Comment by shtdbb** [comment]
好的，谢谢
