### ISSUE TITLE
How does BGE-M3 use gradient checkpointing?

### ISSUE THREAD

**Issue by chansonzhang** [FlagOpen/FlagEmbedding#469]
I am reading the [BGE-M3 paper](https://arxiv.org/pdf/2402.03216.pdf) and noticed the following description.
> We iteratively encode each sub-batch using gradient checkpointing ([Chen et al., 2016](https://arxiv.org/abs/1604.06174)) and gather all generated embeddings.

As described in ([Chen et al., 2016](https://arxiv.org/abs/1604.06174)), gradient checkpointing is **_trade computation for memory_**.

So, I am wondering how exactly checkpointing is used in BGE-ME to **_iteratively encode each sub-batch and gather all generated embeddings_**?

**Comment by staoxiao** [comment]
Thanks for your interest in our work! We provided a pseudo code in Appendix B.3 of our paper. We enable the gradient checkpointing in https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/BGE_M3/modeling.py#L92, and encode via: https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/BGE_M3/modeling.py#L152

**Comment by chansonzhang** [comment]
@staoxiao Thanks for your detailed explanation, it's helpful.
