### ISSUE TITLE
相似度的归一化相比于OpenAI的Embedding差距还是不小的

### ISSUE THREAD

**Issue by aierwiki** [FlagOpen/FlagEmbedding#48]
好多非常匹配的问答对，分数上不去，没法用来做置信度，要投入生产环境还得再做个判断是否匹配的模型。。。。

**Comment by staoxiao** [comment]
不太清楚您说的相似度的归一化能力指什么。bge模型考虑了各种任务的通用性，问答对这种查询和候选文本存在差异的任务通常相似度不会很高，如果需要根据相似度阈值来进行筛选的，可以根据实际任务下的相似度分布来选择。

**Comment by aierwiki** [comment]
主要是BGE相似度打分在我们这个业务场景中分布规律并不明显，比如有的明显的匹配对能有0.8以上，有的只有0.68左右，还存在很多明显不匹配的也能达到0.7，这就不好确定阈值了

**Comment by staoxiao** [comment]
> 主要是BGE相似度打分在我们这个业务场景中分布规律并不明显，比如有的明显的匹配对能有0.8以上，有的只有0.68左右，还存在很多明显不匹配的也能达到0.7，这就不好确定阈值了

明白了，我们之后会分析这个问题，后续会尝试改进相似度的分布。
如果您能提供一些bad case数据（邮箱：stxiao@baai.ac.cn），帮助我们进一步改进模型就更好了。

**Comment by aierwiki** [comment]
> > 主要是BGE相似度打分在我们这个业务场景中分布规律并不明显，比如有的明显的匹配对能有0.8以上，有的只有0.68左右，还存在很多明显不匹配的也能达到0.7，这就不好确定阈值了
> 
> 明白了，我们之后会分析这个问题，后续会尝试改进相似度的分布。 如果您能提供一些bad case数据（邮箱：[stxiao@baai.ac.cn](mailto:stxiao@baai.ac.cn)），帮助我们进一步改进模型就更好了。

q: 网络支付用户规模有多少   
p: 【数字化】中国互金协会：金融机构数字化转型迈入快车道 >> 中国互联网金融协会副秘书长杨农表示，金融机构数字化转型迈入快车道，数字化渠道对金融消费者的覆盖面和便利性不断提升。截至2022年底，我国网络支付用户规模增至9.11亿人，完成中国互联网金融协会标准符合性自律备案的移动金融APP超过2000款。个人数字金融、产业数字金融、金融市场数字化交易等领域的创新产品不断涌现，更好满足了实体经济和人民群众多样化的金融服务需求。  
sim_score:0.6078261733055115
--------------
q: 你好
p:【数字化】《中国金融》｜王纬：促进普惠金融数字化转型升级 >> 银行业强化数字普惠金融的方向 >> ，丰富数字化产品矩阵，升级推出“I·SMART——数字普惠金融服务+”
sim_score:0.6879750490188599

**Comment by staoxiao** [comment]
收到，感谢

**Comment by staoxiao** [comment]
您好，给查询增加指令能够更好的排序与该查询相关的文档，但确实会导致不同查询下的相似度不太可比，建议可以尝试不添加指令，或者使用无指令版本的bge: BAAI/bge-large-zh-noinstruct

**Comment by NLPJCL** [comment]
请问下，用向量检索的方式来做问答对这种任务（非query和doc做检索），有没有相关的论文呀？可以提供几篇嘛？

**Comment by staoxiao** [comment]
> 请问下，用向量检索的方式来做问答对这种任务（非query和doc做检索），有没有相关的论文呀？可以提供几篇嘛？

直接query检索answer的资料不多，通常都是检索包含answer的文本。Open Domain QA任务都是使用向量检索找到候选答案集合，再用生成模型抽取答案， 经典的比如DPR：https://arxiv.org/abs/2004.04906 。
