### ISSUE TITLE
bge m3模型中lexical_weights的token id是不是固定的？

### ISSUE THREAD

**Issue by PrimaLuz** [FlagOpen/FlagEmbedding#482]
您好，我有个问题，使用原生的bge m3 模型，不去微调，是不是它的词表是固定的，因此tokenizer之后的每个词都是固定的，在当前的语句中，token的id也是固定的？

**Comment by staoxiao** [comment]
您好，无论是否微调，词表都是固定的，在当前的语句中，token的id也是固定的。
如果需要增加词汇，需要增加词表，再进行微调。

**Comment by PrimaLuz** [comment]
十分感谢您的及时回答
