### ISSUE TITLE
请问下bge-large-zh这些模型都可以微调吗？请问下该怎么操作？

### ISSUE THREAD

**Issue by asenasen123** [FlagOpen/FlagEmbedding#49]

**Comment by staoxiao** [comment]
可以微调的。微调可以参考：https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune
按照格式准备好数据，选择合适的参数，命令行运作指令，最后按照方式加载本地模型就可以了。

**Comment by asenasen123** [comment]
> 可以微调的。微调可以参考：https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune 按照格式准备好数据，选择合适的参数，命令行运作指令，最后按照方式加载本地模型就可以了。

好的，多谢！请问下你们的评价指标是什么？只看到数值，没看到具体指标

**Comment by staoxiao** [comment]
各项任务的测试指标与mteb是一致的，可以查看：https://arxiv.org/abs/2210.07316
比如检索任务使用的是ndcg@10

**Comment by asenasen123** [comment]
> 各项任务的测试指标与mteb是一致的，可以查看：https://arxiv.org/abs/2210.07316 比如检索任务使用的是ndcg@10

请问下，如果要对bge-large-zh这些模型微调的话，大概需要多少条数据？

**Comment by staoxiao** [comment]
没有明确需求，质量高的数据越多越好，最好是超过千这个级别

**Comment by asenasen123** [comment]
> 没有明确需求，质量高的数据越多越好，最好是超过千这个级别

请问下eval_splits=['dev'],这里的语料是怎么处理的。我看了语料库，里面没有分成train、dev、test这些。您能否帮忙讲解下您的代码中如何加载语料库的？

**Comment by asenasen123** [comment]
> > 没有明确需求，质量高的数据越多越好，最好是超过千这个级别
> 
> 请问下eval_splits=['dev'],这里的语料是怎么处理的。我看了语料库，里面没有分成train、dev、test这些。您能否帮忙讲解下您的代码中如何加载语料库的？

哦哦，已经在huggingface数据库看到了，自己弄清楚了，不好意思

**Comment by asenasen123** [comment]
请问下C_MTEB.py一般要运行多久能够跑完？

**Comment by staoxiao** [comment]
如果是用您的数据微调后，可以在自己的测试数据上进行测试。C_MTEB里包含了各种任务，很多任务或者场景可能与您自己的任务没有关联，不具备参考意义。
运行时，C_MTE默认会运行所有任务，在8卡机器上大概几个小时就能完成。可以指定`--task_type`来运行特定任务类型而不是全部任务。
如
```
python eval_C-MTEB.py --model_name_or_path BAAI/bge-large-zh --task_type Retrieval
```
不同任务类型可以参考https://github.com/FlagOpen/FlagEmbedding/tree/master/C_MTEB#tasks 里的type属性。

**Comment by asenasen123** [comment]
> 

感谢您的回复！请问下我把数据集下载到本地，FileNotFoundError: Couldn't find a dataset script at /root/******/Dataset/CovidRetrieval/CovidRetrieval.py or any data file in the same 
directory。在本地上可以加载数据集，同样的代码放到服务器上跑，又出现上述问题（路径已经修改过了），请问下您知道原因吗

**Comment by staoxiao** [comment]
> 我看了微调的数据处理，确实没有切分数据集啊，是全部数据进行训练吧 @staoxiao

是的，当前训练会使用train.jsonl里提供的所有数据

**Comment by Yyy11181** [comment]
好的！谢谢您

**Comment by Yyy11181** [comment]
> 务
那您不建议在。C_MTEB里面进行测试，提到”可以在自己的测试数据上进行测试“
是怎么个方式呢？能具体解释一下吗？感谢 @staoxiao

**Comment by staoxiao** [comment]
在下游数据上微调是为了提升在下游任务的能力，所以应该测试在下游具体任务的表现。当然，也可以用C_MTEB来检测相关任务的泛化能力。
测试可以参考mteb： https://github.com/embeddings-benchmark/mteb 。对于检索任务，就是自己的数据编码成向量之后，对每个query找到topk，查看相关文本是否在topk列表里，计算一些排序指标，比如ndcg, recall等。

**Comment by Yyy11181** [comment]
好的，谢谢您的提醒。再次感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月24日(周四) 晚上11:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FlagOpen/FlagEmbedding] 请问下bge-large-zh这些模型都可以微调吗？请问下该怎么操作？ (Issue #49)




 
在下游数据上微调是为了提升在下游任务的能力，所以应该测试在下游具体任务的表现。当然，也可以用C_MTEB来检测相关任务的泛化能力。
 测试可以参考mteb： https://github.com/embeddings-benchmark/mteb 。对于检索任务，就是自己的数据编码成向量之后，对每个query找到topk，查看相关文本是否在topk列表里，计算一些排序指标，比如ndcg, recall等。

**Comment by asenasen123** [comment]
> 在下游数据上微调是为了提升在下游任务的能力，所以应该测试在下游具体任务的表现。当然，也可以用C_MTEB来检测相关任务的泛化能力。 测试可以参考mteb： https://github.com/embeddings-benchmark/mteb 。对于检索任务，就是自己的数据编码成向量之后，对每个query找到topk，查看相关文本是否在topk列表里，计算一些排序指标，比如ndcg, recall等。

请问下，下游具体任务的测试数据格式应该是怎么样？

**Comment by staoxiao** [comment]
> > 在下游数据上微调是为了提升在下游任务的能力，所以应该测试在下游具体任务的表现。当然，也可以用C_MTEB来检测相关任务的泛化能力。 测试可以参考mteb： https://github.com/embeddings-benchmark/mteb 。对于检索任务，就是自己的数据编码成向量之后，对每个query找到topk，查看相关文本是否在topk列表里，计算一些排序指标，比如ndcg, recall等。
> 
> 请问下，下游具体任务的测试数据格式应该是怎么样？

see https://github.com/FlagOpen/FlagEmbedding/issues/76
