### ISSUE TITLE
finetune报错

### ISSUE THREAD

**Issue by johnnysjc** [FlagOpen/FlagEmbedding#493]
加载完模型参数后，报错
ValueError: prefetch_factor option could only be specified in multiprocessing.let num_workers > 0 to enable multiprocessing.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8605) of binary: /home/songwsl/anaconda3/envs/pytorch/bin/python3.8
请教如何解决，谢谢

**Comment by johnnysjc** [comment]
完整命令行：
(pytorch) songwsl@Song:~/FlagEmbedding-master$ torchrun --nproc_per_node 1 \
> -m FlagEmbedding.baai_general_embedding.finetune.run \
> --output_dir ./output \
> --model_name_or_path ./bge-large-zh-v1.5 \
> --train_data ./examples/finetune/toy_finetune_data.jsonl \
> --learning_rate 1e-5 \
> --fp16 \
> --num_train_epochs 5 \
> --per_device_train_batch_size 1 \
> --dataloader_drop_last True \
> --normlized True \
> --temperature 0.02 \
> --query_max_len 64 \
> --passage_max_len 256 \
> --train_group_size 2 \
> --negatives_cross_device \
> --logging_steps 10 \
> --query_instruction_for_retrieval ""
02/27/2024 09:26:10 - WARNING - __main__ -   Process rank: 0, device: cuda:0, n_gpu: 1, distributed training: True, 16-bits training: True
02/27/2024 09:26:10 - INFO - __main__ -   Training/evaluation parameters RetrieverTrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=True,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fix_position_embedding=False,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=1e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=./output/runs/Feb27_09-26-10_Song,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_kwargs={},
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
negatives_cross_device=True,
no_cuda=False,
normlized=True,
num_train_epochs=5.0,
optim=adamw_torch,
optim_args=None,
output_dir=./output,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=1,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
resume_from_checkpoint=None,
run_name=./output,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=steps,
save_total_limit=None,
seed=42,
sentence_pooling_method=cls,
skip_memory_metrics=True,
split_batches=None,
temperature=0.02,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_inbatch_neg=True,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
)
02/27/2024 09:26:10 - INFO - __main__ -   Model parameters ModelArguments(model_name_or_path='./bge-large-zh-v1.5', config_name=None, tokenizer_name=None, cache_dir=None)
02/27/2024 09:26:10 - INFO - __main__ -   Data parameters DataArguments(train_data='./examples/finetune/toy_finetune_data.jsonl', train_group_size=2, query_max_len=64, passage_max_len=256, max_example_num_per_dataset=100000000, query_instruction_for_retrieval='', passage_instruction_for_retrieval=None)
02/27/2024 09:26:10 - INFO - __main__ -   Config: BertConfig {
  "_name_or_path": "./bge-large-zh-v1.5",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "directionality": "bidi",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "id2label": {
    "0": "LABEL_0"
  },
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "label2id": {
    "LABEL_0": 0
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.38.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}

Traceback (most recent call last):
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/songwsl/FlagEmbedding-master/FlagEmbedding/baai_general_embedding/finetune/run.py", line 117, in <module>
    main()
  File "/home/songwsl/FlagEmbedding-master/FlagEmbedding/baai_general_embedding/finetune/run.py", line 108, in main
    trainer.train()
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 1653, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 852, in get_train_dataloader
    return self.accelerator.prepare(DataLoader(train_dataset, **dataloader_params))
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 230, in __init__
    raise ValueError('prefetch_factor option could only be specified in multiprocessing.'
ValueError: prefetch_factor option could only be specified in multiprocessing.let num_workers > 0 to enable multiprocessing.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11482) of binary: /home/songwsl/anaconda3/envs/pytorch/bin/python3.8
Traceback (most recent call last):
  File "/home/songwsl/anaconda3/envs/pytorch/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/songwsl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
FlagEmbedding.baai_general_embedding.finetune.run FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-27_09:26:16
  host      : Song.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11482)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by johnnysjc** [comment]
![报错](https://github.com/FlagOpen/FlagEmbedding/assets/102014478/2981b47e-bfdf-4905-90f6-e53c9dda2c56)

**Comment by johnnysjc** [comment]
按照官方文档加载的
torchrun --nproc_per_node 1 
-m FlagEmbedding.baai_general_embedding.finetune.run 
--output_dir ./output 
--model_name_or_path ./bge-large-zh-v1.5 
--train_data ./examples/finetune/toy_finetune_data.jsonl 
--learning_rate 1e-5 
--fp16 
--num_train_epochs 5 
--per_device_train_batch_size 1 
--dataloader_drop_last True 
--normlized True 
--temperature 0.02 
--query_max_len 64 
--passage_max_len 256 
--train_group_size 2 
--negatives_cross_device 
--logging_steps 10 
--query_instruction_for_retrieval ""

**Comment by johnnysjc** [comment]
问题已解决，https://blog.csdn.net/horsetaill/article/details/136160243，用这个方法解决的

**Comment by staoxiao** [comment]
可能跟transfomers版本有关，我们这边尝试4.37没有问题。您可以提供一下您的版本吗？

**Comment by johnnysjc** [comment]
谢谢您的回复~我的transformers版本是4.38.1，新鲜装的，我按照楼上那个帖子改了源码里面num_workers的代码，就没问题了。

**Comment by johnnysjc** [comment]
> 可能跟transfomers版本有关，我们这边尝试4.37没有问题。您可以提供一下您的版本吗？

您好，我想请问微调结束后，新的模型名称叫什么，保存在哪里

**Comment by 1104347305** [comment]
> 谢谢您的回复~我的transformers版本是4.38.1，新鲜装的，我按照楼上那个帖子改了源码里面num_workers的代码，就没问题了。

您好，请问下是改哪个地方的num_workers呢？楼上帖子打不开了，我这边也遇到了同样的问题。

**Comment by staoxiao** [comment]
> > 可能跟transfomers版本有关，我们这边尝试4.37没有问题。您可以提供一下您的版本吗？
> 
> 您好，我想请问微调结束后，新的模型名称叫什么，保存在哪里

在设定的--output_dir ./output里

**Comment by 1104347305** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by staoxiao** [comment]
> > 谢谢您的回复~我的transformers版本是4.38.1，新鲜装的，我按照楼上那个帖子改了源码里面num_workers的代码，就没问题了。
> 
> 您好，请问下是改哪个地方的num_workers呢？楼上帖子打不开了，我这边也遇到了同样的问题。

可以尝试修改transformers的版本

**Comment by johnnysjc** [comment]
> > > 可能跟transfomers版本有关，我们这边尝试4.37没有问题。您可以提供一下您的版本吗？
> > 
> > 
> > 您好，我想请问微调结束后，新的模型名称叫什么，保存在哪里
> 
> 在设定的--output_dir ./output里

![image](https://github.com/FlagOpen/FlagEmbedding/assets/102014478/85c3cfbe-6621-4c5f-9fec-2259500ee33e)
请问是model.safetensors吗

**Comment by johnnysjc** [comment]
> > 谢谢您的回复~我的transformers版本是4.38.1，新鲜装的，我按照楼上那个帖子改了源码里面num_workers的代码，就没问题了。
> 
> 您好，请问下是改哪个地方的num_workers呢？楼上帖子打不开了，我这边也遇到了同样的问题。
这个这个：https://blog.csdn.net/horsetaill/article/details/136160243

**Comment by 1104347305** [comment]
> > > 谢谢您的回复~我的transformers版本是4.38.1，新鲜装的，我按照楼上那个帖子改了源码里面num_workers的代码，就没问题了。
> > 
> > 
> > 您好，请问下是改哪个地方的num_workers呢？楼上帖子打不开了，我这边也遇到了同样的问题。
> 
> 可以尝试修改transformers的版本

我把transformers版本改成4.34.0以后可以了，谢谢您

**Comment by 1104347305** [comment]
> > > 谢谢您的回复~我的transformers版本是4.38.1，新鲜装的，我按照楼上那个帖子改了源码里面num_workers的代码，就没问题了。
> > 
> > 
> > 您好，请问下是改哪个地方的num_workers呢？楼上帖子打不开了，我这边也遇到了同样的问题。
> > 这个这个：https://blog.csdn.net/horsetaill/article/details/136160243
谢谢您，通过改transformers的版本已经可以了
