### ISSUE TITLE
Finetuning / Continue pretraining code+data m3 

### ISSUE THREAD

**Issue by PierreColombo** [FlagOpen/FlagEmbedding#496]
Hello,
Thanks a lot for your great work! Super nice idea to combine the three types of retrieval.
Would it be possible to have a fine-tuning code + data ? This would allow us to built and re-use your work !
Thanks again,
Pierre

**Comment by hanhainebula** [comment]
Thanks for your interest in our work! The fine-tuning code and data of BGE-M3 are expected to be released within this week.

**Comment by hanhainebula** [comment]
Hello! We have released the code and data.
