### ISSUE TITLE
关于是否需要添加instruction的问题

### ISSUE THREAD

**Issue by time1527** [FlagOpen/FlagEmbedding#498]
您好，我的任务情况类似于在大量文言文中找到最贴合场景（现代白话文）的一句，数据是文言文-白话文翻译的句子对。

根据其他issue中的问题及您的解答，我暂时确定了微调时query是白话文（即场景描述），pos是文言文，neg是文言文列表。但仍有如下问题：

1. 有看到您在之前的issue中回复到“翻译数据建议不添加这个指令，将query_instruction_for_retrieval设置为空就好”，白话文-文言文类似翻译，但任务又涉及检索，所以不大能拿准instruction是否要添加

2. 关于数据构建：考虑到RAG中有一说法是“先根据问题生成答案，然后问题和答案拼接去查询”，在这种情况下实际query是白话文+文言文的形式，那么数据集是可以保持不变，还是要基于原数据构造 {"query": 白话文+文言文, “pos": 文言文, ”neg":文言文列表}会更好（以及后者的instruction是否需要添加）

**Comment by staoxiao** [comment]
1. 直接不加就好。加指令会导致使用更加复杂。
2. {"query": 白话文+文言文, “pos": 文言文, ”neg":文言文列表}数据里query里的文言文和pos的文言文是一样的吗？如果是一样的，存在数据泄露，模型训不好。另外，pos也是一个列表。

**Comment by time1527** [comment]
> 1. 直接不加就好。加指令会导致使用更加复杂。
> 2. {"query": 白话文+文言文, “pos": 文言文, ”neg":文言文列表}数据里query里的文言文和pos的文言文是一样的吗？如果是一样的，存在数据泄露，模型训不好。另外，pos也是一个列表。

好的，非常感谢您的回答，实践中我会注意将pos设置为列表以及数据泄露问题。问题2中，query中的文言文部分是使用llm对query中的白话文部分转换生成，类似于”请使用文言文描述xxx场景（即query中白话文）“，这样应该不会存在数据泄露问题
