### ISSUE TITLE
增大模型最长长度限制

### ISSUE THREAD

**Issue by knowledge-llz** [FlagOpen/FlagEmbedding#50]
当前我需要对大量较长的文档片段进行检索，但不幸的是，这些文档片段很多超过了512个token的长度限制，甚至达到了1000个token以上。因为上下文语义的关系，我不希望对这些文本进行分割。
我手里有大量提问与对应的长片段的数据，请问我能否直接将模型中的max_length参数改为2048，并用手中的长文本数据进行微调，希望能增强模型检索长文档的能力，请问这种做法是否可行？

**Comment by staoxiao** [comment]
向量模型实际上是一个压缩模型，片段太长会影响性能，所以还是建议不要使用太长的文本。想要保留予以关系的化，可以将一些关键信息比如标题拼在每段前面，或者使用一些llm生成文本摘要。
当前模型采取的是bert的架构，使用的是绝对位置编码，您需要修改config中的max_position_embeddings增加position embddings，当前的微调脚本没有尝试过，可以还需要更改一些code

**Comment by knowledge-llz** [comment]
好的，明白了，感谢您的解答！

**Comment by campuslifeceo** [comment]
我注意到finetune脚本中的--passage_max_len 128， 而实际模型的最大输入是512，请问这个偏差是什么原因？

**Comment by staoxiao** [comment]
您好，finetune脚本只是一个示例，128能适应很多段落检索任务，更大的长度会消耗非常高的显存，微调的时候应根据实际数据的长度和训练资源进行权衡。

**Comment by kk3dmax** [comment]
> max_position_embeddings

如果只是用于  推理/获取得分, 能通过调整max_position_embeddings = 2048, 来获得"无损"的性能吗? 还是说, 会有潜在的bug或者隐患?
