### ISSUE TITLE
reranker跑任务 `MMarcoReranking`结果与Leaderboard 不一致 求解

### ISSUE THREAD

**Issue by NameJaho** [FlagOpen/FlagEmbedding#507]
你好 我使用 `bge-large-zh-v1.5` 模型跑 MMarcoReranking 任务，结果为**0.006**，差异过大，求解
代码：
```
model = FlagReranker('BAAI/bge-large-zh-v1.5' use_fp16=True)
evaluation = MTEB(tasks=['MMarcoReranking'])
evaluation.run(model, output_folder=f"result/reranker_results/{model_path}")
```
同样的，使用`BAAI/bge-reranker-large` 结果就没问题

**Comment by staoxiao** [comment]
bge-large-zh-v1.5是embedding model，不能使用FlagReranker进行加载。参考https://github.com/FlagOpen/FlagEmbedding/tree/master/C_MTEB#evaluate-embedding-model

**Comment by NameJaho** [comment]
> bge-large-zh-v1.5是embedding model，不能使用FlagReranker进行加载。参考https://github.com/FlagOpen/FlagEmbedding/tree/master/C_MTEB#evaluate-embedding-model

那是用 SentenceTransformer 加载吗？

我尝试用 SentenceTransformer 加载 bge-large-zh-v1.5 但速度很慢很慢

**Comment by staoxiao** [comment]
可以参考我们的评测脚本：https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py#L31

**Comment by NameJaho** [comment]
> 可以参考我们的评测脚本：https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py#L31

好的 感谢大佬
