### ISSUE TITLE
BGE_M3/modeling.py: Replace print() with either (already used) logger.info or at least print(file=sys.stderr) 

### ISSUE THREAD

**Issue by Maykeye** [FlagOpen/FlagEmbedding#514]
Consider current [code that loads the model](https://github.com/FlagOpen/FlagEmbedding/blob/97f57a1b92dc68d56731a1e38a2d3aad4cd67e20/FlagEmbedding/BGE_M3/modeling.py#L85)

Right now if I want to make a script that outputs pure JSON to stdout, I need to work around the loader by temporary disabling print with `globals()["__builtins__"].print = lambda *args, **kwargs: None` as otherwise the model loader prints to the stdout that weights exist, breaking JSON. 

Expected behavior:  stdout not being touched.

Proposed solution: `logger.info` doesn't outputs data to stdout and it's [already used](https://github.com/FlagOpen/FlagEmbedding/blob/97f57a1b92dc68d56731a1e38a2d3aad4cd67e20/FlagEmbedding/BGE_M3/modeling.py#L59)

**Comment by staoxiao** [comment]
Thanks for your suggestion! We have updated the source code.

**Comment by Maykeye** [comment]
Thanks!
