### ISSUE TITLE
bge_large_zh_v1.5微调后的评估问题

### ISSUE THREAD

**Issue by johnnysjc** [FlagOpen/FlagEmbedding#522]
请问有没有适合中文的评估数据集，我这边越微调，在msmarco上的召回率越低。
原始模型
{'MRR@1': 0.04340974212034384, 
'MRR@10': 0.08355823895938519, 
'MRR@100': 0.09039545799825212, 
'Recall@1': 0.04145176695319962, 
'Recall@10': 0.1847063037249284, 
'Recall@100': 0.37225405921681004}
微调50轮模型
{'MRR@1': 0.02335243553008596,
 'MRR@10': 0.04534156547050519, 
'MRR@100': 0.0495361923483206, 
'Recall@1': 0.022373447946513848, 
'Recall@10': 0.09924785100286533, 
'Recall@100': 0.21038681948424065}
微调150轮模型
{'MRR@1': 0.014469914040114613, 
'MRR@10': 0.02514554054668665, 
'MRR@100': 0.027696593732125387, 
'Recall@1': 0.013896848137535816, 
'Recall@10': 0.053271251193887294, 
'Recall@100': 0.1260267430754537}

**Comment by staoxiao** [comment]
msmarco是英文数据集，bge-zh不应该在上面评测。可以参考https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py，使用c-mteb上的任务如t2ranking, dulreader。

**Comment by johnnysjc** [comment]
> msmarco是英文数据集，bge-zh不应该在上面评测。可以参考[https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py，使用c-mteb上的任务如t2ranking](https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py%EF%BC%8C%E4%BD%BF%E7%94%A8c-mteb%E4%B8%8A%E7%9A%84%E4%BB%BB%E5%8A%A1%E5%A6%82t2ranking), dulreader。

您好，他这次报错ImportError: cannot import name 'DRESModel' from 'mteb'，我的mteb版本是1.2.0，C_MTEB版本是1.1.0。
![image](https://github.com/FlagOpen/FlagEmbedding/assets/102014478/a8b1768b-3d20-44ad-b53e-2e9e7bdf94c4)

**Comment by staoxiao** [comment]
> > msmarco是英文数据集，bge-zh不应该在上面评测。可以参考[https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py，使用c-mteb上的任务如t2ranking](https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py%EF%BC%8C%E4%BD%BF%E7%94%A8c-mteb%E4%B8%8A%E7%9A%84%E4%BB%BB%E5%8A%A1%E5%A6%82t2ranking), dulreader。
> 
> 您好，他这次报错ImportError: cannot import name 'DRESModel' from 'mteb'，我的mteb版本是1.2.0，C_MTEB版本是1.1.0。 ![image](https://private-user-images.githubusercontent.com/102014478/310762742-a8b1768b-3d20-44ad-b53e-2e9e7bdf94c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTE2NDAsIm5iZiI6MTcwOTgxMTM0MCwicGF0aCI6Ii8xMDIwMTQ0NzgvMzEwNzYyNzQyLWE4YjE3NjhiLTNkMjAtNDRhZC1iNTNlLTJlOWU3YmRmOTRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMTM1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDJlNzdjYzViOGQyMDU5YTEwZTE5YTc2YTM4Yjg5OWU0NzlhNGUzMzhiNWI0MTQ1NGQ1NmU3ZDE4OTcwOTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lvjSOMfd1-n9RjQTY2svX6Z8TKcY-22PfaLZdoOwwKs)

估计最新版的mteb修改了代码，可以降低版本。

**Comment by johnnysjc** [comment]
> > > msmarco是英文数据集，bge-zh不应该在上面评测。可以参考[https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py，使用c-mteb上的任务如t2ranking](https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py%EF%BC%8C%E4%BD%BF%E7%94%A8c-mteb%E4%B8%8A%E7%9A%84%E4%BB%BB%E5%8A%A1%E5%A6%82t2ranking), dulreader。
> > 
> > 
> > 您好，他这次报错ImportError: cannot import name 'DRESModel' from 'mteb'，我的mteb版本是1.2.0，C_MTEB版本是1.1.0。 ![image](https://private-user-images.githubusercontent.com/102014478/310762742-a8b1768b-3d20-44ad-b53e-2e9e7bdf94c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTE2NDAsIm5iZiI6MTcwOTgxMTM0MCwicGF0aCI6Ii8xMDIwMTQ0NzgvMzEwNzYyNzQyLWE4YjE3NjhiLTNkMjAtNDRhZC1iNTNlLTJlOWU3YmRmOTRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMTM1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDJlNzdjYzViOGQyMDU5YTEwZTE5YTc2YTM4Yjg5OWU0NzlhNGUzMzhiNWI0MTQ1NGQ1NmU3ZDE4OTcwOTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lvjSOMfd1-n9RjQTY2svX6Z8TKcY-22PfaLZdoOwwKs)
> 
> 估计最新版的mteb修改了代码，可以降低版本。

您好，请问有没有开源的微调数据集，我用https://github.com/shibing624/text2vec/blob/master/examples/data/bge_finetune_data.jsonl
这个数据集微调之后的评估结果还不如原来的模型。
bge_large_zh_v1.5 :  "mrr_at_100": 0.9213,   "mrr_at_1000": 0.92134,  "recall_at_100": 0.94676, "recall_at_1000": 0.98188,
我训练了150轮之后的模型： "mrr_at_100": 0.80198, "mrr_at_1000": 0.8021,  "recall_at_100": 0.86645, "recall_at_1000": 0.9524,

**Comment by staoxiao** [comment]
可以使用bge-m3的微调数据Shitao/bge-m3-data，下载下来选择其中的中文数据即可。

**Comment by johnnysjc** [comment]
> 可以使用bge-m3的微调数据Shitao/bge-m3-data，下载下来选择其中的中文数据即可。

收到！谢谢老师！

**Comment by wangsir-cn** [comment]
您好，微调bge_large_zh_v1.5模型您用的微调数据是什么？
