### ISSUE TITLE
Mix process doesn't run on GPUs, only CPU + RAM

### ISSUE THREAD

**Issue by kaykyr** [FlagOpen/FlagEmbedding#526]
Hello guys, I have a server config:
```txt
64GB RAM
2x RTX 4090
```

I am trying to mix two models using the following script:

```python
from LM_Cocktail import mix_models, mix_models_with_data
    
model = mix_models(
    model_names_or_paths=["mistralai/Mistral-7B-Instruct-v0.2", "kaykyramos/aura-7b-instruct-pretrained"], 
    model_type='decoder', 
    weights=[0.3, 0.7],  # you can change the weights to get a better trade-off.
    output_path='/ors/workdir/aura-mixed')
```

This script is not able to load models on GPUs, it loads directly to RAM:

```logs
loading mistralai/Mistral-7B-Instruct-v0.2 -----------------
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.04s/it]
loading kaykyramos/aura-7b-instruct-pretrained -----------------
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:04<00:00,  1.39s/it]
Killed
```

When it is loading I can check that no data is loading to GPUs VRAM, when I run ```htop``` I can see DDR RAM increasing till exceeding maximum (64GB), is this correct? It's only possible to do that task over CPU?

**Comment by staoxiao** [comment]
Currently, the script will default load the model on CPU (https://github.com/FlagOpen/FlagEmbedding/blob/master/LM_Cocktail/LM_Cocktail/utils.py#L15). If you want to load it on GPU, you need to change the `device_map = {"": "cpu"}`.

Besides, you also can mix models layer by layer following https://github.com/FlagOpen/FlagEmbedding/tree/master/LM_Cocktail#3-mix-models-layer-by-layer-for-reducing-memory-cost

**Comment by kaykyr** [comment]
> Currently, the script will default load the model on CPU (https://github.com/FlagOpen/FlagEmbedding/blob/master/LM_Cocktail/LM_Cocktail/utils.py#L15). If you want to load it on GPU, you need to change the `device_map = {"": "cpu"}`.
> 
> Besides, you also can mix models layer by layer following https://github.com/FlagOpen/FlagEmbedding/tree/master/LM_Cocktail#3-mix-models-layer-by-layer-for-reducing-memory-cost

Thank you so much @staoxiao!
