### ISSUE TITLE
Schedule里的Multilingual model是考虑中英双语的吗？

### ISSUE THREAD

**Issue by firezym** [FlagOpen/FlagEmbedding#54]
感觉现有模型效果蛮好。在实际运用中，可能就中文和英文用的多，官方有考虑推出一个更大点的模型来适配中英文吗？平时的使用场景里面就中英文两种最高频，包括编程的一些retrieval，如果能适配好很有用~

**Comment by staoxiao** [comment]
感谢！
中英文模型和代码检索都在日程上，我们会尽快完成训练。

**Comment by firezym** [comment]
非常感谢！
