### ISSUE TITLE
关于微调的问题

### ISSUE THREAD

**Issue by bombia** [FlagOpen/FlagEmbedding#56]
你好，我在微调的过程中出现了
![image](https://github.com/FlagOpen/FlagEmbedding/assets/21083545/d1a64b69-cb03-4113-8dff-ebd9c344c468)
这样的错误，即global_step的值应该是变成0了，请问可以帮我看看我的参数配置有什么问题吗，我的参数配置如下
torchrun --nproc_per_node 1 \
-m FlagEmbedding.baai_general_embedding.finetune.run \
--output_dir ./models \
--model_name_or_path BAAI/bge-large-zh \
--train_data km0fs.json \
--learning_rate 3e-5 \
--num_train_epochs 5 \
--per_device_train_batch_size 500 \
--dataloader_drop_last True \
--normlized True \
--temperature 0.01 \
--query_max_len 32 \
--passage_max_len 128 \
--negatives_cross_device 
另外我的数据集的情况是：query字段是一个文本，pos字段是文本字符串的列表，neg也是另外的文本字符串列表，每个neg列表的长度都是8

**Comment by bombia** [comment]
总的数据长度是18

**Comment by staoxiao** [comment]
您好，这应该是由于数据量太少，导致step 0就跑完导致的，可以尝试把batch size设小一些，小于数据总数量

**Comment by bombia** [comment]
> 您好，这应该是由于数据量太少，导致step 0就跑完导致的，可以尝试把batch size设小一些，小于数据总数量

确实跑通了，太感谢了~
