### ISSUE TITLE
.cache位置如何调整

### ISSUE THREAD

**Issue by daneyoung01** [FlagOpen/FlagEmbedding#570]
from FlagEmbedding import BGEM3FlagModel
自动下载models--BAAI--bge-m3文件夹到C:\Users\Administrator\.cache\huggingface\hub目录，请问如何更改这个目录，减少C盘空间占用？

**Comment by staoxiao** [comment]
可以更改huggingface的默认下载路径：
```
import os
os.environ['HF_HUB_CACHE'] = "new_path"
```

**Comment by daneyoung01** [comment]
明白了，谢谢

> 可以更改huggingface的默认下载路径：
> 
> ```
> import os
> os.environ['HF_HUB_CACHE'] = "new_path"
> ```
