### ISSUE TITLE
context length extension 

### ISSUE THREAD

**Issue by drewskidang** [FlagOpen/FlagEmbedding#571]
is it possible to increase bge context length? Realize most of my training data goes beyond 512

**Comment by staoxiao** [comment]
You can use our new model: bge-m3 https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/BGE_M3, which supports multilingual and 8192 tokens.

**Comment by drewskidang** [comment]
Thank you, you guys are always on top of things!
