### ISSUE TITLE
【llm_reranker】MiniCPM-2B基座选取问题

### ISSUE THREAD

**Issue by zqqqqq1** [FlagOpen/FlagEmbedding#577]
hi请问llm_reranker的基座，MiniCPM-2B-dpo-bf16 和 MiniCPM-2B-sft-bf16，这两个是对比了dpo版本做基座来训练reranker效果更好吗？

**Comment by 545999961** [comment]
是的，之前尝试过这两个版本的基座，dpo版本的reranker效果更好一点
