### ISSUE TITLE
请问这个例子里的pymilvus是什么版本，我安装的2.3.7没有AnnSearchRequest, RRFRanker, WeightedRanker这些类

### ISSUE THREAD

**Issue by seetimee** [FlagOpen/FlagEmbedding#582]
https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/BGE_M3

**Comment by staoxiao** [comment]
refer to https://github.com/FlagOpen/FlagEmbedding/issues/580

**Comment by seetimee** [comment]
thanks

**Comment by HuangZhiXiang498** [comment]
最后是这么处理的呢

**Comment by seetimee** [comment]
pymilvus已经更新到2.4.0了呀,可以用了
