### ISSUE TITLE
bge m3 做pretrain相关

### ISSUE THREAD

**Issue by MoYang94** [FlagOpen/FlagEmbedding#589]
你好，如果想在bge m3的基础上做pretrain，那么和在bge-v1.5上做pretrain有什么区别吗，有相应的script参考吗，谢谢

**Comment by staoxiao** [comment]
没有区别。按照https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/pretrain流程训练即可。注意安装最新版的代码
git clone https://github.com/FlagOpen/FlagEmbedding.git
cd FlagEmbedding
pip install  -e .
