### ISSUE TITLE
参数疑问

### ISSUE THREAD

**Issue by sunzx8** [FlagOpen/FlagEmbedding#593]
我在finetune过程中遇到loss为0的情况，请问是因为什么原因

**Comment by sunzx8** [comment]
<img width="458" alt="image" src="https://github.com/FlagOpen/FlagEmbedding/assets/136688632/05971c8f-092c-4b57-bfc5-e9ca0c98126e">

**Comment by sunzx8** [comment]
这是训练代码
nohup torchrun --nproc_per_node 1 -m FlagEmbedding.baai_general_embedding.finetune.run --output_dir /data/shawn_test/train/output/ --model_name_or_path /data/embedding_worker/model/bge-base-zh --train_data /data/shawn_test/rag/finetune/output.jsonl  --learning_rate 1e-5 --fp16 --num_train_epochs 5 --per_device_train_batch_size 2 --dataloader_drop_last True --normlized True --temperature 0.02 --query_max_len 64 --passage_max_len 256 --train_group_size 2 --negatives_cross_device --logging_steps 10 --query_instruction_for_retrieval "" > log_train.log 2>&1 &

**Comment by sunzx8** [comment]
还有我想问一下
query_max_len: max length for query. Please set it according the average length of queries in your data.
passage_max_len: max length for passage. Please set it according the average length of passages in your data.
这两个一个是问题长度，一个是信息（正回答/负回答）长度吗？

**Comment by staoxiao** [comment]
如果是偶而为0，其他时候又是正常的，可能是那个batch的数据太简单了。
如果一致为0，就是训崩了，调小学习率试试。

query_max_len是问题长度，passage_max_len是回答长度。
