### ISSUE TITLE
funtune  保存模型格式为model.safetensors  如何换成bin

### ISSUE THREAD

**Issue by xxllp** [FlagOpen/FlagEmbedding#598]
这块我看使用微调代码默认输出的格式都不是bin格式，这块有啥办法保存bin吗

**Comment by staoxiao** [comment]
使用的是huggingface trainer进行训练，参数参考：https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.save_safetensors
可以设置--save_safetensors False

**Comment by lower01** [comment]
> 使用的是huggingface trainer进行训练，参数参考：https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.save_safetensors 可以设置--save_safetensors False

在哪个文件的哪里设置--save_safetensors False，我不能打开huggingface网站，可以进行说明或者截图展示吗？谢谢您

**Comment by lower01** [comment]
> 使用的是huggingface trainer进行训练，参数参考：https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.save_safetensors 可以设置--save_safetensors False

在这个示例代码段中，
![image](https://github.com/FlagOpen/FlagEmbedding/assets/45301618/919604e9-582b-417d-bf59-c200b0e060d9)
如何设置--save_safetensors False
