### ISSUE TITLE
难负例的挖掘

### ISSUE THREAD

**Issue by NLPJCL** [FlagOpen/FlagEmbedding#6]
您好，感谢非常棒的工作。
1.请问下，训练过程中，微调阶段，难负例的挖掘具体是怎么做的呢？可否简单介绍下，挖掘的个数呢？我看默认，负例是7个。
2.模型微调阶段，forward里面的参数passage，是否维度是[8,batch_size,max_length]？第一个tensor[batch_size,max_length]是当前batch query的正例，后面7个tensor[batch_size,max_length]是当前batch的query的7个负例？

**Comment by staoxiao** [comment]
您好~，
1. 难负例是按照通用的方法：从passages中找到top200, 删除其中的正例，从中进行随机选取，挖掘的数量不限，训练的时候会从中再次随机选取指定数量。
2. passage 的维度是[group_size*batch_size, max_length], 每隔group_size个passage是一个query的正例，
正例label的[生成方式是](https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/baai_general_embedding/finetune/modeling.py)：
```
target = torch.arange(scores.size(0), device=scores.device, dtype=torch.long)
target = target * (p_reps.size(0) // q_reps.size(0))
```
即当group_size=8, 输入数据中负样本数量为7(我们会同时加上in-batch negatives, 总negatives为8*batch_size-1)，label为[0, 8, 16, ...]

**Comment by NLPJCL** [comment]
请问下，初步的找到top200，是用什么模型来排序top200的呢？

**Comment by staoxiao** [comment]
初步排序也可以使用bge或者其他向量模型

**Comment by NLPJCL** [comment]
感谢回答，完美解决问题。

**Comment by campuslifeceo** [comment]
如何确定某个passage是positive 还是negative
