### ISSUE TITLE
一直报错prefetch_factor，但是又不能添加这个参数

### ISSUE THREAD

**Issue by Anthony-Sun-S** [FlagOpen/FlagEmbedding#611]
在微调reranker时一直出现下面这个报错
`ValueError: prefetch_factor option could only be specified in multiprocessing.let num_workers > 0 to enable multiprocessing, otherwise set prefetch_factor to None.`
今天重新pip了flagembedding想微调bge-reranker-v2-m3，然后换回reranker-v1也不行，添加这个参数也不行，微调的脚本就是reranker那部分提供的示例，请问这个该怎么办呢？

**Comment by 545999961** [comment]
请问你的torch版本以及huggingface版本是什么呢

**Comment by Anthony-Sun-S** [comment]
torch用的镜像源是这个：nvcr.io/nvidia/pytorch:23.02-py3，然后transformers是4.28.1，剩下的就是直接用清华镜像源pip install FlagEmbedding了

**Comment by 545999961** [comment]
从报错信息来看，这个参数对应的training args里的dataloader_prefetch_factor参数，如果不用多进程加载数据的话可以设为None；或者使用多进程加载数据，设置参数dataloader_num_workers>0
如果解决不了的话可以尝试将torch版本更新到2.0及以上，transformers版本也可以更新一下如4.38.1

**Comment by Anthony-Sun-S** [comment]
用了最新版本的torch镜像和transformers还是会有这个报错，请问这个参数应该加在哪里呢？不能直接加在启动训练的脚本里，然后也没有找到dataloader......

**Comment by Anthony-Sun-S** [comment]
现在解决了的，然后发现每训练一步就会有一个警告
`Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.`
这个警告会一下子重复几十遍出来，用尝试用log取消警告也没有用，不清楚这个是从哪里出来的
现在的镜像源是最新的nvcr.io/nvidia/pytorch:24.02-py3，transformers也直接pip的最新的版本，请问这个您知道该怎么取消吗？

**Comment by Anthony-Sun-S** [comment]
这个问题解决了，然后开始训练之后发现出现了一个警告
`Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.`
reranker和reranker-v2-m3都会出现这个，每训练一步会重复出现几十次，尝试用log取消警告也没有用，不太清楚该怎么能屏蔽这个警告，因为重复出现的数量太多了有点影响看训练进度，请问您知道该怎么办吗？

**Comment by 545999961** [comment]
这个应该是query的长度已经超过了max length，可以尝试增大max length

**Comment by Anthony-Sun-S** [comment]
我在训练reranker的时候还是按照reranker-v1的脚本用的是--max_len，而不是像llmreranker将query和passage分开，对于reranker-v2-m3有什么训练的参数和llmreranker是可以通用进行更新的吗？请问您有什么建议吗？

**Comment by 545999961** [comment]
设置max_len是没问题的，这个警告的原因是因为query的长度大于了max_len，可以适当增长max_len，保证passage也可以被编码进去

**Comment by Anthony-Sun-S** [comment]
我设置的max_len是2048，我刚刚统计了一下，query的平均长度只有24，最长的一个是1143，应该不至于超长吧

**Comment by 545999961** [comment]
可以将data.py中的truncation=True替换为Truncation='longest_first'
https://github.com/FlagOpen/FlagEmbedding/blob/0fe98ddefbd9d2caced52e94b9f8421d5ba7317f/FlagEmbedding/reranker/data.py#L40

**Comment by 545999961** [comment]
可以将data.py中的truncation=True替换为truncation='longest_first'
https://github.com/FlagOpen/FlagEmbedding/blob/0fe98ddefbd9d2caced52e94b9f8421d5ba7317f/FlagEmbedding/reranker/data.py#L40
