### ISSUE TITLE
Can we add device argument in FlagReranker's __init__ function?

### ISSUE THREAD

**Issue by wxywb** [FlagOpen/FlagEmbedding#613]
https://github.com/FlagOpen/FlagEmbedding/blob/61ce49e756128464501805dfcd89b37bf26ebad2/FlagEmbedding/flag_reranker.py#L149-L170
like __init__ in BGEM3FlagModel
https://github.com/FlagOpen/FlagEmbedding/blob/61ce49e756128464501805dfcd89b37bf26ebad2/FlagEmbedding/bge_m3.py#L26-L44
In the current setup, it is difficult to directly place the model on device:1 in such a scenario. If you have two graphics cards, and cuda:0 is occupied by an embedding model, when you attempt to place the reranker model on cuda:1, it will detect that it can run on a GPU and then attempt to use cuda:0, leading to an out-of-memory issue.

**Comment by 545999961** [comment]
Sure thing. We've made the necessary modifications to the code in llm_reranker.py. You can now specify the device.
