### ISSUE TITLE
FlagEmbedding - LLM-based layerwise reranker - After evaluating 20 passages or so, I start getting "BlockingIOError: [Errno 11] Resource temporarily unavailable"

### ISSUE THREAD

**Issue by sungkim11** [FlagOpen/FlagEmbedding#615]
BlockingIOError: [Errno 11] Resource temporarily unavailable
Exception ignored when trying to write to the signal wakeup fd:
Traceback (most recent call last):

**Comment by 545999961** [comment]
It seems to be related to system resource limitations. Could you provide more detailed code?

**Comment by sungkim11** [comment]
This is problem with FlagEmbedding. It seems it is using multiprocessing where it spawns a new process to perform score pair eval. This just eats up all system resources where I start getting these messages. No matter how big the system is, it will just eat up all resources.

**Comment by sungkim11** [comment]
The code:

self.reranker = LayerWiseFlagLLMReranker('BAAI/bge-reranker-v2-minicpm-layerwise', use_fp16=True)

scores = []
        for doc_prompt in search_results['text']:       
            score = self.reranker.compute_score([user_prompt, doc_prompt], cutoff_layers=[28]) 
            scores.append(score)

search_results['eval_score'] = scores

**Comment by sungkim11** [comment]
Thank you. Can you expose this as a parameter for the future?

**Comment by 545999961** [comment]
Alright, we will incorporate this as a parameter into the code in the future.

**Comment by sungkim11** [comment]
Closing

**Comment by 545999961** [comment]
The code has been updated now. You can pass the parameter `use_dataloader=False` or `num_workers` when `compute_score`.
