### ISSUE TITLE
训练集构成

### ISSUE THREAD

**Issue by Wenze7** [FlagOpen/FlagEmbedding#62]
想问下训练集中是否包括了测试集相关内容，尤其是retrieval任务，在我看来英文的测试集貌似是beir，beir中存在训练集和测试集，不知bge的训练集是否包括了beir中的训练集？

**Comment by staoxiao** [comment]
mteb的retrieval任务确实是beir。beir中有19个数据集，很多都没有训练集。
bge的训练集中相关的数据集有msmarco, nq, hotpotqa, quora (这些来源于sentence transformers收集的训练数据集)，以及fever。

**Comment by Wenze7** [comment]
这些数据构建的强负例能否提供一下呢

**Comment by staoxiao** [comment]
抱歉，目前暂时没有提供难负例的计划。您可以使用bge或者其他向量模型通过检索构建难负例。
