### ISSUE TITLE
BAAI/bge-large-zh和BAAI/bge-large-zh-noinstruct两个版本的区别是什么？

### ISSUE THREAD

**Issue by Zado-Tan** [FlagOpen/FlagEmbedding#63]
想了解下BAAI/bge-large-zh-noinstruct和BAAI/bge-large-zh在你们进行微调训练时候的区别是什么？

请问区别是否为：
BAAI/bge-large-zh就是在预训练的时候给query加上了类似instruction = "为这个句子生成表示以用于检索相关文章："，然后passage还是原本的内容不变。而BAAI/bge-large-zh-noinstruct则事故qyery和passage都保持原本内容进行训练吗？
(https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/baai_general_embedding/finetune/modeling.py#L22 参考了第78行的代码。)

如果是上面这样，应该会使用多种instruction吧？这个大概使用了多少种？可以给个相关的资料或者参考的文论吗？ 谢谢！

**Comment by staoxiao** [comment]
是的。但只使用了一种instruction，其他任务都相当于同质文本的比较，但检索任务是question和answer之间的匹配，而question和answer是存在差异的，因此对这种任务使用了一个Instruction，方便模型进行区分。

**Comment by Zado-Tan** [comment]
好的谢谢，了解了！
