### ISSUE TITLE
AttributeError: 'FlagReranker' object has no attribute 'encode'

### ISSUE THREAD

**Issue by shiztong** [FlagOpen/FlagEmbedding#637]
请教一下，想测评一下微调的Reranker，跑了eval_cross_encoder.py，发现代码里面计算相关性的时候，还是用的Embedding模型，这个有办法解决么

**Comment by staoxiao** [comment]
可能是mteb升级导致的，可以降低版本试试

**Comment by shiztong** [comment]
好的，mteb 降级到1.1.0 可以跑了，感谢
