### ISSUE TITLE
增量预训练后，相似度变得很高

### ISSUE THREAD

**Issue by zouzoutingting** [FlagOpen/FlagEmbedding#64]
如题，完全不相关的两个句子，相似度都会到0.9以上。
我跑了1 epoch，4000多条数据

**Comment by staoxiao** [comment]
可以把温度系数`temperature`调高点，比如0.02, 0.05。
另外，建议提高负样本的难度，可以通过bge模型进行检索得到一些难负样本。

**Comment by zouzoutingting** [comment]
监督微调还没有做，只是用领域数据做了增量预训练。
两个不相关的句子的相似度，变得很大。

**Comment by staoxiao** [comment]
预训练之后必须加上监督微调，预训练只能让模型的cls向量学习到领域内知识，但无法做样本进行区分。

**Comment by zouzoutingting** [comment]
明白了，多谢

**Comment by NLPJCL** [comment]
请问下，
1.用已经监督微调的bge模型在领域文本上继续预训练，是不是对bge模型在监督微调学习到的语义相似度的能力有一定的损失呢？
2.如果用bge模型在领域文本上预训练再进行领域微调，会比bge模型直接领域微调效果好吗？

**Comment by staoxiao** [comment]
1. 是的。预训练和监督学习目标是不一致的，预训练之后不能直接用来计算相似度。
2. 不一定。通常，如果下游领域上有比较多的高质量预训练数据和微调数据，那么预训练+微调能得到更好的效果。如果下游任务上的数据很少，建议直接微调，因为bge本身就包含了预训练和微调两阶段，有可能这个下游领域上的数据bge已经训练的不错了。

**Comment by NLPJCL** [comment]
感谢！
