### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

### ISSUE THREAD

**Issue by zeruiz99** [FlagOpen/FlagEmbedding#640]
when i am trying to finetune the layerwise reranker model, i use almost exact same instruction as provided:
torchrun --nproc_per_node {number of gpus} \
-m FlagEmbedding.llm_reranker.finetune_for_layerwise.run \
--output_dir {path to save model} \
--model_name_or_path openbmb/MiniCPM-2B-dpo-bf16 \
--train_data ./toy_finetune_data.jsonl \
--learning_rate 2e-4 \
--num_train_epochs 1 \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 16 \
--dataloader_drop_last True \
--query_max_len 512 \
--passage_max_len 512 \
--train_group_size 16 \
--logging_steps 1 \
--save_steps 2000 \
--save_total_limit 50 \
--ddp_find_unused_parameters False \
--gradient_checkpointing \
--deepspeed stage1.json \
--warmup_ratio 0.1 \
--bf16 \
--use_lora True \
--lora_rank 32 \
--lora_alpha 64 \
--use_flash_attn True \
--target_modules q_proj k_proj v_proj o_proj \
--start_layer 8 \
--head_multi True \
--head_type simple \
--lora_extra_parameters linear_head
###
but when i include gradient_checkpointing and deepspeed, it will raise backend_class = ProcessGroupNCCL(
ValueError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
when i delete them, the flash_attn will raise as ImportErrorcls._check_and_enable_flash_attn_2(: 
FlashAttention2 has been toggled on, but it cannot be used due to the following error: Flash Attention 2 is not available.
###
package version: flash_attn=2.5.6 torch=2.2.2 transformer=4.39.2 deepspeed=0.14.0 peft=0.10.0

**Comment by holyYodu** [comment]
@zeruiz99 请问这个问题解决了吗？
