### ISSUE TITLE
关于Finetune的一些小问题，没有early stop和best_model save

### ISSUE THREAD

**Issue by PNightOwlY** [FlagOpen/FlagEmbedding#65]
您好，仔细看了一下finetune的代码，代码内没有做evaluation，early stop或者是设置存最好的模型，请问是通过什么方式去判断finetune表现最好的checkpoints呢？

请问是看每 500 steps之后的train loss作为标准吗？

**Comment by staoxiao** [comment]
您好，目前微调代码里没有evaluation的部分，这块需要用户根据具体下游任务设置评估指标，也可以以C-MTEB里的相似任务进行评估。

**Comment by PNightOwlY** [comment]
明白，谢谢！
