### ISSUE TITLE
activation beacon beyond 400K

### ISSUE THREAD

**Issue by leezythu** [FlagOpen/FlagEmbedding#651]
你好 @namespace-Pt ,谢谢你这么棒的工作。
我用activation beacon模型测试了1000K（1M）的长度，使用512的压缩比：
`torchrun --nproc_per_node 8 -m main.eval_lm --data_root data --max_length 1000000 --beacon_ratio 512 --min_length 1000000 --enable_beacon --stride 0 --model_name_or_path ./activation-beacon-llama2-7b-chat`
结果ppl还不错，是7.496。
因此想和你交流下，为什么论文题目只提到了能到400K？感觉activation beacon在更长长度上也可以有较低的ppl。

**Comment by namespace-Pt** [comment]
Hi, 我们训练时支持的最大压缩率为128，没有做更大压缩率的实验，而400K是128压缩率能够支持的最大长度。另外，PPL仅是测评模型长文本性能的第一关，对于一些需要精确记忆的任务（passkey等），目前的模型在大压缩率下（>=32）并不能胜任。我们也在进一步改进方法，使其能够支持更高压缩率下的精准记忆，请期待我们后续模型更新。

**Comment by leezythu** [comment]
了解！谢谢！
