### ISSUE TITLE
Try to reproduce results on MIRACL dataset.

### ISSUE THREAD

**Issue by wxywb** [FlagOpen/FlagEmbedding#653]
I'm interesting the BGE-M3 results on MIRACL and try to reproduce it.
I found the MIRACL dataset corpus having following format
```json
{
    "docid": "39#0",
    "title": "Albedo", 
    "text": "Albedo (meaning 'whiteness') is the measure of the diffuse reflection of solar radiation out of the total solar radiation received by an astronomical body (e.g. a planet like Earth). It is dimensionless and measured on a scale from 0 (corresponding to a black body that absorbs all incident radiation) to 1 (corresponding to a body that reflects all incident radiation)."
}
```
for indexing the corpus, should I use title information(prepend to text to generate an embedding) or just inference the embedding only from text?

**Comment by hanhainebula** [comment]
In BGE-M3 paper, we use `content = f"{title}\n{text}"` to generate the embedding.
