### ISSUE TITLE
during computing score using reranker-v2-minicpm-layerwise, why using cutoff_layers will affect the result so large and why the finetuned model cannot use cutoff_layers

### ISSUE THREAD

**Issue by zeruiz99** [FlagOpen/FlagEmbedding#658]
When I first load my finetuned embedding model, and use reranker-v2-minicpm-layerwise to compute score for each QA pair, I have two questions:

1. when I finetuned reranker-v2-minicpm-layerwise to have another individual reranker model, it will show:
TypeError: MiniCPMForCausalLM.forward() got an unexpected keyword argument 'cutoff_layers'
for "outputs = self.model(**batch_inputs, output_hidden_states=True, cutoff_layers=cutoff_layers)" in FlagEmbedding/flag_reranker.py

2. when i use different cutoff_layers like 8, 18, 38 and when I do not have this parameter in my command, the result will have huge difference

**Comment by zeruiz99** [comment]
Loading adapter weights from model led to unexpected keys not found in the model:  ['lm_head.0.linear_head.weight', 'lm_head.1.linear_head.weight', 'lm_head.10.linear_head.weight', 'lm_head.11.linear_head.weight', 'lm_head.12.linear_head.weight', 'lm_head.13.linear_head.weight', 'lm_head.14.linear_head.weight', 'lm_head.15.linear_head.weight', 'lm_head.16.linear_head.weight', 'lm_head.17.linear_head.weight', 'lm_head.18.linear_head.weight', 'lm_head.19.linear_head.weight', 'lm_head.2.linear_head.weight', 'lm_head.20.linear_head.weight', 'lm_head.21.linear_head.weight', 'lm_head.22.linear_head.weight', 'lm_head.3.linear_head.weight', 'lm_head.4.linear_head.weight', 'lm_head.5.linear_head.weight', 'lm_head.6.linear_head.weight', 'lm_head.7.linear_head.weight', 'lm_head.8.linear_head.weight', 'lm_head.9.linear_head.weight'].

**Comment by 545999961** [comment]
1. If you want to finetune `reranker-v2-minicpm-layerwise`, you need to add an argument, `finetune_type=from_finetuned_model`, and after finetune, you need to merge the model use the following code:  https://github.com/FlagOpen/FlagEmbedding/tree/a55982a171be5b08cce8c377f6455ad0e5ffd1cc/FlagEmbedding/llm_reranker/merge
2. If you don't set `cutoff_layers `, it will be set as 40.
3. The comparison of scores between layers is meaningless; what matters is the comparison of scores between different samples within the same layer.

**Comment by zeruiz99** [comment]
> 1. If you want to finetune `reranker-v2-minicpm-layerwise`, you need to add an argument, `--finetune_type from_finetuned_model`, and after finetune, you need to merge the model use the following code:  https://github.com/FlagOpen/FlagEmbedding/tree/a55982a171be5b08cce8c377f6455ad0e5ffd1cc/FlagEmbedding/llm_reranker/merge
> 2. If you don't set `cutoff_layers `, it will be set as 40.
> 3. The comparison of scores between layers is meaningless; what matters is the comparison of scores between different samples within the same layer.

Sure, also, could you specify the version of transformers and flash_attn?

**Comment by 545999961** [comment]
`transformers==4.38.1`
`flash_attn==2.5.6`

**Comment by zeruiz99** [comment]
Another question is: do you have any recommendation script to evaluate the effect after reranking model using bge embedding model

**Comment by 545999961** [comment]
Was this error reported during fine-tuning or during inference? Can you provide more specific error information?

**Comment by zeruiz99** [comment]
> Was this error reported during fine-tuning or during inference? Can you provide more specific error information?

I fixed this issue.
But I got another typeerror when I use dense retrieval:
# 1. Generate Corpus Embedding
python step0-generate_embedding.py \
--encoder BAAI/bge-m3 \
--index_save_dir ./save_path \
--max_passage_length 512 \
--batch_size 256 \
--fp16 \
--add_instruction False \
--pooling_method cls \
--normalize_embeddings True

it returns:
TypeError: FlagModel.__init__() got an unexpected keyword argument 'passage_instruction_for_retrieval'

but i set add_instruction as False

**Comment by zeruiz99** [comment]
> > Was this error reported during fine-tuning or during inference? Can you provide more specific error information?
> 
> I fixed this issue. But I got another typeerror when I use dense retrieval:
> 
> # 1. Generate Corpus Embedding
> python step0-generate_embedding.py --encoder BAAI/bge-m3 --index_save_dir ./save_path --max_passage_length 512 --batch_size 256 --fp16 --add_instruction False --pooling_method cls --normalize_embeddings True
> 
> it returns: TypeError: FlagModel.**init**() got an unexpected keyword argument 'passage_instruction_for_retrieval'
> 
> but i set add_instruction as False

Maybe edit passage_instruction_for_retrieval=model_args.passage_instruction_for_retrieval if model_args.add_instruction else None in def get_model in step0 file to work only when add_instruction is true

**Comment by hanhainebula** [comment]
> > > Was this error reported during fine-tuning or during inference? Can you provide more specific error information?
> > 
> > 
> > I fixed this issue. But I got another typeerror when I use dense retrieval:
> > # 1. Generate Corpus Embedding
> > python step0-generate_embedding.py --encoder BAAI/bge-m3 --index_save_dir ./save_path --max_passage_length 512 --batch_size 256 --fp16 --add_instruction False --pooling_method cls --normalize_embeddings True
> > it returns: TypeError: FlagModel.**init**() got an unexpected keyword argument 'passage_instruction_for_retrieval'
> > but i set add_instruction as False
> 
> Maybe edit passage_instruction_for_retrieval=model_args.passage_instruction_for_retrieval if model_args.add_instruction else None in def get_model in step0 file to work only when add_instruction is true

Thank you for finding this bug. We have fixed this bug in [this commit](https://github.com/FlagOpen/FlagEmbedding/commit/f13c25d538436bc1be0c8baa9a8792a268dc05a7).

**Comment by zeruiz99** [comment]
> > > > Was this error reported during fine-tuning or during inference? Can you provide more specific error information?
> > > 
> > > 
> > > I fixed this issue. But I got another typeerror when I use dense retrieval:
> > > # 1. Generate Corpus Embedding
> > > python step0-generate_embedding.py --encoder BAAI/bge-m3 --index_save_dir ./save_path --max_passage_length 512 --batch_size 256 --fp16 --add_instruction False --pooling_method cls --normalize_embeddings True
> > > it returns: TypeError: FlagModel.**init**() got an unexpected keyword argument 'passage_instruction_for_retrieval'
> > > but i set add_instruction as False
> > 
> > 
> > Maybe edit passage_instruction_for_retrieval=model_args.passage_instruction_for_retrieval if model_args.add_instruction else None in def get_model in step0 file to work only when add_instruction is true
> 
> Thank you for finding this bug. We have fixed this bug in [this commit](https://github.com/FlagOpen/FlagEmbedding/commit/f13c25d538436bc1be0c8baa9a8792a268dc05a7).

Np
another question is how many gpu u used for evaluate?
i have done:
RuntimeError: CUDA error: peer mapping resources exhausted
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by hanhainebula** [comment]
> Np another question is how many gpu u used for evaluate? i have done: export CUDA_LAUNCH_BLOCKING=1 export CUDA_VISIBLE_DEVICE==0 and i tried to use 4 gpu, all will return as: RuntimeError: CUDA error: peer mapping resources exhausted Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

We usually use 8 GPUs for evaluation. 

For the `RuntimeError`, you can try `CUDA_VISIBLE_DEVICES=0,1,2,3 <cmd>`.
