### ISSUE TITLE
请问下，为什么预训练和微调的数据格式不一致？

### ISSUE THREAD

**Issue by asenasen123** [FlagOpen/FlagEmbedding#66]

**Comment by staoxiao** [comment]
预训练类似于bert的预训练流程，目标是通过句子向量还原句子文本，有文本数据就可以，不需要有监督的文本匹配数据。
微调需要文本对数据，目标是来拉近正样本对的距离，拉远负样本对的距离。

**Comment by asenasen123** [comment]
> 预训练类似于bert的预训练流程，目标是通过句子向量还原句子文本，有文本数据就可以，不需要有监督的文本匹配数据。 微调需要文本对数据，目标是来拉近正样本对的距离，拉远负样本对的距离。
明白，十分感谢！

**Comment by asenasen123** [comment]
请问下该模型支持fastchat框架吗？
