### ISSUE TITLE
llm-based reranker - config.json file

### ISSUE THREAD

**Issue by Rispo997** [FlagOpen/FlagEmbedding#662]
Hello! I have been trying to use your LLM-based reranker to classify a set of documents.
I ran the fine-tuning step of GEMMA with the following command line:
`CUDA_VISIBLE_DEVICES=2 torchrun --nproc_per_node 1 \
-m FlagEmbedding.llm_reranker.finetune_for_instruction.run \
--output_dir ./gemma/ \
--model_name_or_path google/gemma-2b \
--train_data ./train_data.json \
--learning_rate 2e-4 \
--num_train_epochs 5 \
--per_device_train_batch_size 8 \
--gradient_accumulation_steps 16 \
--dataloader_drop_last True \
--query_max_len 128 \
--passage_max_len 128 \
--train_group_size 16 \
--logging_steps 1 \
--save_steps 2000 \
--save_total_limit 50 \
--ddp_find_unused_parameters False \
--gradient_checkpointing \
--deepspeed stage1.json \
--warmup_ratio 0.1 \
--use_lora True \
--lora_rank 32 \
--lora_alpha 64 \
--use_flash_attn False \
--target_modules q_proj k_proj v_proj o_proj \
`
The problem is that when I try to load a checkpoint through the command:
`reranker = FlagLLMReranker('./gemma/, use_fp16=True)`
I get the error:
`does not appear to have a file named config.json`
Indeed in the checkpoint directory, there is only a file adapter_config.json, but no config.json.
Has this ever happened to you? Do you know how to generate the file or why it hasn't been generated? Thank you.

**Comment by 545999961** [comment]
The finetune result is a lora check point, you need to merge the model.
You can use the code here to merge the model FlagEmbedding/llm_reranker/merge/merge_base_model.py
