### ISSUE TITLE
help!!!!

### ISSUE THREAD

**Issue by khazic** [FlagOpen/FlagEmbedding#668]
你好 我出现了两个问题
1.我想知道在哪儿设置保存的check_point的save_steps的大小 我现在看是500保存一次 但我没看到源码在哪儿呢
2.我拿了我的数据去训 跑通了 但是loss从一开始就是0 这是为什么呢？我用了你们的demo数据跑了一下 是正常的0.几

**Comment by khazic** [comment]
我的数据里面  \n \t "" ''我都去掉了 还没去掉emoji  难道是emoji的影响吗？

**Comment by staoxiao** [comment]
1. 设置参数`--save_steps xxx`即可，更多参数可以参考https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.save_steps
2. 输出每一个step的loss看看（`--logging_steps 1`），如果是突然降到0，是模型训崩了，检查数据和学习率。如果从第一个step就是0，可能是任务太简单了，检查数据和提高batch size。

**Comment by staoxiao** [comment]
> 是的 我写了--save_steps 了 第二个问题 我的query跟pos是一样的 会不会就会造成这种情况呢？ 

那应该是任务太简单了

**Comment by khazic** [comment]
是的 我测试之后发现 是这个原因


Shitao Xiao ***@***.***> 于2024年4月10日周三 21:08写道：
