### ISSUE TITLE
negatives_cross_device 分布式梯度回传问题请教

### ISSUE THREAD

**Issue by YanshekWoo** [FlagOpen/FlagEmbedding#677]
## 场景
FlagEmbedding / baai_general_embedding / finetune

## 疑问：
negatives_cross_device部分的tensor是否无法进行梯度回传
我们注意到您通过dist.all_gather获取了其他进程上的tensor作negatives_cross_device，我理解这部分tensor是无法进行梯度回传的
而相反的 inbatch_neg 这部分是保留在计算图内可以进行梯度回传的
简言之，最终梯度回传的时候是否只有部分negative可以进行梯度回传（inbatch的部分），以及这样计算是否会对优化带来影响

## 代码位置：https://github.com/FlagOpen/FlagEmbedding/blob/4f3db6a6f505851461285e12af7fb66255f9c73b/FlagEmbedding/baai_general_embedding/finetune/modeling.py#L119

**Comment by staoxiao** [comment]
negatives_cross_device部分的tensor无法进行梯度回传。
但是，我们把query和passag都进行了broadcast。该显卡上自己生成的q和p的梯度上完整的（等于把所有显卡上q,p一起计算时的梯度），每张显卡之后会同步自己的梯度，就可以保证所有梯度的完整性。详情参考MoPQ: https://arxiv.org/pdf/2104.07858.pdf

**Comment by YanshekWoo** [comment]
> negatives_cross_device部分的tensor无法进行梯度回传。 但是，我们把query和passag都进行了broadcast。该显卡上自己生成的q和p的梯度上完整的（等于把所有显卡上q,p一起计算时的梯度），每张显卡之后会同步自己的梯度，就可以保证所有梯度的完整性。详情参考MoPQ: https://arxiv.org/pdf/2104.07858.pdf

感谢解答！疑问应该都理解了
这个工作也很棒，Figure 3很清晰，一看就get到了之前没考虑的点

**Comment by wxhheian** [comment]
hello,  请教一下
假设一共有两块GPU，GPU0和GPU1.  当前处在GPU0上，
我理解， 开启 negatives_cross_device 后，
1. 前向传播过程中，发生了dist_gather_tensor操作，用到了当前GPU0和GPU1上的正样本和负样本，计算得到loss, 并且每个GPU上的loss都是一样的
2. 但是后向传播的时候，由于发生了dist_gather_tensor操作，只有当前GPU下原本的q和p是可以计算梯度的，从其他GPU上broadcast过来的q和p是不能计算梯度的。 所以虽然每个GPU上的loss是一样的，但是也只计算了当前GPU上自己的q和p的梯度

不知道我怎么理解对吗？请指教 @staoxiao

**Comment by staoxiao** [comment]
@wxhheian ， 对的。每张卡计算自己q和p的梯度；所有GPU把梯度传播后，就可以得到所有q和p的梯度。
