### ISSUE TITLE
建议examples/search_demo去掉基于pyserini的BM25召回，直接使用BGE编码+Faiss

### ISSUE THREAD

**Issue by 1191000606** [FlagOpen/FlagEmbedding#68]
根据代码，examples/search_demo使用Cohere/wikipedia-22-12数据集的中文部分作为QA时的外源知识，其首先使用pyserini工具进行BM25召回，筛选出前1000个文档，然后使用Faiss工具对筛选出的文档进行排序。

首先Cohere/wikipedia-22-12数据集中含有大量政治敏感的wiki条目，其次我在实际测试的过程中发现pyserini包中的BM25工具类LuceneSearcher中文检索能力很差，无论使用pyserini中唯一预构建的中文维基索引文件zhwiki-paragraphs还是项目中自己构建的bm25_index，其都会优先返回政治敏感内容。这甚至导致后续BGE+Faiss排序的时候也只有这些无关内容。

我测试了一下，直接将Cohere/wikipedia-22-12中200w维基条目使用BGE编码存储，然后使用Faiss工具进行查询。每个query的用时完全在1s以内，这应该完全可以接受，并且原来使用BM25召回然后排序好像并没有多快。

然后可以考虑加一行代码做中文繁体到简体的转换。我使用的是zhconv.convert

**Comment by staoxiao** [comment]
感谢您的建议！目前的search_demo只是一个示例，还非常简陋，后面会考虑将其完善。
