### ISSUE TITLE
微调数据集预处理问题

### ISSUE THREAD

**Issue by Qingchen-Yu** [FlagOpen/FlagEmbedding#698]
您好！我正在按照您给出的数据集（T2-Ranking，DuReader，MedQA等数据集）复现您的微调实验。但是发现这些原始数据集的格式并不统一，想询问一下您这边有对应的代码或者方法，统一将这些数据处理成您给出的{"query": str, "pos": List[str], "neg":List[str]}格式吗？非常感谢！

**Comment by staoxiao** [comment]
您好，可以直接从https://huggingface.co/datasets/Shitao/bge-reranker-data和https://huggingface.co/datasets/Shitao/bge-m3-data下载其中的中文数据

**Comment by Qingchen-Yu** [comment]
好的！感谢您的分享！

**Comment by i1995wqh** [comment]
链接有包含列出来的英文数据吗？如果没有，是否也有对应的存放地址

> 您好，可以直接从[https://huggingface.co/datasets/Shitao/bge-reranker-data和https://huggingface.co/datasets/Shitao/bge-m3-data下载其中的中文数据](https://huggingface.co/datasets/Shitao/bge-reranker-data%E5%92%8Chttps://huggingface.co/datasets/Shitao/bge-m3-data%E4%B8%8B%E8%BD%BD%E5%85%B6%E4%B8%AD%E7%9A%84%E4%B8%AD%E6%96%87%E6%95%B0%E6%8D%AE)
