### ISSUE TITLE
怎么扩展输入文本的长度

### ISSUE THREAD

**Issue by yuanjie-ai** [FlagOpen/FlagEmbedding#7]
怎么扩展输入文本的长度

**Comment by staoxiao** [comment]
您好，目前bge模型限制的最大token数量为512。如果想要为更长文本建模，可以将文本切分为多个子段落，每段分别生成embedding，最后使用mean pooling的方式融合成一个向量。一些不同融合方式以及效果可以参考：https://arxiv.org/pdf/2305.13915.pdf

**Comment by supdizh** [comment]
赞刚好有相同问题

**Comment by xuyungit** [comment]
bge模型的token数如何计算？可以使用tiktoken吗？

**Comment by staoxiao** [comment]
> bge模型的token数如何计算？可以使用tiktoken吗？

可以使用Huggingface的AutoTokenizer来计算长度
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
length = len(tokenizer.encode("Hello world"))
```

**Comment by haoshan98** [comment]
> > bge模型的token数如何计算？可以使用tiktoken吗？
> 
> 可以使用Huggingface的AutoTokenizer来计算长度
> 
> ```
> from transformers import AutoTokenizer
> tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
> length = len(tokenizer.encode("Hello world"))
> ```

Working well, thanks!

**Comment by heshuguo** [comment]
> 您好，目前bge模型限制的最大token数量为512。如果想要为更长文本建模，可以将文本切分为多个子段落，每段分别生成embedding，最后使用mean pooling的方式融合成一个向量。一些不同融合方式以及效果可以参考：https://arxiv.org/pdf/2305.13915.pdf

@staoxiao 麻烦咨询下，假如token数超过512的，目前微调的代码不支持mean pooling的方式融合成一个向量吧，后续有计划支持吗？

**Comment by staoxiao** [comment]
> > 您好，目前bge模型限制的最大token数量为512。如果想要为更长文本建模，可以将文本切分为多个子段落，每段分别生成embedding，最后使用mean pooling的方式融合成一个向量。一些不同融合方式以及效果可以参考：https://arxiv.org/pdf/2305.13915.pdf
> 
> @staoxiao 麻烦咨询下，假如token数超过512的，目前微调的代码不支持mean pooling的方式融合成一个向量吧，后续有计划支持吗？

是的，mean pooling这种方式会对降低效果，只是一个可行的方式，最好的方式还是分成chunk分别检索。
后续会尝试扩大token最大限制。

**Comment by aliencaocao** [comment]
有没有可能通过position interpolation, RoPE或者Yarn类似的方法扩展？我发现在较长的文章中，bge-v1.5模型比openai的效果差很多，用的是纯英文经济方面的学术语料。

**Comment by staoxiao** [comment]
> 有没有可能通过position interpolation, RoPE或者Yarn类似的方法扩展？我发现在较长的文章中，bge-v1.5模型比openai的效果差很多，用的是纯英文经济方面的学术语料。 使用的是目前最好的mean pool，用token数量作为权重

bge没有适配过mean pooling，确实会很大的降低效果。position interpolation, RoPE或者Yarn这类属于相对位置编码，bge目前还是采用的绝对位置编码，无法直接应用，需要一定的微调，但确实是一种潜在的方案。我们近期也在计划拓展bge的最大长度，也欢迎大家贡献PR。

**Comment by staoxiao** [comment]
发布了新版模型[BGE-M3](https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/BGE_M3), 支持多语言、长文本和多种检索模式。欢迎使用并给出反馈意见。
