### ISSUE TITLE
关于loss的计算

### ISSUE THREAD

**Issue by zhaobinNF** [FlagOpen/FlagEmbedding#70]
您好，我在看代码的过程中，发现loss的计算有点奇怪，于是就print出来了。我的运行参数如下：
torchrun --nproc_per_node 1 \
-m FlagEmbedding.baai_general_embedding.finetune.run \
--output_dir /work/cache/zhaobin/code/embedding_model_training/FlagEmbedding/output_21 \
--model_name_or_path /work/cache/zhaobin/code/vector_embedding/bge-large-zh \
--train_data /work/share/lvhm/embedding_training_data/finetune_gongjijin_0825_text_train.jsonl \
--learning_rate 1e-5 \
--num_train_epochs 5 \
--per_device_train_batch_size 2 \
--dataloader_drop_last True \
--normlized True \
--temperature 0.01 \
--query_max_len 128 \
--passage_max_len 512 \
--train_group_size 8

但是会发现此时target 输出显示为tensor([0, 8], device='cuda:0')，按我的理解应该是
tensor（[[1, 0, ..., 0],[1, 0, ..., 0]]）
![image](https://github.com/FlagOpen/FlagEmbedding/assets/72935067/f30d68f8-6bf3-4601-84d8-5fcd90197919)
,望解惑，谢谢

**Comment by staoxiao** [comment]
您好，loss使用的是交叉熵loss进行计算，target是指正样本所在的位置，比如这里，对于第一个和第二个query，正样本位置就是第1个（索引为0）和第9（索引为8）个文档。
