### ISSUE TITLE
OSError: [Errno 39] Directory not empty: 'embed_finetuning/tmp-checkpoint-1000' -> 'embed_finetuning/checkpoint-1000'

### ISSUE THREAD

**Issue by shrijayan** [FlagOpen/FlagEmbedding#704]
# Error
```
{'loss': 0.0033, 'learning_rate': 9.84883368676159e-06, 'epoch': 0.08}
  2%|██▌                                                                                                                                                                      | 1000/66020 [45:17<49:19:56,  2.73s/it]04/19/2024 08:08:52 - INFO - sentence_transformers.SentenceTransformer -   Save model to embed_finetuning/tmp-checkpoint-1000
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/FlagEmbedding/baai_general_embedding/finetune/run.py", line 111, in <module>
    main()
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/FlagEmbedding/baai_general_embedding/finetune/run.py", line 102, in main
    trainer.train()
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/transformers/trainer.py", line 1914, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/transformers/trainer.py", line 2274, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/transformers/trainer.py", line 2383, in _save_checkpoint
    os.rename(staging_output_dir, output_dir)
OSError: [Errno 39] Directory not empty: 'embed_finetuning/tmp-checkpoint-1000' -> 'embed_finetuning/checkpoint-1000'
  2%|██▌                                                                                                                                                                      | 1000/66020 [45:21<49:09:23,  2.72s/it]
[2024-04-19 08:09:01,065] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1216377 closing signal SIGTERM
[2024-04-19 08:09:01,530] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1216376) of binary: /home/karrtik/Projects/FlagEmbedding/flagembedding/bin/python3.10
Traceback (most recent call last):
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

# Training
```
torchrun --nproc_per_node 2 \
-m FlagEmbedding.baai_general_embedding.finetune.run \
--output_dir embed_finetuning \
--model_name_or_path BAAI/bge-large-en-v1.5 \
--train_data converted_data.jsonl \
--learning_rate 1e-5 \
--fp16 \
--num_train_epochs 5 \
--per_device_train_batch_size 8 \
--dataloader_drop_last True \
--normlized True \
--temperature 0.02 \
--query_max_len 64 \
--passage_max_len 256 \
--train_group_size 2 \
--negatives_cross_device \
--logging_steps 10 \
--save_steps 1000 \
--query_instruction_for_retrieval "" 
```

**Comment by staoxiao** [comment]
According to the log, you can try to change the path to save model (`--output_dir`)

**Comment by shrijayan** [comment]
> According to the log, you can try to change the path to save model (`--output_dir`)

First time it stopped at 
```
OSError: [Errno 39] Directory not empty: 'embed_finetuning/tmp-checkpoint-2000' -> 'embed_finetuning/checkpoint-2000'
```

So only I change the name of the path, but under the same folder.

But again the same issue raised.

**Comment by staoxiao** [comment]
Can you provide the version of your transformers, sentence-transformers, and torch?

**Comment by shrijayan** [comment]
> Can you provide the version of your transformers, sentence-transformers, and torch? We need these to reproduce your error.

transformers - 4.36.0
sentence-transformers - 2.6.0
torch - 2.2.2

**Comment by 545999961** [comment]
You need to update you transformers version.
You can `pip install -U transformers` or `pip install transformers==4.38.1`.

**Comment by shrijayan** [comment]
> You need to update you transformers version. You can `pip install -U transformers` or `pip install transformers==4.38.1`.

[The new version of Transformers may pose issues for fine-tuning. If you encounter problems, you can try to downgrade to versions 4.33-4.36.](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune#:~:text=The%20new%20version%20of%20Transformers%20may%20pose%20issues%20for%20fine%2Dtuning.%20If%20you%20encounter%20problems%2C%20you%20can%20try%20to%20downgrade%20to%20versions%204.33%2D4.36.)

**Comment by shrijayan** [comment]
@staoxiao @545999961 Any help?

**Comment by staoxiao** [comment]
@shrijayan, please upgrade your transformers package.

`The new version of Transformers may pose issues for fine-tuning. If you encounter problems, you can try to downgrade to versions 4.33-4.36.` This comment just says that you can try to degrade transformers when there is an error in fine-tuning with the latest transformers.

**Comment by shrijayan** [comment]
> @shrijayan, please upgrade your transformers package.
> 
> `The new version of Transformers may pose issues for fine-tuning. If you encounter problems, you can try to downgrade to versions 4.33-4.36.` This comment just says that you can try to degrade transformers when there is an error in fine-tuning with the latest transformers.

Thank you! updated the Transformers and started the training, let me know If the issue continuous.

**Comment by shrijayan** [comment]
I was using the transformers==4.36.1 which created this issue.

> # Error
> ```
> {'loss': 0.0033, 'learning_rate': 9.84883368676159e-06, 'epoch': 0.08}
>   2%|██▌                                                                                                                                                                      | 1000/66020 [45:17<49:19:56,  2.73s/it]04/19/2024 08:08:52 - INFO - sentence_transformers.SentenceTransformer -   Save model to embed_finetuning/tmp-checkpoint-1000
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/FlagEmbedding/baai_general_embedding/finetune/run.py", line 111, in <module>
>     main()
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/FlagEmbedding/baai_general_embedding/finetune/run.py", line 102, in main
>     trainer.train()
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
>     return inner_training_loop(
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/transformers/trainer.py", line 1914, in _inner_training_loop
>     self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/transformers/trainer.py", line 2274, in _maybe_log_save_evaluate
>     self._save_checkpoint(model, trial, metrics=metrics)
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/transformers/trainer.py", line 2383, in _save_checkpoint
>     os.rename(staging_output_dir, output_dir)
> OSError: [Errno 39] Directory not empty: 'embed_finetuning/tmp-checkpoint-1000' -> 'embed_finetuning/checkpoint-1000'
>   2%|██▌                                                                                                                                                                      | 1000/66020 [45:21<49:09:23,  2.72s/it]
> [2024-04-19 08:09:01,065] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1216377 closing signal SIGTERM
> [2024-04-19 08:09:01,530] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1216376) of binary: /home/karrtik/Projects/FlagEmbedding/flagembedding/bin/python3.10
> Traceback (most recent call last):
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
>     return f(*args, **kwargs)
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
>     run(args)
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
>     elastic_launch(
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/home/karrtik/Projects/FlagEmbedding/flagembedding/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ```

# Solution

```
Use transformers==4.40.1 Which will solve the issue.
```
