### ISSUE TITLE
Classifcation head

### ISSUE THREAD

**Issue by drewskidang** [FlagOpen/FlagEmbedding#705]
is there a way to add a classifcation head to the model.. tried intergrating M3E with sefit but kept running out of memory

**Comment by staoxiao** [comment]
You can use the scripts from huggingface: https://github.com/huggingface/transformers/tree/main/examples/pytorch/text-classification.
It uses huggingface trainer to train the classifcation model, so you can set '--fp16' and '--grandient_checkpointing' to reduce the memory cost.

**Comment by drewskidang** [comment]
thank you!!
