### ISSUE TITLE
关于基于retroMAE pre-train 的问题

### ISSUE THREAD

**Issue by runwean** [FlagOpen/FlagEmbedding#71]
您好，想请教以下两个问题：
1、执行pretrain，使用retroMAE方法，我看了script需要导入模型文件--model_name_or_path BAAI/bge-large-en，那我是不是可以理解为这里的pre-trian其实是基于已经pretrain+fine-tune之后的bge-large-en模型进行continual pre-tain （二次预训练）？

2、因为想改变向量的维度（原始为1024），这样意味着原始模型的结构hidden layer的维度要变化，因此需要从0开始预训练，这里想问问代码是否支持从0开始预训练？如果不可以，若想改变embedding的表示维度，还有其他方法吗？

感谢解答～

**Comment by staoxiao** [comment]
1. 是的，可以从bge起预训练，也可以从其他bert/roberta类模型起预训练。
2. 支持的，可以不传入model_name_or_path，传入config_name和tokenizer_name，这样模型会从0初始化。但这样训练消耗会大一些。
微调的时候，改变embedding的表示维度可以在bge模型后面加一个线性层，直接压缩向量的维度，再计算对比学习的loss，这样训练消耗小。但目前微调代码里暂时没有添加此向量压缩的功能，您需要自己实现一下，也欢迎提PR。

**Comment by runwean** [comment]
非常感谢您详细的回答👍

这里改变维度可以压缩也可以扩充，不知道您之前是否验证过如果将维度由1024扩大到比如4096是否能够有更好/更差的表征效果？我们的场景属于垂直领域，这种情况下是不是没有必要再扩大表征维度了（因为相对于通用向量表征，场景更小数据更少）？

**Comment by staoxiao** [comment]
如果训练充分的化，更大的维度肯定会带来更好的效果，但也会给检索时带来更大的计算开销。这是一个效率和效果的权衡。
但确实，如果只是在模型最后增加一个线性层增大维度，效果提升不会太明显。建议优先考虑提升微调数据数量和质量。
