### ISSUE TITLE
最新部署的bge-reranker-v2-m3模型，占用的显存会持续增加并不会释放

### ISSUE THREAD

**Issue by yaoyasong** [FlagOpen/FlagEmbedding#712]
部署了bge-reranker-v2-m3做精排的服务，运行一段时间后监控到显存会一直增加，不会自动释放，必须重启服务才能释放。
请问有什么方法能够自动释放占用的显存吗？

**Comment by staoxiao** [comment]
可以参考 https://zhuanlan.zhihu.com/p/497192910

**Comment by password36** [comment]
解决了么？我也遇到这个问题了，随着reranker调用次数的增加，显存不断上涨，加了empty_cache也没啥效果

**Comment by yaoyasong** [comment]
0.10.3版本显存可以释放

**Comment by wangyanyan66** [comment]
> 0.10.3版本显存可以释放

请问这是什么版本，对应的FlagEmbedding应该是哪个版本？

**Comment by kennard520** [comment]
这种部署当时支持多线程调用吗？

**Comment by Homura2333** [comment]
> 0.10.3版本显存可以释放

你好，请问这是什么的版本？
