### ISSUE TITLE
How do I evaluates the miracl dataset with the Ndcg@10 metric?

### ISSUE THREAD

**Issue by daegonYu** [FlagOpen/FlagEmbedding#714]
Is there any code that evaluates the miracl dataset with the Ndcg@10 metric? Or, I know that in order to evaluate Ndcg on the miracl dataset, the similarity between positives and negatives needs to be labeled. How do I know how to do labeling?

**Comment by staoxiao** [comment]
You can refer to: https://github.com/castorini/pyserini?tab=readme-ov-file . And the evaluation of bge-m3 will be integrated into this repo in the future.
