### ISSUE TITLE
BGEM3FlagModel vs FlagModel

### ISSUE THREAD

**Issue by manestay** [FlagOpen/FlagEmbedding#717]
Had a quick clarification for the classes `FlagEmbedding.BGEM3FlagModel` and `FlagEmbedding.FlagModel`. Will they produce equivalent results if loading the model `BAAI/bge-m3`?
I ask because there's an inconsistency with the README example:
https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/BGE_M3#generate-embedding-for-text
and the MKQA reproduction code:
https://github.com/FlagOpen/FlagEmbedding/blob/34d24e85e010176a35047bb66cb79a1a944e625f/C_MTEB/MKQA/dense_retrieval/step0-generate_embedding.py#L68

**Comment by manestay** [comment]
Thanks, that makes sense! Suppose I want to do both hybrid+sparse at the same time.

**Comment by hanhainebula** [comment]
Yes, you can set `return_dense=True` and `return_sparse=True` to generate the dense & sparse embedding at the same time. You need to make some minor modifications to the code in the script:

https://github.com/FlagOpen/FlagEmbedding/blob/34d24e85e010176a35047bb66cb79a1a944e625f/C_MTEB/MKQA/sparse_retrieval/step0-encode_query-and-corpus.py#L134
