### ISSUE TITLE
MKQA reproduction for sparse retrieval crashes due to negative QID

### ISSUE THREAD

**Issue by manestay** [FlagOpen/FlagEmbedding#718]
I am following the MKQA reproduction, and I'm getting an error at "step 3 sparse retrieval". I ran `1. Generate Query and Corpus Sparse Vector`  successfully.  When I run `2. Output Search Results`, I get an error:

The error happens in Pyserini:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ".../pyserini/search/lucene/__main__.py", line 152, in <module>
    query_iterator = get_query_iterator(args.topics, TopicsFormat(args.topics_format))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyserini/query_iterator.py", line 188, in get_query_iterator
    return mapping[topics_format].from_topics(topics_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyserini/query_iterator.py", line 109, in from_topics
    return cls(topics, order)
           ^^^^^^^^^^^^^^^^^^
  File ".../pyserini/query_iterator.py", line 45, in __init__
    self.order = order if order else sorted(topics.keys())
                                     ^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
```

I'm using `pyserini=0.25.0`.  The error occurs the ids for the [MKQA](https://huggingface.co/datasets/mkqa) entries can be negative, which makes pyserini load the IDs as strings instead of ints, causing a crash. I verified that if `-` is removed from the TSV, then there is no crash.

Let me know what I should do to fix this issue. Were you, the authors, able to run all steps for sparse retrieval without this error? Thank you.

**Comment by hanhainebula** [comment]
We also encountered this error when performing sparse retrieval. As you said, the error occurs the ids for the [MKQA](https://huggingface.co/datasets/mkqa) entries can be negative, which makes pyserini load the IDs as strings instead of ints, causing a crash. 

A possible solution is to modify the code [here](https://github.com/castorini/pyserini/blob/master/pyserini/query_iterator.py#L91) in pyserini:

```python
# From 
try:
    topics = get_topics_with_reader('io.anserini.search.topicreader.TsvIntTopicReader', topics_path)
except ValueError as e:
    topics = get_topics_with_reader('io.anserini.search.topicreader.TsvStringTopicReader', topics_path)

# to
topics = get_topics_with_reader('io.anserini.search.topicreader.TsvStringTopicReader', topics_path)
```

Modifying qids in MKQA is another possible solution. Just make sure that there are no duplicate qids.

**Comment by manestay** [comment]
Appreciate the quick response! That fix worked for me, and I suppose this issue can be better raised in the Pyserini issue page.

**Comment by hanhainebula** [comment]
We updated the qids in MKQA test data in [this commit](https://huggingface.co/datasets/Shitao/bge-m3-data/commit/a69db8b86e9c1767d193ee0de95e5c4001a71eae) to avoid this issue. The only change is to add the prefix `mkqa_` to each qids. Now you can try not modifying the code of pyserini to see if this error still occurs.

**Comment by manestay** [comment]
Yep it works. Appreciate the fast responses again! Looking forward to using M3 embeddings for my own research.
