### ISSUE TITLE
可以指定运行在哪张GPU上吗

### ISSUE THREAD

**Issue by Leekinxun** [FlagOpen/FlagEmbedding#719]
目前看上去是所有卡都会用到，我希望集中在1～2张卡上运行，该如何操作

**Comment by 545999961** [comment]
可以通过设置`CUDA_VISIBLE_DEVICES`实现，比如`CUDA_VISIBLE_DEVICES=2,3 python test.py`是指定使用2号卡和3号卡，如果在python代码里设置可以这样：`os.environ["CUDA_VISIBLE_DEVICES"] = "2,3"`

**Comment by Leekinxun** [comment]
> 可以通过设置`CUDA_VISIBLE_DEVICES`实现，比如`CUDA_VISIBLE_DEVICES=2,3 python test.py`是指定使用2号卡和3号卡，如果在python代码里设置可以这样：`os.environ["CUDA_VISIBLE_DEVICES"] = "2,3"`

确实有效，感谢！！
