### ISSUE TITLE
怎么提交自己训练模型预测的结果到MTEB上

### ISSUE THREAD

**Issue by Young1993** [FlagOpen/FlagEmbedding#72]
您好，我基于你们的模型进行了fine-tune，我想知道我跑出来了预测结果之后，怎么才能在https://huggingface.co/spaces/mteb/leaderboard 中文的leaderboard上显示结果呢？
我看英文的只要有READE.md文件就行了

跑中文的生成的zh_results.md该怎么提交呢？

**Comment by staoxiao** [comment]
我们这边是将结果传到了https://huggingface.co/datasets/mteb/results上。不太清楚中文目前是否支持README.md文件，您可以在https://github.com/embeddings-benchmark/mteb/tree/main 上提issue询问其他方式。
