### ISSUE TITLE
Visualized-BGE 每encode一次都会使内存持续增长，最终将内存撑爆

### ISSUE THREAD

**Issue by songsa1** [FlagOpen/FlagEmbedding#720]
我将Visualized-BGE封装在flask中用来提供embedding服务，但是发现没生成一次文本或图片的嵌入，都会使内存占用增大一些，最终撑爆内存。
请帮忙看看这种情况是否存在，或者我的代码是否存在问题。
这是我的代码：
import os
import time
import traceback
from datetime import datetime
from flask import Flask
from flask import request, jsonify
import logging
from logging.handlers import RotatingFileHandler
from FlagEmbedding.visual.modeling import Visualized_BGE

model = Visualized_BGE(model_name_bge = "bge-m3", model_weight="bge-visualized/Visualized_m3.pth")
model.eval()

def make_dir(make_dir_path):
    path = make_dir_path.strip()
    if not os.path.exists(path):
        os.makedirs(path)
def setup_log(log_dir_name):
    # 日志地址
    log_dir_name = log_dir_name
    # 文件名，以日期作为文件名
    log_file_name = 'logger-' + time.strftime('%Y-%m-%d', time.localtime(time.time())) + '.log'
    # 创建日志文件
    log_file_folder = log_dir_name
    make_dir(log_file_folder)
    log_file_str = log_file_folder + os.sep + log_file_name

    # 默认日志等级的设置
    logging.basicConfig(level=logging.INFO)
    # 创建日志记录器，指明日志保存路径,每个日志的大小，保存日志的上限
    file_log_handler = RotatingFileHandler(log_file_str, maxBytes=1024 * 1024, backupCount=30, encoding='UTF-8')
    # 设置日志的格式                   发生时间    日志等级     日志信息文件名      函数名          行数        日志信息
    formatter = logging.Formatter('%(asctime)s__%(levelname)s__%(filename)s__%(funcName)s__%(lineno)d__%(message)s')
    # 将日志记录器指定日志的格式
    file_log_handler.setFormatter(formatter)

    # 日志等级的设置
    # file_log_handler.setLevel(logging.WARNING)

    return file_log_handler

app = Flask(__name__)
app.logger.addHandler(setup_log('.'))
logger = app.logger

@app.route('/get_bge_embedding', methods=['POST'])
def get_bge_embedding_api():  # 
    if request.method == 'POST':
        data = request.get_json()
        img_datas = data.get("datas", [])
        img_embeddings = []
        for img_data in img_datas:
            try:
                path = img_data.get("path", "")
                text = img_data.get("text", "")
                if os.path.exists(path) and text:
                    img_embedding = model.encode(image=path, text=text)
                    img_embedding = img_embedding.tolist()
                elif os.path.exists(path):
                    img_embedding = model.encode(image=path)
                    img_embedding = img_embedding.tolist()
                elif text:
                    img_embedding = model.encode(text=text)
                    img_embedding = img_embedding.tolist()
                else:
                    img_embedding = [0 for i in range(1024)]
            except:
                logger.error(traceback.format_exc())
                img_embedding = [0 for i in range(1024)]
            img_embeddings.append(img_embedding)
        return jsonify({'img_embeddings': img_embeddings})

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8888, processes=True)

**Comment by JUNJIE99** [comment]
我这边没遇到过这类问题，代码的话看模型调用方法也没看出什么问题，或者您尝试一下每次调用API后手动删除一下变量或者`torch.cuda.empty_cache()`

**Comment by songsa1** [comment]
请问您说的手动删除一下变量指的是什么呢？每一次请求都重新加载模型吗？
另外，请问您是否可以使用我提供的代码在cpu上尝试复现一下呢？我这边目前是必现的。
麻烦您看看，这个问题蛮严重的，谢谢您了

**Comment by songsa1** [comment]
已经解决了

**Comment by huangjeake** [comment]
应该是只使用了CPU,没有使用GPU

**Comment by FoolishMao** [comment]
> 请问您说的手动删除一下变量指的是什么呢？每一次请求都重新加载模型吗？ 另外，请问您是否可以使用我提供的代码在cpu上尝试复现一下呢？我这边目前是必现的。 麻烦您看看，这个问题蛮严重的，谢谢您了

大佬，你怎么解决的？
