### ISSUE TITLE
关于领域专业术语在向量召回命中率较低的问题

### ISSUE THREAD

**Issue by ListenZen** [FlagOpen/FlagEmbedding#726]
您好，我这里有2个问题请教一下
1. 我们这边有很多领域专业术语，例如AAB是个术语，召回的时候命中很多AB的chunk，如果我想在tokenzier中添加tokenizer后微调，这个对于dense embedding生效吗，还是只对multi vector embedding生效？
2. 对于领域专业术语问答的dense embedding训练，QA更好还是QQ更好，我们的应用场景肯定是QA，但是A往往又会比较长，而且不同Q对应的A的长度差距比较大

**Comment by staoxiao** [comment]
1. 对dense embedding也生效的。
2. 这个跟数据场景关系比较大，没有定论。以实验结果为主，哪个最后效果好用哪个。

**Comment by ListenZen** [comment]
好的，谢谢！
关于添加special token，是不是我在添加完这些token之后，还需要拿这些token相关的QA对进行微调？

**Comment by staoxiao** [comment]
1. 是的。添加完后模型新增了一部分参数，最好微调一下。
2. 越多越好
