### ISSUE TITLE
我遇到了微调的列表越界错误

### ISSUE THREAD

**Issue by haldon98** [FlagOpen/FlagEmbedding#73]
![image](https://github.com/FlagOpen/FlagEmbedding/assets/142977056/dc1c511c-c4f2-4ce2-84da-5ee5d1da3c02)
你好，如图，我遇到了错误，我的参数是：torchrun --nproc_per_node 1 -m FlagEmbedding.baai_general_embedding.finetune.run --output_dir ./models --model_name_or_path /mnt/workspace/FlagEmbedding/bge-large-zh --train_data train.json --learning_rate 3e-5 --num_train_epochs 5 --per_device_train_batch_size 120 --dataloader_drop_last True --normlized True --temperature 0.01 --query_max_len 32 --passage_max_len 128 --train_group_size 2 \--negatives_cross_device 

期待您的解答~

**Comment by staoxiao** [comment]
您好，是random.choice(self.dataset[item]['pos'])出错了，应该是数据存在问题，有些数据的'pos'列表为空，即没有正样本，需要检查一下数据。

**Comment by staoxiao** [comment]
取决于per_device_train_batch_size 和query_max_len， passage_max_len， 可以根据数据的实际长度设置max_len，然后调整batch size以让其运行。同时，可以设置`--fp16`减小显存。

**Comment by haldon98** [comment]
好的，谢谢您！
