### ISSUE TITLE
BGEM3的Pre-train阶段的疑惑

### ISSUE THREAD

**Issue by Cha-01** [FlagOpen/FlagEmbedding#734]
阅读技术报告的过程中有两个疑问：

1. 在技术报告中，3.3节末尾提到“Firstly, the text encoder is pre-trained with the massive unsupervised data, where only the dense retrieval is trained inthe basic form of contrastive learning.”，这个过程是如何从无监督数据中确定正负样例以完成对比学习的呢？

2. 模型的总体训练过程是”RetroMAE + Unsup + Fine-tune“，如果要用自己的数据进行预训练时，是要进行RetroMAE+Unsup过程还是只有Unsup过程呢？

求佬解惑。

**Comment by staoxiao** [comment]
1. 可以参考论文C-Pack: Packaged Resources To Advance General Chinese Embedding。使用的是数据中的结构，如标题-正文
2. 都可以。数据量大可以都做，否则建议只跑Unsup

**Comment by Cha-01** [comment]
感谢！请问使用examples/pretrain/README中方法预训练时对应的是哪个过程呢？

**Comment by staoxiao** [comment]
> 感谢！请问使用examples/pretrain/README中方法预训练时对应的是哪个过程呢？

RetroMAE

**Comment by Cha-01** [comment]
感谢解答

**Comment by Cha-01** [comment]
还请问一下examples/fineturn/README中的微调对应的是哪些过程？是Unsup + Fine-tune吗？

**Comment by staoxiao** [comment]
Unsup或Fine-tune。这两者训练方式一致，只是数据不一样。
