### ISSUE TITLE
一些微调数据集的问题

### ISSUE THREAD

**Issue by yanzhang404** [FlagOpen/FlagEmbedding#755]
请问如果我的query是“XXX的损失率”， pos为“损失率”， 这样的微调效果如何呢，以及可以选择“损失量”这种词作为neg吗，还是选择完全不相关的词作为neg，谢谢您的解答

**Comment by staoxiao** [comment]
@yanzhang404 , I can't be certain about the impact on performance using it as a negative sample; it depends on your downstream task. Fine-tuning data should ideally match the downstream scenario as much as possible.

**Comment by yanzhang404** [comment]
感谢您的回答，我的下游任务是找到长句中的关键词，就像上面那样，当我的query是“XXX的损失率”时，应该返回“损失率”而不是“损失量”。
