### ISSUE TITLE
No sentence-transformers model found with name /root/***/result_finetune. Creating a new one with MEAN pooling.

### ISSUE THREAD

**Issue by asenasen123** [FlagOpen/FlagEmbedding#76]
请问下微调后怎么会出现这个提示，对最终微调结果影响大吗？

**Comment by staoxiao** [comment]
您好，加载方式存在问题，影响会很大，这是因为微调默认使用的是cls pooling: `--sentence_pooling_method cls`， 但sentence transfomers默认使用mean pooling。需要设置sentence transfomers的pooling方式，可以参考 https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune#3-load-your-model 中sentence_transformers的加载方式。

**Comment by asenasen123** [comment]
> 您好，加载方式存在问题，影响会很大，这是因为微调默认使用的是cls pooling: `--sentence_pooling_method cls`， 但sentence transfomers默认使用mean pooling。需要设置sentence transfomers的pooling方式，可以参考 https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/finetune#3-load-your-model 中sentence_transformers的加载方式。

感谢您的回答。还有一个问题想请教：对于微调后的模型，该如何构建下游任务的评估集，来对微调后的模型进行评测呢？（下游任务的评测数据集格式应该是什么样的？和C_MTEB的格式保持一致吗？）

**Comment by asenasen123** [comment]
https://huggingface.co/spaces/mteb/leaderboard 请问下，排行榜的评价指标是ndcg@10，数值大小不应该是0-1之间吗？

**Comment by staoxiao** [comment]
您好，目前使用的都是mteb的评测代码，可以参考：https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/C_MTEB/tasks/Retrieval.py 构建自己的测试数据，新建一个测试任务。也可以参考一些其他库的测试流程，比如：https://github.com/texttron/tevatron/tree/main/examples/coCondenser-marco 。
ndcg@10是再0-1之间，榜单上的结果都是乘以100之后的数值。

**Comment by asenasen123** [comment]
> 您好，目前使用的都是mteb的评测代码，可以参考：https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/C_MTEB/tasks/Retrieval.py 构建自己的测试数据，新建一个测试任务。也可以参考一些其他库的测试流程，比如：https://github.com/texttron/tevatron/tree/main/examples/coCondenser-marco 。 ndcg@10是再0-1之间，榜单上的结果都是乘以100之后的数值。

请问下，如果参考mteb的评测代码，我的数据格式也要弄成类似于C-MTEB/CovidRetrieval和C-MTEB/CovidRetrieval-qrels这两份文件的形式吗？

**Comment by staoxiao** [comment]
可以参考代码https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/C_MTEB/tasks/Retrieval.py里的load_retrieval_data函数，基于自己的数据写一个加载数据的函数，只要可以返回corpus, queries, relevant_docs三个数据就可以

**Comment by asenasen123** [comment]
微调的json文件格式：{"query": str, "pos": List[str], "neg":List[str]}。请问下，如果“pos”或者“neg”中的样本语料本身有包含“、”等这些特殊字符的话，需要在语料库中使用转义字符吗？

**Comment by staoxiao** [comment]
需要的，否则加载数据的时候可以会出现格式错误。
可以使用json库进行存储，会自动加上转义字符：
```
line = {'query':'a', 'pos': ['fd'], 'neg':['fds']}
f.write(json.dumps(line)+'\n')
```

**Comment by asenasen123** [comment]
> 需要的，否则加载数据的时候可以会出现格式错误。 可以使用json库进行存储，会自动加上转义字符：
> 
> ```
> line = {'query':'a', 'pos': ['fd'], 'neg':['fds']}
> f.write(json.dumps(line)+'\n')
> ```

torchrun --nproc_per_node {number of gpus} \
-m FlagEmbedding.baai_general_embedding.finetune.run请问下，您的模块里没有对转义字符进行处理吧？

**Comment by staoxiao** [comment]
使用的是datasets的load_datasets进行的数据加载，其支持对json的读取

**Comment by asenasen123** [comment]
> 



> 使用的是datasets的load_datasets进行的数据加载，其支持对json的读取

意思是您的微调指令里使用的是load_datasets进行数据加载，我使用您的微调指令的话，就不需要考虑转义字符的问题了吧？

**Comment by staoxiao** [comment]
是的
