### ISSUE TITLE
关于C-MTEB评测

### ISSUE THREAD

**Issue by Saicat** [FlagOpen/FlagEmbedding#78]
C-MTEB中包含有classification这样需要训练的任务，我看eval_C-MTEB.py中似乎没有涉及到训练的部分，请问是怎么做这个评测的呢

**Comment by staoxiao** [comment]
C-MTEB是基于mteb代码开发的，可以参考mteb中的评测：https://github.com/embeddings-benchmark/mteb/blob/main/mteb/evaluation/evaluators/ClassificationEvaluator.py
