### ISSUE TITLE
question about finetuning 

### ISSUE THREAD

**Issue by slpmee** [FlagOpen/FlagEmbedding#781]
Hi, 
I am trying to finetune baai-general-embedding model using my own data.
I followed finetuning tutorial in this repository. 
the result was not good and the accuracy was worse than the original version.
I didn't use "query_instruction_for_retrieval " parameter and set it to "".
Does this parameter affect to the model performance?

**Comment by staoxiao** [comment]
The instruction has little influence. The most important thing is the data, so you should check the quality of your data.
