### ISSUE TITLE
bge m3训练数据中mMARCO-zh数据集负样本构建

### ISSUE THREAD

**Issue by AugustLHHHHHH** [FlagOpen/FlagEmbedding#785]
hi，您好，

我在huggingface上下载了您的bge-m3-data 数据集，https://huggingface.co/datasets/Shitao/bge-m3-data
想请教一下这其中的mMARCO-zh负样本是如何构建的呢？请问是原始英文数据集提供的吗还是用您提供的hn_mine.py构建
谢谢

**Comment by staoxiao** [comment]
The negatives are mined by our script: hn_mine.py.

**Comment by AugustLHHHHHH** [comment]
> mined

感谢您的回复
在原始的多语言版本的数据中，https://microsoft.github.io/msmarco/, 一个问题对应一个负样本
![image](https://github.com/FlagOpen/FlagEmbedding/assets/109325850/cdb6828f-3e06-4333-97a2-a40c4cd9be54)

通过hn_mine.py挖掘更多负样本时，范围是从input_file的所有neg中选择的吗？还是其他呢？
另外，candidate_pool可以设置为语料库中排除测试集的文档吗？
谢谢
