### ISSUE TITLE
help!!!!!

### ISSUE THREAD

**Issue by khazic** [FlagOpen/FlagEmbedding#786]
你好我用你们的代码训练的bgem3 我训练的是那个多模型训练的形式 训练完成之后但是在mulvus上无法正常的调用 是什么情况呢？

**Comment by haibincoder** [comment]
1. bgem3是embedding模型，mulvus是向量引擎，这两部分是单独的，你是embedding输出有问题还是向量引擎使用有问题？
2. “无法正常的调用”，你至少要把输入输出和错误信息贴出来，不然没人能帮你解决

**Comment by khazic** [comment]
解决啦 是模型没保存完 才报错了

bin ***@***.***>于2024年5月15日 周三上午10:20写道：
