### ISSUE TITLE
微调bge-large-zh-v1.5后在自己的数据上评估

### ISSUE THREAD

**Issue by Tungsong** [FlagOpen/FlagEmbedding#797]
不懂这行代码有什么作用，引入时报错
![image](https://github.com/FlagOpen/FlagEmbedding/assets/35001280/7c79bf83-5715-4387-8ca8-3ec70a403305)

**Comment by Tungsong** [comment]
还有一个问题是按文档运行了微调bge-large-zh-v1.5之后报错的模型目录如下，是正常的吗
![image](https://github.com/FlagOpen/FlagEmbedding/assets/35001280/b3e04479-76ed-4f60-a090-b857d9c37412)

**Comment by namespace-Pt** [comment]
hi，感谢指出，之前忘记删了，已更新。
