### ISSUE TITLE
增量预训练

### ISSUE THREAD

**Issue by lizepengg** [FlagOpen/FlagEmbedding#803]
这个如果要进行增量训练的话，是不是数据集的格式和预训练相同，直接使用那个预训练的脚本文件运行啊？（在此处使用特定领域的数据集进行预训练是不是可以相当于是增量训练？），之后训练的评估指标也是可以直接使用那个评估的脚本文件来进行评价吗？

**Comment by staoxiao** [comment]
yes, you can use this script: https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/pretrain to do pre-training. However, the pre-trained model cannot be used to compute similarity between text, so it cannot be evaluated with our script. You need to fine-tune the pre-trained model and then evaluate its retrieval performance.
