### ISSUE TITLE
finetune model

### ISSUE THREAD

**Issue by Cloopen-ReLiNK** [FlagOpen/FlagEmbedding#83]
finetune modeling.py里的
BiEncoderModel  q_reps = self.encode(query)  训练的时候为什么在一个batch中输入相同的feature：input_ids、attention_mask、token_type_ids，得到的embeeding不一样

**Comment by staoxiao** [comment]
因为存在dropout层，训练时的向量是会不一样的。

**Comment by Cloopen-ReLiNK** [comment]
> 因为存在dropout层，训练时的向量是会不一样的。

这个dropout在哪里？代码中好像没看到

**Comment by Cloopen-ReLiNK** [comment]
> > 因为存在dropout层，训练时的向量是会不一样的。
> 
> 这个dropout在哪里？代码中好像没看到

bert自己的drop out？attention_probs_dropout_prob hidden_dropout_prob

**Comment by staoxiao** [comment]
> bert自己的drop out？attention_probs_dropout_prob hidden_dropout_prob

是的
