### ISSUE TITLE
向量检索后续优化思路

### ISSUE THREAD

**Issue by YYGe01** [FlagOpen/FlagEmbedding#841]
你好，我有一个问题：居住建筑中对于台阶、楼梯踏步数的相关要求？

然后去向量数据库中做答案搜索，发现排名靠前的，虽然都提及到了  台阶、楼梯踏步数的相关要求，但是主语不是居住建筑，而是其他的建筑，比如厂房，公园等等，而住宅建筑相关的答案，排名较后面。

用的bge-m3模型，我想问下，如果想改善上述问题，让住宅建筑相关内容能靠前，也就是让模型更关注主语的匹配，而不是把重点放在具体内容上，有什么比较好的方法嘛。

有不用微调的方法嘛，可能数据不太够。
如果实在要微调，在准备微调数据上面可以有哪些侧重呢，谢谢

**Comment by staoxiao** [comment]
@YYGe01 , I think re-ranker model can have better performance than the embedding model in this task. You can use the reranker model to rerank data.
