### ISSUE TITLE
reranker模型微调，单机多卡会比单卡慢很多。

### ISSUE THREAD

**Issue by zlh-source** [FlagOpen/FlagEmbedding#848]
你好，我正在尝试用下面的脚本微调bge-reranker-v2-m3，在我的数据上，单卡a100(40G)需要20小时的训练时间，但是2卡训练时，其它超参数保持不变，需要30小时，4卡大约是40小时。请问可能的原因有哪些？

torchrun --nproc_per_node {number of gpus} \
-m FlagEmbedding.reranker.run \
--output_dir {path to save model} \
--model_name_or_path BAAI/bge-reranker-v2-m3 \
--train_data ./toy_finetune_data.jsonl \
--learning_rate 6e-5 \
--fp16 \
--num_train_epochs 5 \
--per_device_train_batch_size {batch size; set 1 for toy data} \
--gradient_accumulation_steps 4 \
--dataloader_drop_last True \
--train_group_size 16 \
--max_len 512 \
--weight_decay 0.01 \
--logging_steps 10 

运行环境：
CUDA Version: 11.8
pytorch：2.2.1+cu118
transformers：4.40.1

**Comment by staoxiao** [comment]
@zlh-source , please make sure that you use the same `per_device_train_batch_size` when using more GPUs.

**Comment by zlh-source** [comment]
> @zlh-source , please make sure that you use the same `per_device_train_batch_size` when using more GPUs.

是的，单卡/多卡的per_device_train_batch_size是相同的（在我的脚本里，都是8）
