### ISSUE TITLE
Error when running the finetune script 

### ISSUE THREAD

**Issue by FlyingBird11** [FlagOpen/FlagEmbedding#85]
I'd like to finetune the model on multi-gpus in DataParallel model. When executes the script "FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/run.py", it reports the error

  File "/root/anaconda3/envs/emb/lib/python3.11/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

I have tried to add "model = torch.nn.DataParallel(model)", but the error still exists.
Only when applying the " os.environ["CUDA_VISIBLE_DEVICES"]="0" ", the finetune script works well.

How to solve it ?
Thanks

**Comment by staoxiao** [comment]
Hi, DistributedDataParallel is more efficient than DataParallel and can be used easily: `torchrun --nproc_per_node {number of GPUs}` , so we suggest to use DistributedDataParallel. If want to use DataParallel , you only need to replace the `torchrun --nproc_per_node {number of GPUs}`  with `python` and delete `--negatives_cross_device`.

**Comment by FlyingBird11** [comment]
That works. Thank you!
