### ISSUE TITLE
模型合并问题！！！

### ISSUE THREAD

**Issue by lower01** [FlagOpen/FlagEmbedding#860]
如何让模型合并的程序最后保存模型的格式为bin？
![image](https://github.com/FlagOpen/FlagEmbedding/assets/45301618/32b0c698-07e5-4a01-ae27-78572d3ca007)
README中的示例程序会自动保存为safetensors格式，如何让其自动保存为bin格式？在哪里可以设置修改？

**Comment by staoxiao** [comment]
You can save the model following: https://github.com/huggingface/transformers/issues/28863
