### ISSUE TITLE
请问使用BGE做分类Fintune的方法

### ISSUE THREAD

**Issue by 1006076811** [FlagOpen/FlagEmbedding#87]
首先感谢贵团队对开源世界做出的贡献，这个项目非常棒！
我的问题是：
我想使用BGE在领域数据上做分类，首先是不是应该使用对比学习的语句对数据进行Fintune BGE，然后在这个结果上再使用分类数据从Fintune模型的基础上加个线性层和softmax训练分类模型呢？

**Comment by staoxiao** [comment]
您好，直接用分类数据finetune就可以，使用对比学习的语句对数据进行finetune不是必须的

**Comment by 1006076811** [comment]
> 您好，直接用分类数据finetune就可以，使用对比学习的语句对数据进行finetune不是必须的
感谢您的回答。
直接finetune的话，我理解的数据格式是query对应原句子， pos对应label，neg应该给什么数据呢？抽非本分类的任意标签即可吗？

**Comment by 1006076811** [comment]
> 您好，直接用分类数据finetune就可以，使用对比学习的语句对数据进行finetune不是必须的

感谢您的回答

如果直接fintune的话，分类数据的格式是否可以按如下构造：
query->原始句子， pos->分类标签， neg->抽取非本分类的任意标签

**Comment by staoxiao** [comment]
这是一种可行的方式，建议neg包含所有非本分类的标签，同时设置train_group_size=标签数量，使得可以像加线性层和softmax那样一次能见到所有分类标签。但不确定这种方式是否会比加线性层和softmax训练好。

**Comment by 1006076811** [comment]
非常感谢您的回答
