### ISSUE TITLE
Segmentation Fault on BGEM3FlagModel  Import - Mac M1

### ISSUE THREAD

**Issue by liamfranke** [FlagOpen/FlagEmbedding#872]
Hello,

I have been using this model recently without fail - however, today I installed the latest version, and now I am getting the following error message when importing the package: `zsh: segmentation fault  python3 main.py`

This occurs on the import. I have tried printing above and below, and it never gets past the import of the BGEM3FlagModel

```
from FlagEmbedding import BGEM3FlagModel    
model = BGEM3FlagModel('BAAI/bge-m3',  use_fp16=True)
```

I am very curious as to how this issue started occurring, and how I should go about resolving it. 

Thank you!

**Comment by staoxiao** [comment]
Hi, @liamfranke , this error is strange. You can try to re-install the package.

**Comment by liamfranke** [comment]
Closing - my laptop was on a previous version. Upgrading my OS resolved all issues.

**Comment by leopeng1995** [comment]
What is your OS version? I have the same problem now, the version is 14.5 @liamfranke
