### ISSUE TITLE
VISTA v.s UniIR

### ISSUE THREAD

**Issue by gordonhu608** [FlagOpen/FlagEmbedding#881]
Congratulations on a great work of VISTA retriever. However, could you compare your performance with an existing method UniIR, especially, on the task WebQA (since you both tested on it). I'm confused which method in zero-shot WebQA dataset have higher performance.

**Comment by JUNJIE99** [comment]
Thank you for your attention!

If I understand correctly, UniIR has fine-tuned on their MBEIR, which includes data from WebQA. Therefore, UniIR cannot test the zero-shot results on WebQA. However, a model variant proposed by UniIR, $CLIP_{sf}$, can be used without training, which is the result reported in Table 6 of the UniIR paper for SoTA Zero-Shot.

As you can see in their Table 6, they have split the WebQA candidates into two corpora, one for pure text candidates and one for image-text candidates. In our paper, all of our tests are conducted on the complete corpus of WebQA.

Therefore, if corresponding to the results in UniIR's Table 6, VISTA's $q_{t}$ -> $c_{t}$ is 69.46, $q_{t}$ -> $c_{it}$ is 64.34. If it is a mixed corpus, then it is 60.11. All of these significantly surpass the SoTA Zero-shot reported by UniIR.

If you have any further questions, feel free to discuss with us.

**Comment by gordonhu608** [comment]
Thank you so much for your prompt and helpful reply. Great work!

**Comment by shriram1998** [comment]
Are the above results for separate image and text retrieval metrics reported anywhere in the paper or docs?
