### ISSUE TITLE
微调之后效果较差

### ISSUE THREAD

**Issue by 34127chi** [FlagOpen/FlagEmbedding#89]
如题，比不微调效果差，并且归一化后得分很低，都接近0。微调的语料是法律领域，不知道啥原因

**Comment by staoxiao** [comment]
注意训练时候loss是否正常。数据对效果影响很大，需要保证微调数据的质量，同时可以使用hn_mine脚本挖掘难负样本提高效果。另外，微调参数注意batch size不能太小。
