### ISSUE TITLE
Can you add the results about ShareGPT4Video-8B on MLVU benchmark?

### ISSUE THREAD

**Issue by xiaoachen98** [FlagOpen/FlagEmbedding#898]
Thanks for your awesome work of building a solid benchmark for understanding long videos. I wonder if you could add the results about ShareGPT4Video-8B on MLVU. We provide the inference code [here](https://github.com/ShareGPT4Omni/ShareGPT4Video), very easy to follow. Many thanks!

**Comment by JUNJIE99** [comment]
Thank you for your interest. We will be conducting an evaluation of ShareGPT4Video-8B on MLVU in the coming days. Once the results are ready, we will inform you via email.

Furthermore, to ensure better future maintenance of MLVU, we have recently relocated the repository to https://github.com/JUNJIE99/MLVU. We cordially invite you to follow our new repository.

**Comment by xiaoachen98** [comment]
> Thank you for your interest. We will be conducting an evaluation of ShareGPT4Video-8B on MLVU in the coming days. Once the results are ready, we will inform you via email.
> 
> Furthermore, to ensure better future maintenance of MLVU, we have recently relocated the repository to https://github.com/JUNJIE99/MLVU. We cordially invite you to follow our new repository.

That's great! Thank you sooooo much!!
