### ISSUE TITLE
Sequence Length 512是最大token数还是最大字符长度

### ISSUE THREAD

**Issue by ftufkc** [FlagOpen/FlagEmbedding#91]
以中文为例，想知道bge-large-zh在MTEB中标明的Sequence Length 512是最大token数还是中文文本的最大字符长度呢？如果超长模型会进行截断是吗？

**Comment by staoxiao** [comment]
是最大token数量。是的，超过512个token会进行截断，只保留最前面的512。

**Comment by ftufkc** [comment]
明白了。另外，想补充请教一个问题，我在readme中有看到关于langchain的教程，但其中似乎并不涉及为短查询添加指令部分。

**Comment by staoxiao** [comment]
有query_instruction参数，langchain中会自动为query加上这个指令

**Comment by nanyoullm** [comment]
微调代码中的 passage_max_len 是不是也应该设置成 512 呢，我看参数解释是
```The maximum total input sequence length after tokenization for passage. Sequences longer than this will be truncated, sequences shorter will be padded.```
看着是和题主Sequence Length一个意思

**Comment by staoxiao** [comment]
> 微调代码中的 passage_max_len 是不是也应该设置成 512 呢，我看参数解释是 `The maximum total input sequence length after tokenization for passage. Sequences longer than this will be truncated, sequences shorter will be padded.` 看着是和题主Sequence Length一个意思

您好，这个passage_max_len 和query_max_len可以根据实际数据的分布进行调整，如果数据都很长，就应该设成512。如果数据都很短，就没有必要设成512，那样会比较消耗显存。
