### ISSUE TITLE
rerank模型返回参数保持一致

### ISSUE THREAD

**Issue by danerlt** [FlagOpen/FlagEmbedding#922]
scores长度为1的时候不要返回一个浮点数，如果一定要返回浮点数，加个参数控制，：
![image](https://github.com/FlagOpen/FlagEmbedding/assets/14197717/cd4480f5-7c21-4d33-98d9-eac72df2a93c)

**Comment by kaleyroy** [comment]
嗯，支持！
建议保持返回一个 数组，即使只有一个元素（保持接口一致）。 
实际调用中只有一个元素的时候，还得特别注意的这个地方。

**Comment by staoxiao** [comment]
感谢反馈，repo里的代码已修改
