### ISSUE TITLE
bge-reranker-large 按照readme微调时warning find_unused_parameters=True was specified in DDP constructor

### ISSUE THREAD

**Issue by HuXiLiFeng** [FlagOpen/FlagEmbedding#925]
bge-reranker-large、bge-reranker-base 按照readme微调时，提示如下，请问这个正常吗
> Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

**Comment by staoxiao** [comment]
不用理会这个warning
