### ISSUE TITLE
关于预训练数据的问题

### ISSUE THREAD

**Issue by Harmon-l** [FlagOpen/FlagEmbedding#93]
您好，非常感谢您的工作，关于预训练有两个问题想向您请教：
1.预训练的text文本长度有要求吗，脚本里给的默认参数max_seq_length=512，是需要提供长文本给模型吗？使用短文本是否也可以进行预训练？
2.关于预训练的数据量，如果在bge-large-zh上继续预训练的话，至少需要多少条text才可以？
感谢您的回答~！

**Comment by staoxiao** [comment]
1. 使用短文本也是可以的，但是要保证短文本也有比较完整的语义。
2. 要提升下游任务的效果，预训练数据应该与下游任务相关，越多越好，上万条比较好

**Comment by Harmon-l** [comment]
1.{“text”: "操作后即时生效"}
2.{“text”: "内页信息应与实际情况相匹配"}
3.{“text”: "本方法自2022年11月17日开始实施"}
请问这样的短文本是否满足预训练数据需要呀

**Comment by staoxiao** [comment]
可以的。但是这种数据也不适合做检索？如果要训练的话，可以用检索的候选集做训练数据

**Comment by Harmon-l** [comment]
了解，非常感谢您的回答！

**Comment by Harmon-l** [comment]
您好，请问预训练之后得到的encoder_model可以直接应用于文档匹配吗，还是也需要进行finetune之后才可以使用？ @staoxiao

**Comment by staoxiao** [comment]
> 您好，请问预训练之后得到的encoder_model可以直接应用于文档匹配吗，还是也需要进行finetune之后才可以使用？ @staoxiao

您好，预训练之后需要finetuen的

**Comment by Harmon-l** [comment]
了解，请问在做下游任务时，直接对bge-large-zh进行finetune，以及在bge-large-zh基础上预训练+finetune区别大吗？二次预训练对下游任务能力提升大吗？

**Comment by staoxiao** [comment]
抱歉，我们无法给出一个准确的结论，这跟下游任务和数据质量都有关。如果是对模型训练不熟悉的话，建议直接fine-tune就好，省时省力。

**Comment by Harmon-l** [comment]
好的，感谢您的回复！
