### ISSUE TITLE
关于Embedding是否支持大小写无关问题

### ISSUE THREAD

**Issue by FmKnight** [FlagOpen/FlagEmbedding#934]
目前我司在使用bge-m3 embedding模型 + milvus2.4.4混合检索版本 实现知识库功能。请问bge-m3是否支持大小写无关的embedding向量，在网络上搜索相关问题，未得到明确的答案，经过实验，bge-m3 embedding是大小写敏感的。请问是否有相关参数设置，或者有其他方式进行解决

测试用例：

原文中包含“KRAS G12C”这一大写专有名词，问题"KRAS G12C相关进展"与"kras g12c相关进展"，搜索结果相差很大，“KRAS G12C相关进展”能否较好匹配；小写则不然，milvus稠密检索与稀疏检索结果匹配程度很低，检索结果牛头不对马嘴。

**Comment by staoxiao** [comment]
@FmKnight ， 目前bge-m3使用的是xlm-roberta的词表，其词表是区分大小写的。
可以尝试在生成向量时，将问题和候选文本都小写化，避免大小写的错配。

**Comment by FmKnight** [comment]
@staoxiao 谢谢解答！
