### ISSUE TITLE
关于CMTEB的评测问题

### ISSUE THREAD

**Issue by Zhouziyi828** [FlagOpen/FlagEmbedding#939]
由于网络限制的原因，无法加载huggingface上面的数据集，只能使用本地的数据集进行评测，有什么方法么？我尝试在C_MTEB文件夹中更改T2Reranking类中的hf_hub_name，但是没有用，依然会加载huggingface上的数据集

**Comment by staoxiao** [comment]
可以设置hf mirror:https://hf-mirror.com/

**Comment by Zhouziyi828** [comment]
谢谢，我还想问一下如何将损失输出，以便我后面再tensorboard中查看损失下降的情况？

**Comment by LRW2000** [comment]
> 由于网络限制的原因，无法加载huggingface上面的数据集，只能使用本地的数据集进行评测，有什么方法么？我尝试在C_MTEB文件夹中更改T2Reranking类中的hf_hub_name，但是没有用，依然会加载huggingface上的数据集

你的这个问题解决了吗？我在Reranking.py文件添加
import os
os.environ["HF_HUB_ENDPOINT"] = "https://hf-mirror.com"
运行后还是报：ConnectionError: Couldn't reach 'C-MTEB/T2Reranking' on the Hub (ConnectionError)

**Comment by LRW2000** [comment]
> 可以设置hf mirror:https://hf-mirror.com/

这种方法我也试了，还是不行。使用下载好的本地数据集的话，需要修改哪些地方，直接修改hf_hub_name是不行的，这样还是会去huggingface下载。
