### ISSUE TITLE
关于构造1.2亿训练数据对

### ISSUE THREAD

**Issue by JDZW2014** [FlagOpen/FlagEmbedding#94]
非常感谢开源这么棒的工作。
请问1.2亿的大规模微调数据集是如何构造的呢？  能详细说一下吗，非常感谢！！！

**Comment by staoxiao** [comment]
您好，对于问答数据，使用的是question-answer对，对于网页数据，使用的是title和内容对。同时，使用向量模型计算相似度，过滤掉相似度太低的数据对。近期会尝试对数据进行开源。

**Comment by JDZW2014** [comment]
好的，非常感谢，努力向大佬学习。
