### ISSUE TITLE
BGE-M3模型在相似度上，搭配使用的一些物品在相似度上是否会相近？比如电磁炉和蒸锅，筷子和碗？

### ISSUE THREAD

**Issue by jiangsiYang** [FlagOpen/FlagEmbedding#940]
如题，想了解这方面的特性，谢谢

**Comment by staoxiao** [comment]
您好，没有做过这方面实验，我们也不太确定。

**Comment by jiangsiYang** [comment]
> 您好，没有做过这方面实验，我们也不太确定。

你好，谢谢你的回答。想请教下，现在的embeding模型还是主要在语义相似度上的训练？通常并不会考虑问题所述的那种训练？
