### ISSUE TITLE
向量化中的文本有办法对特定的一些词给与更高的权重吗？

### ISSUE THREAD

**Issue by jiangsiYang** [FlagOpen/FlagEmbedding#941]
比如“非常甜,性价比高, 售后快，非常适合宝宝食用”，我想突出“性价比高”这个词语，能做到吗？谢谢！

**Comment by staoxiao** [comment]
可以尝试把性价比高这几个词重复多次放到文本里

**Comment by jiangsiYang** [comment]
> 可以尝试把性价比高这几个词重复多次放到文本里

有点道理，👍
