### ISSUE TITLE
vespa 如何通过colbert类型查询?

### ISSUE THREAD

**Issue by jiangsiYang** [FlagOpen/FlagEmbedding#947]
我实践了这里的https://github.com/vespa-engine/pyvespa/blob/master/docs/sphinx/source/examples/mother-of-all-embedding-models-cloud.ipynb 
但是这里有点疑惑，这还是通过dense_rep匹配的吧，那么我想通过colbert_rep字段匹配该怎么做呢？谢谢
response: VespaQueryResponse = app.query(
    yql="select id, text from m where userQuery() or ({targetHits:10}nearestNeighbor(dense_rep,q_dense))",
    ranking="m3hybrid",
    query=query[0],
    body={**query_fields},
)

**Comment by jiangsiYang** [comment]
这样查询会报错
response: VespaQueryResponse = app.query(
    yql="select act_id, text from act_tag where ({targetHits:10}nearestNeighbor(colbert_rep,q_colbert))",
    ranking="m3hybrid",
    query=query[0],
    body={**query_fields},
)


VespaError: [{'code': 3, 'summary': 'Illegal query', 'source': 'qjl_content', 'message': 'NEAREST_NEIGHBOR {field=colbert_rep,queryTensorName=q_colbert,hnsw.exploreAdditionalHits=0,distanceThreshold=Infinity,approximate=true,targetHits=10} tensor query(q_colbert) must have exactly 1, indexed dimension, but was: tensor<bfloat16>(qt{},x[1024])'}]

**Comment by staoxiao** [comment]
可以到vespa仓库提问
