### ISSUE TITLE
预训练与微调两阶段，哪个阶段效果收益更大

### ISSUE THREAD

**Issue by Qzsl123** [FlagOpen/FlagEmbedding#95]
如题，
1）预训练和微调两个阶段，哪个阶段对MTEB和C-MTEB榜单上的效果影响更大？
2）使用微调的3.5亿文本对，换一个其他的底座是不是效果也很好？

**Comment by staoxiao** [comment]
预训练并不能学习相似度区分，需要进行对比学习微调才能进行评测。
实验中，预训练之后的底座会在检索任务上明显好于其他底座。之后会放出相关论文。
