### ISSUE TITLE
关于Query vs Query微调数据的选择

### ISSUE THREAD

**Issue by natlank** [FlagOpen/FlagEmbedding#950]
https://mp.weixin.qq.com/s/DC0-so_8pVUfcz7lGhYwlQ 文章中写到：
Embedding 微调：通用 Embedding 模型不足以应对用户口语化严重的问题，需要针对具体业务场景进行微调，以过滤无关信息并提高准确度。我们有四种不同的构造数据的方案，在实践中都有不错的表现：
Query vs Original：简单高效，数据结构是直接使用用户 query 召回知识库片段；
Query vs Query：便于维护，即使用用户的 query 召回 query，冷启动的时候可以利用模型自动化从对应的知识片段中抽取 query；
Query vs Summary：使用 query 召回知识片段的摘要，构建摘要和知识片段之间的映射关系；
F-Answer vs Original：根据用户 query 生成 fake answer 去召回知识片段。
经过微调后的 Embedding 模型在召回上会有大幅地提升。top 5 召回达到 100%。

请问Query vs Query是怎么构造的？它比较重要吗？是用于应对用户口语化严重的问题的吗？
我如果要构建Query vs Query数据集的话还是按照这个格式吧{"query": str, "pos": List[str], "neg":List[str]}，其中positive是应该怎么生成呢，用其他大模型api生成用户query相似的问题，还是别的方法？谢谢！

**Comment by staoxiao** [comment]
@natlank ， 这个文章是智谱的，我们并不清楚具体方法。但使用大模型生成query是一种可行思路。

**Comment by natlank** [comment]
好的，非常感谢
