### ISSUE TITLE
关于llm-embedder的一些疑问

### ISSUE THREAD

**Issue by HuXiLiFeng** [FlagOpen/FlagEmbedding#952]
1、BAAI/llm-embedder不支持中文，那我现在用一个支持中文的query_encoder，按[fine-tune.md](https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/llm_embedder/docs/fine-tune.md)说明的如下脚本微调，这算是微调出支持中文的一个llm-embedder吗？
```
CUDA_VISIBLE_DEVICES="0,2" nohup torchrun --nproc_per_node=2 run_dense.py \
--output_dir data/outputs/icl \
--train_data llm-embedder:train.jsonl \
--save_steps 6000 \
--query_encoder BAAI/bge-large-zh-v1.5 \
--version zh_llm_embedder \
--inbatch_same_dataset epoch \
--learning_rate 2e-5 \
--num_train_epochs 2 \
--train_group_size 15 \
--per_device_train_batch_size 16 \
--cos_temperature 0.02 \
--dtype fp32 \
--report_to tensorboard \
--data_root data >log.log 2>&1 &
```
指令配置如下：
```
    "zh_llm_embedder": {
        "instruction": {
            "icl": {
                "query": "为这个句子生成表示以用于检索相关文章: ",
                "key": "",
            }
        },  
    },
```
用的是icl任务，训练数据形如:
```
{"query":"今天星期几","pos":[xxxx],"neg":[xxxx],"task":"icl"}
```

2、按照上述脚本训练完之后，模型保存路径文件如下：

> ├── args.json
├── encoder
│   ├── config.json
│   ├── model.safetensors
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   ├── tokenizer.json
│   └── vocab.txt
├── runs
│   └── Jul10_11-27-29_ai-app
│       └── events.out.tfevents.1720582213.ai-app.33398.0
├── special_tokens_map.json
├── tokenizer_config.json
├── tokenizer.json
└── vocab.txt

按照fine-tune.md里面所说，如果要使用sentence_transformer加载，还得做一下转换
![image](https://github.com/FlagOpen/FlagEmbedding/assets/20320649/1e597abc-f9d2-4b3a-8b9a-e1169c31482d)

运行这个脚本时，提示如下：

> loading model from ./data/outputs/icl/encoder and saving the sentence_transformer model at ./data/outputs/st_model...
Some weights of BertModel were not initialized from the model checkpoint at ./data/outputs/icl/encoder and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

请问这个有问题吗

**Comment by staoxiao** [comment]
这个warning没有问题的，pooler并没有使用到，可以忽略，

**Comment by HuXiLiFeng** [comment]
> 这个warning没有问题的，pooler并没有使用到，可以忽略，

那请问第一个问题呢，麻烦也帮忙看看

**Comment by staoxiao** [comment]
算的，模型和数据都替换中文是可以微调出中文模型的
