### ISSUE TITLE
关于预训练的一些细节咨询

### ISSUE THREAD

**Issue by stanpcf** [FlagOpen/FlagEmbedding#96]
非常赞的工作。
中文模型的预训练使用的数据是wudao，我看有3个体量（200G、3T、5T）的数据集，请问用的是哪个呢。

另外总结了一下这个工作的预训练的一些细节，辛苦看一下是否正确哈~
- encoder初始化模型：来自[https://huggingface.co/hfl](https://huggingface.co/hfl)（来自[https://huggingface.co/BAAI/bge-large-zh/discussions/6](https://huggingface.co/BAAI/bge-large-zh/discussions/6)），尚不清楚具体是哪个模型
- 训练： 预训练是在24块A100(40G) gpu上进行的，batch大小为720。在retromae中，编码器和解码器的掩码率分别为0.3和0.5。 使用AdamW优化器，学习率为2e-5（参考readme）
- 数据：wudao，尚不清楚是200G/3T/5T哪个数据集。参考[https://github.com/FlagOpen/FlagEmbedding/issues/30](https://github.com/FlagOpen/FlagEmbedding/issues/30)大概过了720\*18w=1.3亿数据（3个epoch的话则数据集大小为4kw），合计为1.3亿\*512=66.6B的token量。训练了2周（[https://github.com/FlagOpen/FlagEmbedding/issues/19#issuecomment-1672566678](https://github.com/FlagOpen/FlagEmbedding/issues/19#issuecomment-1672566678)）。

**Comment by staoxiao** [comment]
wudao 是200G的版本。初始化模型是https://huggingface.co/hfl/chinese-roberta-wwm-ext。中英文模型的lr不太一样，中文上面large/base/small是5e-5, 10e-5, 15e-5

**Comment by lifeng7777** [comment]
@staoxiao 大佬，我有两个问题想咨询下：
1. bge-large-en使用哪个基座模型初始化的呢，我看retromae仓库里用的是bert-base-uncased，bge用的也是这个么？
2. 另外还想咨询下预训练时pile的800g数据集是全部都用了么，是直接用的还是重新清洗过呢？
希望您能帮忙解答！

**Comment by staoxiao** [comment]
1. en是bert-large-uncased-whole-word-masking
2. 全部的数据
