### ISSUE TITLE
Finetune模型数据处理与测试

### ISSUE THREAD

**Issue by fskong** [FlagOpen/FlagEmbedding#963]
您好，能否提供一下sst2，mnli等任务的数据处理与测试代码？即，复现 LM-Cocktail 文章中 Table 1 后三列（Fine-tuned，LM-Cocktail2，LM-Cocktail10）结果的代码。
谢谢！

**Comment by staoxiao** [comment]
参考https://github.com/FlagOpen/FlagEmbedding/tree/master/LM_Cocktail#1-reproduce-the-results-of-llm

**Comment by fskong** [comment]
感谢！
