### ISSUE TITLE
关于微调Reranker时正负例比例设定的问题 About the ratio of pos and negs while fine-tuning Reranker

### ISSUE THREAD

**Issue by Kaguya-19** [FlagOpen/FlagEmbedding#966]
bge-reranker is a very good work, and we fine-tune it on our own data. However, we see that the fine-tuning script in FlagEmbedding provides that the ratio of positive and negative cases is 1:15. Considering that the general classification task usually sets the ratio of positive and negative cases to 1:1, is there any experiment for the setting of multiple negative cases? Thank you very much!

bge-reranker是一个非常好的工作，我们打算在自己业务数据上微调它。然而，我们看到FlagEmbedding中的微调脚本提供的是正负例标准是1:15，考虑到一般分类任务将正负例比例设为1:1，多个负例的选取是否有实验验证？非常感谢！

**Comment by staoxiao** [comment]
使用的是交叉熵损失，一般而言，负样本数量多效果更好

**Comment by Kaguya-19** [comment]
谢谢哥，有道理
