### ISSUE TITLE
finetune调参相关咨询

### ISSUE THREAD

**Issue by PNightOwlY** [FlagOpen/FlagEmbedding#97]
```bash
torchrun --nproc_per_node {number of gpus} \
-m FlagEmbedding.baai_general_embedding.finetune.run \
--output_dir {path to save model} \
--model_name_or_path BAAI/bge-large-en \
--train_data ./toy_finetune_data.jsonl \
--learning_rate 1e-5 \
--fp16 \
--num_train_epochs 5 \
--per_device_train_batch_size {large batch size; set 1 for toy data} \
--dataloader_drop_last True \
--normlized True \
--temperature 0.02 \
--query_max_len 64 \
--passage_max_len 256 \
--train_group_size 2 \
--negatives_cross_device \
--query_instruction_for_retrieval "为这个句子生成表示以用于检索相关文章：" 
```

老师，您好！想请问一下这里的finetune技巧：
1. train_group_size这里设置为多少比较合适呢？有没有推荐的negatives的大小？因为这个值调大了，那么每次都用的batch_size就变小的，这里有trade-off实验吗？
2. temperature这里默认0.02是最好的吗，还是说要具体看下游的任务？
3. 还有其他参数可以调整吗？

**Comment by staoxiao** [comment]
1. train_group_size 我们实验里默认用的8，可以依据训练数据中neg的平均数量指定。推荐挖掘出难负样本进行训练，这样可以不那么依赖很大的batch size去提供高质量负样本。
2. 不一定。但一般temperature越大效果越差，一般设为0.01或者0.02，但较小的temperature(如0.01）会导致整体相似度偏高（依然会保证相似度的排序关系），所以这里取了一个trade-off 0.02。
3. passage_max_len 和query_max_len 应该按照数据集的长度来定，例子里的64和256只是一个样例，如果文档都很长的话，需要增大passage_max_len ，都很短的话可以减小passage_max_len 加快训练速度。
