### ISSUE TITLE
Biencoder diff between FlagOpen/FlagEmbedding and RetroMAE/src/biencoder/ ?

### ISSUE THREAD

**Issue by wuji3** [FlagOpen/FlagEmbedding#971]
I find that there are two repo having Biencoder code-base, one is https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/baai_general_embedding/finetune/modeling.py
another is https://github.com/staoxiao/RetroMAE/blob/master/src/bi_encoder/modeling.py, could you share me which is better in modeling embedding. 
I find the latter is equipped with distilling by crossencoder. 
By the way, not only Biencoder, Crossencoder also catches my interest between two repos.

Looking forward to your sharing.

**Comment by staoxiao** [comment]
There is no difference between these two repos (except the latter can do knowledge distillation).  
Considering that the code for the retromae project is quite old and I haven't run it in a long time, I recommend using our new project: FlagEmbedding.
