### ISSUE TITLE
MLVU: some answers are not in the candidates

### ISSUE THREAD

**Issue by Richar-Du** [FlagOpen/FlagEmbedding#976]
Thanks for your work in MLVU. I found some errors in the benchmark, i.e., some answers are not in the candidates:
<img width="828" alt="image" src="https://github.com/user-attachments/assets/6030cca6-462d-420f-a275-2964c345bfcf">

**Comment by JUNJIE99** [comment]
Thank you very much for your reminder. We have just rechecked all the data and found typos in two questions. We are very sorry for this, and we have made corrections.

**Comment by Richar-Du** [comment]
Thanks for your correction :)
