### ISSUE TITLE
Can BGE-M3 use commands to optimize the search effect?

### ISSUE THREAD

**Issue by Amphetaminewei** [FlagOpen/FlagEmbedding#978]
It is mentioned in the documentation that BGE-1.5 can optimize search performance by query instruction "为这个句子生成表示以用于检索相关文章：", can the BGE-M3 be optimized in a similar way?

**Comment by staoxiao** [comment]
@Amphetaminewei , the bge-m3 is trained without instruction, so adding instruction should not improve the performance.
