### ISSUE TITLE
关于fine-tune涉及到的参数

### ISSUE THREAD

**Issue by runwean** [FlagOpen/FlagEmbedding#98]
非常棒的工作，点赞👍
有一个细节想要咨询下，就是关于对比学习中的fine-tune是全参数微调吗？如果不是那微调涉及到的参数有哪些呢？
此外，这块的代码涉及到的position_embedding的用意是？👇

`
    if training_args.fix_position_embedding:
        for k, v in model.named_parameters():
            if "position_embeddings" in k:
                logging.info(f"Freeze the parameters for {k}")
                v.requires_grad = False`

**Comment by staoxiao** [comment]
谢谢~
fine-tune是全参数微调。fix_position_embedding默认是false，之前参考过e5 embedding 的策略固定住position emedding，后面取消了这一设定。
