### ISSUE TITLE
can  bge-m3 unsupervised be directly used on the real task? 

### ISSUE THREAD

**Issue by sunzx8** [FlagOpen/FlagEmbedding#983]
which one is better?

**Comment by staoxiao** [comment]
@sunzx8 , we don't release a version of bge-m3 supervised.

**Comment by sunzx8** [comment]
sorry,my bad , i mean the unsupervised version,can it be directly used on the real task?

**Comment by staoxiao** [comment]
> sorry,my bad , i mean the unsupervised version,can it be directly used on the real task?

It can be used to compute similarity, but the performance may not be good.
