### ISSUE TITLE
对单个词的embedding计算不符合预期

### ISSUE THREAD

**Issue by Awezome** [FlagOpen/FlagEmbedding#99]
https://huggingface.co/BAAI/bge-base-zh 使用demo 测试发现结果不符合预期，[男孩] 应该比 [狗] 相对[人]的距离更近吧：

![image](https://github.com/FlagOpen/FlagEmbedding/assets/3314334/b0a76d82-64bf-48a8-a1b8-ad6116e97352)

**Comment by staoxiao** [comment]
只有一个单词，没有上下文语义，个人觉得这种case意义不大， 也不符合bge的使用场景

**Comment by staoxiao** [comment]
确实不是很符合人类预期。试了一下[text2vec](https://huggingface.co/shibing624/text2vec-base-chinese) 也出现这种情况。无法保证模型所有的输出都符合人类认知。

**Comment by staoxiao** [comment]
抱歉，弄混了，指的是m3e-base也是这样，因为加上了检索任务，短问题检索长答案，模型对这种语义相似度的任务会下降，但QA或者大模型增强主要还是检索任务。
这个例子在bge-base-zh-v1.5中是正常的，您可以使用新版本的bge。
